Fix Show All
zeus-health/ctw-component-library pull request #1038
Opened 2023-07-27 19:16 UTC by pmadria3

Added a UseEffect to make sure the show all is only rendered after the records length is 0

2023-07-27 20:09 UTC, patrickvalle requested changes

2023-07-27 20:09 UTC, patrickvalle commented on src/components/core/table/table.tsx
> +    setCount(pageSize);
I think there should be an `else` here, otherwise this is going to execute regardless of the above `if`

2023-07-27 20:17 UTC, pmadria3 commented on src/components/core/table/table.tsx
> +    setCount(pageSize);
good catch!

2023-07-28 13:56 UTC, patrickvalle approved these changes
lgtm

2023-07-28 14:23 UTC, patrickvalle approved these changes

2023-07-28 14:25 UTC, merged