CTW-370/patientid-guard
zeus-health/ctw-component-library pull request #104
Opened 2022-10-05 19:40 UTC by pmadria3

This PR adds a guard for if the patientID doesn't exist in Zus. 

![Screen Shot 2022-10-06 at 8 58 11 AM](https://user-images.githubusercontent.com/98342697/194332465-cee447e2-40c7-4e19-b745-046001bb24d0.png)

2022-10-05 19:45 UTC, luthfib commented on src/components/core/alert.tsx
> +);
I imagine we are going to be using this AlertDialog in other components so it should be generic and take in the message it should

2022-10-05 19:45 UTC, luthfib commented on .changeset/silent-squids-divide.md
> +Don't fetch when not on patient provider. Also fixes overfetching
Fix changeset, this is not the correct description

2022-10-05 19:49 UTC, luthfib commented
Nit: branch names should be projectPrefix-ProjectNumber/description-of-project

2022-10-05 19:55 UTC, luthfib requested changes
Looking good, but some changes needed. Need padding around the alert dialog. Refer to figma and compare it yours.

2022-10-05 19:55 UTC, luthfib commented on src/components/core/alert.tsx
> +);
Alert Icon and the title need to be aligned. Also the paragraph should not appear right below the alert icon but to the side. Please refer to figma

2022-10-05 19:57 UTC, luthfib reviewed
I believe we dont need to add a new icon but can exclamation-triangle from heroicons.

2022-10-05 19:58 UTC, luthfib commented on src/components/content/conditions.tsx
> +      {patientResponse.error && <AlertDialog />}
Need a fragment around this to get rid of the error

2022-10-05 20:07 UTC, luthfib commented on src/components/content/conditions.tsx
> +      {patientResponse.error && <AlertDialog />}
you can do patientResponse.isError for more succint error handling

2022-10-05 20:24 UTC, luthfib commented on src/components/content/conditions.tsx
> +              resourceType="Condition"
Doesnt this need to be plural?

2022-10-05 20:25 UTC, pmadria3 commented
Going with the design team icon after discussion

2022-10-05 20:28 UTC, luthfib requested changes
These still do not match. Look at the aligement with the icon. Align center should the the tricky if the icon and the title are in the same flex div. Also the content shouldnt be below the alert icon

<img width="988" alt="image" src="https://user-images.githubusercontent.com/16874444/194156938-30703d2b-e22a-4bb7-a89f-5af7ea494859.png">


<img width="962" alt="image" src="https://user-images.githubusercontent.com/16874444/194157017-1e673152-1c5c-4fd2-be1a-38f449929a04.png">

2022-10-05 20:37 UTC, luthfib commented on src/styles/tailwind.theme.ts
> +      burgundy: "#92400E",
Still checking if we want to add new colors, if we do I think we could change these to be:

```
burgundy/text
lightred/body
yellow/default
```

The current names dont have too much of a semantic meaning

2022-10-05 21:30 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +        {!patientResponse.isError && (
Might be easier to have do:

```ts
if (patientResponse.isError) {
  return (<...>)
}

return ( ...) // The existing stuff.
```

2022-10-06 14:09 UTC, WesleyKapow commented on src/components/core/alert.tsx
> +      <div className="ctw-flex ctw-text-caution-heading">
flex is usually not needed when there's only one child.. flex box is about how elements line up in a row or column, one child = nothing to do.

2022-10-06 14:11 UTC, WesleyKapow commented on src/components/core/alert.tsx
> +export const AlertDialog = ({ resourceType, children }: AlertDialogProps) => (
You've made this alert component specific to resource unavailable errors. We may want to show it for other things too.

2022-10-06 15:04 UTC, WesleyKapow commented on .changeset/silent-squids-divide.md
> +Adds an error display to the conditions table if there is no patientID corresponding in Zus Health.
Maybe change to `... conditions table if patient could not be found".

2022-10-06 16:02 UTC, WesleyKapow approved these changes

2022-10-06 16:08 UTC, merged