Ctw 328/add practitioner fetch
zeus-health/ctw-component-library pull request #110
Opened 2022-10-06 20:14 UTC by luthfib

Add display when saving the recorder field for condition.

2022-10-06 22:31 UTC, pmadria3 commented on src/fhir/practitioner.ts
> +    throw new Error(`Failed fetching practitioner: ${e}`);
For this error maybe we can also include the practitionerID as well

2022-10-07 14:01 UTC, WesleyKapow requested changes
Minor comments, LGTM

2022-10-07 14:01 UTC, WesleyKapow commented on src/fhir/practitioner.ts
> +export const getPractitioner = async (
Change to return only one and error if 0 found.

2022-10-07 17:26 UTC, pmadria3 approved these changes
LGTM

2022-10-07 17:30 UTC, WesleyKapow requested changes

2022-10-07 17:30 UTC, WesleyKapow commented on src/fhir/practitioner.ts
> +    }
I've hit this tricky problem before. This `throw` will get caught in the below `catch`.

2022-10-07 17:40 UTC, luthfib commented on src/fhir/practitioner.ts
> +    }
You are right, good catch.

2022-10-07 18:41 UTC, WesleyKapow submitted a review, later dismissed
LGTM, may want to push the use of `new PractitionerModel` into the helper as well. I think it makes sense for our fhir helpers to just return the models since that's mostly what we want to be working with.

2022-10-07 18:48 UTC, WesleyKapow commented on src/components/content/forms/conditions.ts
>    const display = practitionerModel.fullName;
can simplify to just calling it a `practitioner` and not model.

2022-10-07 18:50 UTC, WesleyKapow approved these changes

2022-10-07 18:51 UTC, merged