CTW-382/conditions-quick-view
zeus-health/ctw-component-library pull request #118
Opened 2022-10-17 20:38 UTC by pmadria3

This PR helps to simplify the view for the conditions table when it is viewed at 320 pixels.
![Screen Shot 2022-10-17 at 3 38 27 PM](https://user-images.githubusercontent.com/98342697/196278544-80d24ffb-7830-4f83-a403-8bae877052b3.png)

2022-10-17 20:39 UTC, pmadria3 commented on src/styles/tailwind.theme.ts
> +  esm: 320,
wasn't sure what to call this esm stands for extra small but am open to renaming this

2022-10-17 20:48 UTC, luthfib requested changes
<img width="246" alt="image" src="https://user-images.githubusercontent.com/16874444/196280129-94ef3646-3eb8-4f23-b5a3-bef2a486d15f.png">

Patient Record should be above the inactive filter as show in the desired behavior for the quick view

2022-10-17 20:53 UTC, pmadria3 commented
For the pill, design team said to not have that and forgot to remove it from the design (put it in the out-of-scope as well)

2022-10-17 20:53 UTC, luthfib commented
Additionally I don't see a prop to turn quick profile on and off, meaning that we have by default set the quick profile view on, which I dont think is the desired behavior.

2022-10-18 14:13 UTC, WesleyKapow commented
This needs to get reworked. Quick view is not something that happens due to window/container size. It is instead something that is explicitly used by healthie via a new component or prop(s) on the existing component.

2022-10-18 15:47 UTC, melocule commented on src/App.tsx
> +          <Conditions quickProfile={false} />
Smth like this https://stackoverflow.com/questions/37828543/how-to-pass-props-without-value-to-component

2022-10-18 16:21 UTC, melocule requested changes

2022-10-18 16:21 UTC, melocule commented on src/components/content/conditions.tsx
> +  quickProfile?: boolean;
Hey looks great! Just one thing: Since you're setting `quickProfile = false` in the Conditions function, `quickProfile` doesn't have to be optional here

2022-10-18 16:22 UTC, WesleyKapow requested changes
Please update PR description with latest screenshot!

2022-10-18 16:22 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +                : "ctw-flex ctw-flex-col ctw-items-start ctw-space-y-2 ctw-p-3"
Maybe refactor to a `ctw-conditions-title-container-readonly` .. actually I'm not sure what the differences here are. What particularly is needed for this view here?

2022-10-18 16:23 UTC, melocule commented on src/styles/tailwind.theme.ts
> +  esm: 320,
How about `xs`? Tailwind uses this to refer to extra small in [their docs](https://tailwindcss.com/docs/screens)

2022-10-18 17:18 UTC, pmadria3 commented on src/components/content/conditions.tsx
> +  quickProfile?: boolean;
I do need the question mark otherwise will need to make it a param in App.tsx

2022-10-18 17:31 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +              !breakpoints.esm
Don 't use responsive breakpoints for this, instead use `flex-wrap` and setup whatever `space-y` is needed. This should probably get added to the existing `ctw-conditions-title-container` class.

The idea is that we aren't saying "these should stack when below 320px", what we really want to say is "these should stack when there isn't enough room" and normal CSS wrapping can handle that.

2022-10-18 17:35 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +              !breakpoints.esm
Oh actually spacing will be a little trickier and will likely need both a `column-gap` and a `row-gap` so that X and Y spacing is only applied when needed.

2022-10-18 17:37 UTC, WesleyKapow requested changes

2022-10-18 17:37 UTC, WesleyKapow commented on src/components/content/conditions-table-base.tsx
> +  hideMenu: boolean;
Make this optional and default to `false`.

2022-10-18 17:37 UTC, WesleyKapow commented on .changeset/perfect-countries-hear.md
> +Added an optional quick view functionality to provide a read only view for the conditions table.
Renamed quick view.. change to `readOnly` and `hideMenu`?

2022-10-18 18:03 UTC, WesleyKapow requested changes

2022-10-18 18:03 UTC, WesleyKapow commented on .changeset/perfect-countries-hear.md
> +Added an optional readyOnly functionality to provide a read only view for the conditions table. If this readOnly functionality is on, the meatball menu will be hidden.
Makes it sound like meatball menu being hidden is the only thing result.

2022-10-18 18:03 UTC, WesleyKapow commented on src/components/content/conditions.scss
> +    @apply ctw-m-3 ctw-mb-0 ctw-space-y-2;
You'll likely want column and row gaps on the `title-container itself, and not just when it is stacked.

2022-10-18 18:03 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> -
Sometimes blank newlines are nice to separate chunks of functionality. Did you feel strongly against them?

2022-10-18 18:03 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> -
Same here.

2022-10-18 19:53 UTC, WesleyKapow approved these changes

2022-10-18 19:55 UTC, merged