CTW-1404 Refactoring diagnostic report queries
zeus-health/ctw-component-library pull request #1252
Opened 2023-09-26 19:01 UTC by eric-gunther

2023-09-26 19:08 UTC, eric-gunther commented on src/fhir/diagnostic-report.ts
> +  useEffect(() => {
This `useEffect` is important! Without this we had been calling the diagnostic reports query twice - once on load and then again after the observations query finished.

2023-09-26 19:10 UTC, eric-gunther commented on src/fhir/observations.ts
> +      )
I'm assuming this FQS back-fill is done now.

2023-09-26 19:11 UTC, eric-gunther commented on src/services/fqs/client.ts
> +export const MAX_OBJECTS_PER_REQUEST = 500;
This is pretty unscientific. But we're currently retrieving up to 1000 resources per patient and we're doing it often. This seems like overkill (though some patients do have a ton of resources). Perhaps we can vary this more by resource type?

2023-09-26 19:12 UTC, eric-gunther commented on src/services/fqs/queries/diagnostic-reports-query.ts
> -          }
No idea why this was here but I could not come up with a use-case (or any reference in the code) to justify retrieving medication requests along with our diagnostic reports. And this was a very expensive thing to include in this query.

2023-09-26 19:12 UTC, eric-gunther commented on src/services/fqs/queries/diagnostic-reports-query.ts
> -          }
These observations are quite expensive to include as well, really only need them when rendering the table, don't need them for the red dots.

2023-09-27 13:40 UTC, bryanjknight requested changes

2023-09-27 13:40 UTC, bryanjknight commented on src/fhir/observations.ts
> +      )
It's sadly isn't :(

2023-09-27 14:20 UTC, eric-gunther commented on src/fhir/observations.ts
> +      )
Added back the hack

2023-09-27 14:21 UTC, eric-gunther commented on src/services/fqs/client.ts
> +export const MAX_OBJECTS_PER_REQUEST = 500;
100% agree that lens & pagination is the right long term solution. 500 still seems like a pretty reasonably large number while reducing the amount of memory we're using.

2023-09-27 14:22 UTC, eric-gunther commented on src/services/fqs/queries/diagnostic-reports-query.ts
> -          }
Still including all of this when you render the full table, it's just now conditional based on an `includeObservations` argument supplied when getting the query for diagnostic reports. This makes it so we don't request them when rendering the red dot.

2023-09-27 14:24 UTC, bryanjknight approved these changes

2023-09-27 14:25 UTC, pmadria3 approved these changes

2023-09-27 14:25 UTC, merged