CW-CQ encounters data
zeus-health/ctw-component-library pull request #1268
Opened 2023-10-02 21:07 UTC by pmadria3

CDEV-472 
CDEV-473

This PR sets up the Encounters and Notes Data section for the ADT table. It has an FQS query call for the encounter and then displays them in the drawer.

2023-10-03 20:55 UTC, pmadria3 reviewed
changeset

2023-10-03 20:55 UTC, pmadria3 commented on src/components/content/patients-adt/patients-adt-alerts-table.tsx
> +        console.log("binary id log", e.relatedEncounter.binaryId);
remove console log

2023-10-03 20:57 UTC, pmadria3 commented on src/services/fqs/queries/documents.ts
> +export const documentADTQuery = gql`
Where is this being used?

2023-10-04 17:15 UTC, WesleyKapow requested changes

2023-10-04 17:15 UTC, WesleyKapow commented on src/components/content/patients-adt/patients-adt-alerts-table.tsx
> +          )}
Are we managing pagination ourselves because we want pages and not the show all pagination that `ResourceTable` uses?

Maybe bump this out into a `const pagedData`?

2023-10-04 17:15 UTC, WesleyKapow commented on src/components/content/patients-adt/patients-adt-alerts-table.tsx
> +  }
What's all this doing? Maybe pull out into helper? And is this fetching data displayed in the drawer or things needed for the table?

2023-10-04 17:15 UTC, WesleyKapow commented on src/components/content/patients-adt/patients-adt-alerts-table.tsx
> +type AdtTemplate = Map<
What does `template` mean here?

2023-10-04 17:15 UTC, WesleyKapow commented on src/components/content/patients-adt/modal-hooks.tsx
> +        key={encounter.id}
`key` is only needed when within a loop.

2023-10-04 17:15 UTC, WesleyKapow commented on src/components/content/patients-adt/modal-hooks.tsx
> +  return (
Anyway to piggyback on existing components that handle show/hide of details. Seems like a lot of overlap here.

2023-10-04 18:49 UTC, melocule commented on src/components/content/patients-adt/patients-adt-alerts-table.tsx
> +type AdtTemplate = Map<
Renamed it, this types the JSON data we get from an S3 bucket that we populated with the ID's of ADT encounters and their corresponding Commonwell/Carequality encounters (and those encounters' binaries which we want to display)

2023-10-04 19:21 UTC, melocule commented on src/components/content/patients-adt/patients-adt-alerts-table.tsx
> +  }
CTW passes down the RelatedEncountersMap type (which ties the ID of a given ADT encounter to the ID's of the corresponding commonwell/carequality encounter and the binary we want to display) as "encounterAndNotesData" so that this code can fetch the actual encounter and binary resource

2023-10-04 19:22 UTC, melocule commented on src/components/content/patients-adt/patients-adt-alerts-table.tsx
> +  }
Which has the info we want to display in the drawer

2023-10-04 19:30 UTC, melocule commented on src/components/content/patients-adt/patients-adt-alerts-table.tsx
> +          )}
Yep! And sure

2023-10-04 19:33 UTC, melocule commented on src/components/content/resource/helpers/notes-entry.tsx
> +  collapsedRender?: ReactNode;
Thanks! This makes sense to me

2023-10-04 19:59 UTC, WesleyKapow commented on src/components/content/patients-adt/patients-adt-alerts-table.tsx
> +  }
Right ok, so that info is used in the drawer. Do I understand this correctly that we are prefetching that data for all ADT encounters in the table? Can we instead lazily load it when the drawer is opened?

2023-10-04 21:11 UTC, melocule commented on src/components/content/patients-adt/modal-hooks.tsx
> +  return (
Got it! Thank you

2023-10-05 14:40 UTC, melocule commented on src/services/fqs/queries/encounters.ts
> +export const encounterADTQuery = gql`
Merged them

2023-10-05 14:42 UTC, melocule commented on src/components/content/resource/helpers/notes-entry.tsx
> +export const NotesEntrySimple = ({
fixed

2023-10-05 15:28 UTC, WesleyKapow requested changes
Really great work, just one potential blocker that needs checking.

2023-10-05 15:28 UTC, WesleyKapow commented on src/components/content/patients-adt/patients-adt-alerts-table.tsx
> -          encounterADTQuery,
`encounterADTQuery` is no longer used now right? You can delete it?

2023-10-05 15:28 UTC, WesleyKapow commented on src/components/content/patients-adt/patients-adt-alerts-table.tsx
> +      const { data: encounterFqsData } = await fqsRequest<EncounterGraphqlResponse>(
Not sure if `fqsRequest` and our `graphClient` here are working with react query. The nice thing about running requests through react query is that we get caching. See if switching pages and then switching back causes you to re-fetch the same data you already fetched. If so, See if you can wrap this in a `queryClient.fetchQuery(...` like we use in `usePatientPromise` in `patient-provider.tsx` (note, the first arg to `fetchQuery` is the dependency array that uniquely identifies the query).

2023-10-05 16:00 UTC, WesleyKapow approved these changes
LGTM

2023-10-05 16:16 UTC, merged