CTW-1480 hospitalizations row actions
zeus-health/ctw-component-library pull request #1316
Opened 2023-10-12 22:12 UTC by melocule

CTW-1480
Add hospitalization table row actions
https://github.com/zeus-health/ctw-component-library/assets/33408946/a838c584-7393-4a6c-bdb4-71d58666ba62

Solution: Needed a new function to get the basics outside of PatientProvider. 

Additionally: Tweaks the styling on button in the drawer that sends you to the patient, based on designer feedback. [CTW-1476](https://zeushealth.atlassian.net/browse/CTW-1476)

TODO: 
- Fetches again once you switch to another page for some reason, need to figure out why
- No query keys, so it refetches upon refresh. May have to do useQuery[...] inside a loop and add a line to ignore the ESLint rule for that.

2023-10-13 16:26 UTC, WesleyKapow requested changes
Handful of comments, also I'm confused, where did the enabling of the row actions come in?

2023-10-13 16:26 UTC, WesleyKapow commented on src/hooks/use-filtered-sorted-data.ts
> +  isLoading?: boolean;
At first I thought this made sense but then I was curious why it worked before. It already has the `records` in the dependencies array for the `useEffect` so I'm surprised `isLoading` is needed here. What issue did you run into?

2023-10-13 16:26 UTC, WesleyKapow commented on src/components/content/patients-adt/patients-adt-alerts-table.tsx
> +      const requestContext = await getRequestContext();
Why pull this up? Not sure which is better but I suspect keeping it within the query function is good as `getRequestContext` will refresh auth token if needed. So good to always run that code when making a query.

2023-10-13 16:26 UTC, WesleyKapow commented on src/components/content/patients-adt/patients-adt-alerts-table.tsx
> +  const { data: encWithBasics, isLoading: isLoadingBasics } = useBasicsOf(
nit: better to not create abbreviations like `enc` and instead go with more verbose `encountersWithBasics`. This reduces cognitive load (no "what does enc mean?" thoughts)

2023-10-13 16:26 UTC, WesleyKapow commented on src/fhir/basic.ts
> +export function useBasicsOf<R extends fhir4.Resource, T extends FHIRModel<R>>(
nit: favor exported functions at top of file and helpers below. This is totally subjective but I find it easier to see the "interface" a file provides when the exports are at the top so I can quickly scan the available functions.

2023-10-13 16:26 UTC, WesleyKapow commented on src/fhir/basic.ts
> +    ["hospitalizations", key],
**BLOCKER:** This should not have `hospitalizations` in the key.

2023-10-13 16:26 UTC, WesleyKapow commented on src/components/content/patients-adt/patients-adt-alerts-table.tsx
> +    `Page ${currentPage}`
Maybe this should provide the key of `Hospitalizations page #`?

2023-10-13 16:26 UTC, WesleyKapow commented on src/fhir/basic.ts
> +  return useQueryWithCTW(
This may make more sense if you use this to wrap the part that's doing the fetching, so move it to `fetchBasicsFor`.. then the key would be `QUERY_KEY_BASIC, [resource.id]`.

Also, now looking at it, two thoughts:
1. You are doing N queries (one for each resource instead of a single query that grabs all basic resources).
2. Check with FQS & team here, we want to use FQS **and not ODS/smile**

2023-10-20 14:51 UTC, melocule commented on src/hooks/use-filtered-sorted-data.ts
> +  isLoading?: boolean;
other tables get the main resources with the basics together, but the hospitalizations component is given the main resources by CTW and then I have it assign the basics to a property of those resources. Since `records` is mutated and not replaced, it doesn't re-filter or re-sort with the basics. I added `isLoading` here as a workaround

2023-10-20 15:00 UTC, melocule commented on src/fhir/basic.ts
> +  return useQueryWithCTW(
1. Alternative would be doing 1 query for all the basics of all the encounters, and then iterating through the result to map the basics to which encounter they belong to. I thought this would make unnecessary work but is it preferred over making multiple queries?
2. (waiting for backfill)

2023-10-20 19:19 UTC, melocule commented on src/components/content/patients-adt/patients-adt-alerts-table.tsx
> +    `Page ${currentPage}`
Update: caching wouldn't be very helpful and wasn't working, went back to using just an async function

2023-10-23 18:39 UTC, WesleyKapow submitted a review, later dismissed

2023-10-23 19:44 UTC, WesleyKapow approved these changes

2023-10-23 20:23 UTC, merged