CTW-1497/Support feature flag ctw-patient-history-form
zeus-health/ctw-component-library pull request #1343
Opened 2023-10-25 20:08 UTC by mrosata

Support feature flag ctw-patient-history-form. This will hide the request records button if this flag is disabled. It is enabled for everyone currently.

2023-10-25 20:24 UTC, eric-gunther requested changes

2023-10-25 20:24 UTC, eric-gunther commented on src/components/content/patient-history/patient-history-action.tsx
> +  const hideRequestRecordsFormToggle = !useFeatureToggle("ctw-patient-history-form").enabled;
This seems like it hides the request records form when the toggle is enabled, not when it's disabled like the changeset and description suggest.

Think it's very confusing to use a feature flag to hide something, making me further second guess using a feature flag for this. May be a bit clearer if the name of the feature flag is something like `ctw-hide-request-records`.

2023-10-25 20:32 UTC, mrosata commented on src/components/content/patient-history/patient-history-action.tsx
> +  const hideRequestRecordsFormToggle = !useFeatureToggle("ctw-patient-history-form").enabled;
The feature flag shows it, the variable hides it, the `!` negates the feature toggle.

2023-10-25 20:36 UTC, eric-gunther commented on src/components/content/patient-history/patient-history-action.tsx
> +  const hideRequestRecordsFormToggle = !useFeatureToggle("ctw-patient-history-form").enabled;
Facepalm, I missed the `!` before `useFeatureToggle`.

2023-10-25 21:12 UTC, mrosata commented
> @mrosata in the interest of following with soon incoming PR guidelines, can you put in the description how you tested this and how you will confirm it works after deploying to prod?


@eric-gunther added this to description "Tested this running locally by toggling the ctw-patient-history-form feature flag in unleash to be disabled for that builder."

2023-10-26 12:42 UTC, eric-gunther approved these changes
Confirmed that the feature flag is on for all users in production.

Please also update any spots in standalone app where this feature flag will be applicable.

2023-10-26 13:26 UTC, mrosata commented
> Confirmed that the feature flag is on for all users in production.
> 
> Please also update any spots in standalone app where this feature flag will be applicable.

@eric-gunther The [PR for that](https://github.com/zeus-health/ctw/pull/903) is already in draft, wanted to merge them in together so the ctw-cl upgrade and ctw changes could go in at the same time.

2023-10-26 13:29 UTC, merged