CTW-381 Autofill Values for Confirming a Condition
zeus-health/ctw-component-library pull request #141
Opened 2022-10-20 18:14 UTC by melocule

Sets verification status to active by default when user adds a condition from another provider, not just when the user adds a new condition. 
Adds a helper function to set any common default values between adding a new condition or confirming one.

https://user-images.githubusercontent.com/33408946/197026210-1667abd3-4097-458f-8425-85b15a59be78.mov

2022-10-20 18:28 UTC, luthfib commented
I think your branch has some funky stuff going on I dont think you changed 26 files

2022-10-20 18:31 UTC, pmadria3 commented
Something weird happened with the merge (did you rebase instead of merge potentially?)

2022-10-21 00:52 UTC, luthfib reviewed
Looking good, some minor nitpicks

2022-10-21 00:52 UTC, luthfib commented on src/components/content/conditions.tsx
> +  const handleConfirmCondition = (condition: ConditionModel) => {
Little confused by this rename? Not too sure `handleConfirmCondition` is descriptive of whats going on

2022-10-21 00:52 UTC, luthfib commented on src/components/content/forms/condition-helpers.ts
> +// Sets any autofill values that apply when a user adds a medication, whether creating or confirming.
You say medication here, I think you mean condition

2022-10-21 13:57 UTC, WesleyKapow requested changes

2022-10-21 13:57 UTC, WesleyKapow commented on src/fhir/conditions.ts
> +  newCondition = applyAddConditionDefaults(newCondition);
NOTE: `applyAddConditionDefaults` modifies `newCondition` argument, so this assignment is not needed.

2022-10-21 13:57 UTC, WesleyKapow commented on src/components/content/forms/condition-helpers.ts
> +  return Object.assign(condition, addDefaults);
No need to return as you are modifying the passed in condition via this `assign`

2022-10-24 15:19 UTC, WesleyKapow submitted a review, later dismissed

2022-10-24 18:20 UTC, WesleyKapow submitted a review, later dismissed

2022-10-24 18:20 UTC, WesleyKapow commented on src/components/content/forms/conditions-autocomplete.tsx
> +export function setAddConditionDefaults(condition: Condition): void {
This has nothing to do with autcomplete, move somewhere else. Maybe fhir/conditions?

2022-10-24 19:29 UTC, melocule commented on src/components/content/forms/conditions-autocomplete.tsx
> +export function setAddConditionDefaults(condition: Condition): void {
Moved to the file with condition helpers for forms

2022-10-24 19:52 UTC, WesleyKapow approved these changes
Approving but in general our `fhir/` code should not depend on our form code. Should always be the other way around as the `fhir/` code is more "basic" or a "lower level".

2022-10-24 19:55 UTC, merged