[CTW-428] Meds components from CTW to Library
zeus-health/ctw-component-library pull request #143
Opened 2022-10-20 19:33 UTC by mrosata

Still left to do in this would be at least:
 - refactoring the todos in the file `src/components/content/medication-history.tsx`
 - utilizing the pagination in meds table using params passed down from above the `<PatientMedications />` component as the query params were removed and converted to props on `PatientMedications`, just nothing is using them
 - we probably want to separate out the "Add new meds" action from the component to have it passed in as a child or prop since not all builders will want that feature, and some might want the button to actually do something different (like canvas does)
 
<img width="716" alt="Screen Shot 2022-10-24 at 4 09 33 PM" src="https://user-images.githubusercontent.com/6380075/197619197-c0626687-a73c-47a7-98c9-c79d5ff59a6c.png">

<img width="729" alt="Screen Shot 2022-10-24 at 4 10 14 PM" src="https://user-images.githubusercontent.com/6380075/197619336-4e1dad0c-c082-46c9-af1f-aa60315b82b8.png">

<img width="464" alt="Screen Shot 2022-10-24 at 4 10 35 PM" src="https://user-images.githubusercontent.com/6380075/197619387-e0263375-db55-427e-8294-faa65ecc79fc.png">

<img width="941" alt="Screen Shot 2022-10-24 at 4 10 57 PM" src="https://user-images.githubusercontent.com/6380075/197619446-675d7e31-05a5-49d7-893e-bb58716d23e8.png">

2022-10-21 19:50 UTC, WesleyKapow requested changes
Lot of nits nothing too major outside of needing `ctw-` prefix on tailwind classes!

2022-10-21 19:50 UTC, WesleyKapow commented on src/SecuredApp.tsx
> +// eslint-disable-next-line import/no-extraneous-dependencies
???

2022-10-21 19:50 UTC, WesleyKapow commented on src/components/content/forms/medications.ts
> +  queryClient.invalidateQueries(["patient-medications"]);
FYI. We'll be switching these keys to be constants declared in a single utils file.

2022-10-21 19:50 UTC, WesleyKapow commented on src/components/content/medication-drawer.tsx
> +// noinspection JSXNamespaceValidation
???

2022-10-21 19:50 UTC, WesleyKapow commented on src/components/content/medication-drawer.tsx
> +        // { label: "Reason", value: medication.reason },
???

2022-10-21 19:50 UTC, WesleyKapow commented on src/components/content/medication-drawer.tsx
> +  function renderDrawerContentTop() {
Inline this as it isn't that big.

2022-10-21 19:50 UTC, WesleyKapow commented on src/components/content/medications-table-base.tsx
> +    <div className={`ctw-table ${className}`.trim()}>
`trim()` needed? Favor using `cx` helper for concating classes

2022-10-21 19:50 UTC, WesleyKapow commented on src/components/content/medication-history.tsx
> +  }
Bump below `if (loading)`

2022-10-21 19:51 UTC, WesleyKapow reviewed
Yay prefixes! I assume that made a difference!?

**ALSO -- Please add screenshots to the PR description!**

2022-10-21 20:21 UTC, mrosata commented on package.json
> +    "jsdom": "^20.0.1",
I think that `jsdom` is required for tests. It's in the vitest config
```
    environment: "jsdom",
```
I didn't see any complaints about jsdom from `npm` until after running tests or a build post-downgrade from react-18 to react-16 so my thought was that the version of the testing library might require it explicitly installed for some reason now as before it wasn't actually being required by us.

Similar story on `glob`, before we only had `@types/glob` in package.json. I actually thought I removed glob though instead of added it so I can try to remove it again and see what happens

2022-10-21 20:30 UTC, mrosata commented on src/components/content/columns/active-column.tsx
> +export const ActiveColumn = ({ status }: { status: string }) => {
It's was written afaik for just the meds columns to show colors on lens status or column statuses. https://github.com/zeus-health/ctw/blob/1e85fb8cb1d4f2904674efbf051c9e7e79d71d30/app/components/content/columns/active-column.tsx#L3

It actually only renders differently iirc in CTW and not in just the components library.

2022-10-21 20:37 UTC, mrosata commented on src/components/content/conditions.scss
>  .ctw-conditions {
yeah that was actually my thought as well, I had a version yesterday that was very minimal. Adding it back now
```
.ctw-conditions {
  @apply ctw-border ctw-border-solid ctw-border-divider-light ctw-bg-white;
}

.ctw-conditions.ctw-stacked {
  .ctw-conditions-not-reviewed {
    @apply ctw-table-x;
  }

  .ctw-conditions-not-reviewed {
    @apply ctw-border-b-0;
  }
}

```

2022-10-21 20:38 UTC, mrosata commented on .env.example
> +# VITE_AUTH0_AUDIENCE=
this was the bit that I only got correct using the forms-ui clientId and audience. I'd rather not but the forms client id in here. Monday I'll try to get the ctw ones working

2022-10-21 20:43 UTC, mrosata commented on src/components/content/conditions.tsx
> +            className="ctw-table"
I agree with the class name living on the table. I don't think they need to use the specific naming though because then people may lean towards much more custom styles and way more custom classes. Iirc the conditions component has a custom class like `.ctw-component` which can be used to override minimal set of styles on `.ctw-table`

Will move that class into the table now

2022-10-21 20:49 UTC, mrosata commented on src/components/content/conditions.tsx
> -    async function load() {
yeah it just wasn't needed to be wrapped in an async function b/c there weren't any `await` being used in there iirc. I'll revert it

2022-10-21 20:52 UTC, mrosata commented on src/components/core/table/table-rows.tsx
> +        >
Was discussing this earlier with Tai Eric and Adrianna as well. Atm there is no UX informing the users that they can click a row. Is there a class that I should use?

2022-10-21 20:59 UTC, mrosata commented on src/hooks/use-search-params.ts
> +export function useSearchParams(): [URLSearchParams, () => void] {
Actually this probably is no longer needed, wrote it more as a hack to make get things working and maintain type parity... but nothing should be using it anymore so I'll delete it

2022-10-21 21:01 UTC, mrosata commented on src/main.tsx
> +  document.getElementById("root") as HTMLElement
It's just an API break between React 16 and 17

2022-10-21 23:15 UTC, WesleyKapow commented on package.json
> +    "jsdom": "^20.0.1",
Ah ok sgtm.

2022-10-21 23:17 UTC, WesleyKapow commented on src/components/content/columns/active-column.tsx
> +export const ActiveColumn = ({ status }: { status: string }) => {
Ah ok, if it's medication specific then it should go with medication code and not be named generic like `ActiveColumn`.

2022-10-21 23:21 UTC, WesleyKapow commented on src/components/core/table/table-rows.tsx
> +        >
Yes, this is what CTW App does -- https://github.com/zeus-health/ctw/blob/main/app/components/core/table.tsx#L231

In general I'm not really a fan of row clicks as they:
1. Are not always obvious, particularly with what the action will do.
2. Prevent adding more options or links within the row.

All that said, please check with Tai if you can switch over to the "..." menu which would be consistent with conditions table.

2022-10-21 23:24 UTC, WesleyKapow commented on src/main.tsx
> +  document.getElementById("root") as HTMLElement
Ah ok sg. Another reminder to try and split work into multiple PRs. Downgrading to react 16 could have been on its own. Personally, I find this a constant battle to try and remind myself. Sometimes I am good and set out with work broken into PRs, other times I only find it after diving in and in those cases I sometimes opt to pull out stuff into separate PRs.

2022-10-21 23:27 UTC, WesleyKapow requested changes

2022-10-21 23:27 UTC, WesleyKapow commented on src/components/content/conditions.scss
> +    @apply ctw-table;
BTW `ctw-table` may collide with tailwind display classes -- https://tailwindcss.com/docs/display (so tailwind has a `ctw-table` already).

2022-10-21 23:27 UTC, WesleyKapow commented on src/components/content/medications-table-base.tsx
>      <div className={`ctw-table ${className}`.trim()}>
Little weird that this also has `ctw-table`, I'd expect that to be specific to the table core component.

2022-10-24 14:22 UTC, mrosata commented on src/models/patients.ts
> +import { differenceInYears, parseISO } from "date-fns";
@WesleyKapow - perhaps someone can walk me through the pattern used. I did see a `save` method in some models which felt out of place for a model _(personally not a fan of live records)_, I'd be interested to know the benefit of not having setters in the model though and going for direct modification of fhir resources over that abstraction. If there is someone in particular that is good to ask those questions of please let me know.

2022-10-24 14:27 UTC, mrosata commented on src/models/patients.ts
> +import { differenceInYears, parseISO } from "date-fns";
just cleaned out everything unused in this model

2022-10-24 14:28 UTC, mrosata commented on src/components/core/error-boundary.tsx
> +        <>
nice, will do, I actually prefer one or the other as well

2022-10-24 15:06 UTC, mrosata commented on src/components/core/error-boundary.tsx
> +export class ErrorBoundary extends Component<Props, State> {
correct, I moved it next to App.tsx and added a short message above it. It could also live nicely in utils folder`./src/utls/error-boundary.tsx` if we didn't want to bloat the root src dir, up to you though

2022-10-24 15:38 UTC, mrosata commented on src/components/content/patient-medications.tsx
> +};
I can rip the pagination out, I don't think it's needed. ATM it isn't actually there anyways, I was going to leave some of the logic in place (minus the url params) so whoever adds it in has less work, but honestly the pagination likely won't be implemented in a way that resembles these artifacts so I'll remove it all (including any array slicing and placeholder values in the meds react component).

2022-10-24 15:52 UTC, WesleyKapow commented on src/components/content/patient-medications.tsx
> +};
YAGNI my friend!

2022-10-24 16:34 UTC, mrosata commented on src/models/conditions.ts
> -  private includedResources?: ResourceMap;
I'm not reading it, the model is reading it internally but not modifying it. I'll change it back to private.

2022-10-24 17:10 UTC, mrosata commented on src/components/content/medication-drawer.tsx
> +        // { label: "Reason", value: medication.reason },
Part of the Canvas UI discussion Eric, Adrianna, Tai and I had last week was to remove these because it was too much information (or too many labels with no information). The commenting out happened in real-time during a zoom meeting where we group iterated.

I was thinking that even though Canvas won't use them, we might not want to lose them completely. One thought I had was to only show items that have a value but apparently historically that hasn't been desirable by all users. So maybe we let the component take an optional list of fields to display and filter by that list. Then a default list could either be everything or this trimmed down version. What do you suggest @WesleyKapow?

2022-10-24 17:12 UTC, mrosata commented on src/components/content/medication-drawer.tsx
> +  function renderDrawerContentTop() {
I tried but it just gets reformatted by prettier (`npm run format`)

2022-10-24 17:19 UTC, WesleyKapow commented on src/components/content/medication-drawer.tsx
> +        // { label: "Reason", value: medication.reason },
YAGNI -- For now show only what is needed and remove any dead/commented out code.

Conditions is in the same boat that someday we may add a prop to allow specifying which columns to display or which fields to display in history.

2022-10-24 17:20 UTC, WesleyKapow commented on src/components/content/medication-drawer.tsx
> +  function renderDrawerContentTop() {
What do you mean?

My suggestion is to remove the `renderDrawerContentTop` method and instead inline the JSX as appose to pulling it out into this helper function.

2022-10-24 17:22 UTC, mrosata commented on src/components/content/medications-table-base.tsx
>      <div className={`ctw-table ${className}`.trim()}>
yeah good point it should just be
```suggestion
  return (
    <div className={className}>
```

2022-10-24 20:06 UTC, mrosata commented on .env.example
> +# VITE_AUTH0_AUDIENCE=
This should be resolved now

2022-10-25 16:22 UTC, mrosata commented on src/components/content/patient-medications.tsx
> +};
removed these yesterday

2022-10-25 19:12 UTC, eric-gunther approved these changes

2022-10-25 19:12 UTC, merged