Hex to RGBA converter
zeus-health/ctw-component-library pull request #144
Opened 2022-10-21 16:11 UTC by pmadria3

CTW-379

This PR adds a hex to rgba converter that allows to convert the values and also declare opacity. The black is now replaced with CTW theme.

Before:
![image](https://user-images.githubusercontent.com/98342697/197240644-30e7fc86-3dde-42b7-95ed-c458f366305b.png)

After: 
![image](https://user-images.githubusercontent.com/98342697/197240695-34e9d9e9-c4cd-4815-90f3-b569280bf875.png)

Note: will need to wait till autocomplete conditions is merged to merge this PR.

2022-10-21 20:10 UTC, luthfib reviewed
Looking good, just a couple of changes

2022-10-21 20:10 UTC, luthfib commented on src/styles/tailwind.theme.ts
> +}
I think we can just return `rgb(${r}, ${g}, ${b})`. Since this is happening in the converter and users are going to specify hex I dont see us needing to allow option to specify rgba. Also would be kind nice if we supported rgba values, so if a user specifies rgba we just return rgba instead of converting.

2022-10-24 07:28 UTC, WiktorKania approved these changes
Looks good, left one suggestion.
Keep in mind that this converter won't work for shorthand values like `#FFF`.
Also, it doesn't allow you to specify the alpha channel so technically you can't declare opacity. If we want to declare opacity then hex values will do just fine too, you can add another octet at the end which will specify the opcity.
Approving this since I don't really know the requirements

2022-10-24 07:28 UTC, WiktorKania commented on src/styles/tailwind.theme.ts
> +  return colorMapping;
```suggestion
  if (colorMapping[0] !== "#") return colorMapping;
  const r = parseInt(colorMapping.slice(1, 3), 16);
  const g = parseInt(colorMapping.slice(3, 5), 16);
  const b = parseInt(colorMapping.slice(5, 7), 16);
  return `rgb(${r}, ${g}, ${b})`;
```

2022-10-24 13:44 UTC, WesleyKapow commented on src/styles/tailwind.theme.ts
> +  return colorMapping;
and yet another option: `colorMapping.startsWith('#')`

2022-10-24 13:51 UTC, WesleyKapow requested changes

2022-10-24 13:51 UTC, WesleyKapow commented on src/components/content/forms/drawer-form-with-fields.tsx
> +                  <label>{label}</label>
Why the change to styles here? I think we want to keep the classes as they were.

2022-10-24 13:59 UTC, pmadria3 commented on src/styles/tailwind.theme.ts
> +  return colorMapping;
Yeah I agree - originally I had opacity but removed it but added it back and made it optional.

2022-10-24 14:00 UTC, pmadria3 commented on src/components/content/forms/drawer-form-with-fields.tsx
> +                  <label>{label}</label>
Design team updated some of the error handling and thus the change was small I just implemented it in this PR. The third screenshot captures the change.

2022-10-24 14:04 UTC, WesleyKapow commented on src/components/content/forms/drawer-form-with-fields.tsx
> +                  <label>{label}</label>
Is there a ticket for that? Can you link me to slack discussion or figma for this?

2022-10-24 14:16 UTC, pmadria3 commented on src/components/content/forms/drawer-form-with-fields.tsx
> +                  <label>{label}</label>
Removed this per discussion

2022-10-24 14:18 UTC, WesleyKapow approved these changes

2022-10-24 14:40 UTC, merged