Ctw 357/choose best code
zeus-health/ctw-component-library pull request #150
Opened 2022-10-24 19:19 UTC by luthfib

- Adds preferred coding function to get the coding best on our definition of best coding, favoring enrichment. 
- Adds default value for add new provider and edit condition. 
- Fixes issue where when adding condition the error message wasnt 100% clear. 
- Remove uneeded code

2022-10-24 19:22 UTC, luthfib commented
My bad on the package.lock.json

2022-10-24 19:33 UTC, WesleyKapow requested changes

2022-10-24 19:33 UTC, WesleyKapow commented on src/fhir/conditions.ts
> +export const BEST_CODE_PREFERENCE_ORDER = [
This is specific to conditions.

How about `CONDITION_CODE_PREFERENCE_ORDER`?

2022-10-24 19:33 UTC, WesleyKapow commented on src/fhir/codeable-concept.ts
> +export const findCodingByOrderOfPreference = (
Maybe this should take the preferences so it isn't specific to conditions.

2022-10-24 19:33 UTC, WesleyKapow commented on src/fhir/codeable-concept.ts
> +  let codeSystem;
1. Don't need this, instead of `break` you can `return`.
2. `codeSystem` should be `coding`.

2022-10-24 19:33 UTC, WesleyKapow commented on src/fhir/codeable-concept.ts
> +    }
You need an else here, otherwise it will check for snomed with enrichment and then snomed without where ticket has all enrichment systems first.

You'll also need to add snomed and icd10 without enrichment in the right order to `BEST_CODE_PREFERENCE_ORDER`

2022-10-24 19:33 UTC, WesleyKapow commented on src/components/content/forms/condition-schema.tsx
> +        defaultCoding={condition.codings}
`codings`? Is this more than one? Seems weird for the autcomplete component. We want edit to display the preferred but not modify ANY of the `codings` right?

2022-10-24 19:33 UTC, WesleyKapow commented on src/models/conditions.ts
> +  get preferredSystem(): string | undefined {
This used?

2022-10-24 19:48 UTC, luthfib commented on src/fhir/codeable-concept.ts
> +    }
Yup, good catch on the else. I dont think we need to add snomed and icd10 without the enrichment to the array. Because if we dont find it in the enrichment find then we can just do a find in that same loop

2022-10-24 19:54 UTC, WesleyKapow commented on src/fhir/codeable-concept.ts
> +    }
Check again, I think you will need snomed without enrichment.

It should go:
1. Snomed with enrichment
2. ICD10 with enerichment
3. Snomed without enrichment
4. ICD10 without enrichment
5. ICD10_CM without
6. ...

So whatever gives us that!

2022-10-24 20:19 UTC, luthfib commented on src/components/content/forms/condition-schema.tsx
> +        defaultCoding={condition.codings}
We do this because we want to keep all of the codings when editing

2022-10-24 20:38 UTC, pmadria3 commented on src/fhir/conditions.ts
> +
remove extra space

2022-10-24 20:40 UTC, pmadria3 approved these changes
LGTM

2022-10-25 01:45 UTC, WesleyKapow approved these changes

2022-10-25 02:25 UTC, merged