Ctw-361/edit field requirements
zeus-health/ctw-component-library pull request #162
Opened 2022-10-26 18:58 UTC by pmadria3

This PR updates the field requirements and read only content for the Edit/Add Condition forms.

Edit Conditions: 
![Screen Shot 2022-10-26 at 1 56 09 PM](https://user-images.githubusercontent.com/98342697/198112570-34bfd04c-de17-4eb6-85af-790b6235a66e.png)

Add Conditions: 
![Screen Shot 2022-10-26 at 1 58 22 PM](https://user-images.githubusercontent.com/98342697/198113039-35ea6921-69b2-4171-a5f3-6c1705eb19e7.png)

2022-10-26 20:49 UTC, WesleyKapow requested changes

2022-10-26 20:49 UTC, WesleyKapow commented on src/components/content/forms/drawer-form-with-fields.tsx
> +  formType?: FormActionTypes;
Why do I need formType here?

2022-10-26 20:49 UTC, WesleyKapow commented on src/components/content/forms/drawer-form-with-fields.tsx
> +          {formType === "Edit" && <div>{header}</div>}
See if just doing this will work for when it is defined and when it is not defined: `{header}`

2022-10-26 20:49 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +              <div>
Combine these two divs

2022-10-26 20:49 UTC, WesleyKapow commented on src/components/content/conditions.tsx
>      }
Do we need both of these states? Can we instead have a `selectedCondition` state?

2022-10-26 20:49 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +          header={
Is this the same content as used by the condition history? May want to DRY it up into a `condition-header` component.

2022-10-26 20:49 UTC, WesleyKapow commented on src/components/content/forms/condition-schema.tsx
> -  {
Will editing a condition lose the codings now that we aren't setting up this field?

2022-10-26 20:49 UTC, WesleyKapow commented on src/components/content/forms/drawer-form-with-fields.tsx
> +          <div className="ctw-space-y-6 ctw-py-4">
Why the `py-4`? Is that to create space between this and the header? It will add space above and below!

Favor using `space-y` classes on a parent div.

2022-10-26 22:02 UTC, pmadria3 commented on src/components/content/forms/drawer-form-with-fields.tsx
> +          {formType === "Edit" && <div>{header}</div>}
so for this and the `formType` comment - I do need this because I need to know which `formType` it is (`add` vs `edit`) otherwise if I remove this and just do `{header}`, the title shows up in the add Form drawer as well.

2022-10-27 02:24 UTC, pmadria3 commented on src/components/content/forms/drawer-form-with-fields.tsx
> +          {formType === "Edit" && <div>{header}</div>}
Taking a closer look, it seems to be that the previous action doesn't seem to reset and thus need to reset the state/clear cache after drawer closes

2022-10-27 15:06 UTC, WesleyKapow commented on src/components/content/forms/drawer-form-with-fields.tsx
> +          {formType === "Edit" && <div>{header}</div>}
Have the consumer of this only pass in `header` for edit.

2022-10-27 15:09 UTC, WesleyKapow requested changes

2022-10-27 15:09 UTC, WesleyKapow commented on src/components/content/conditions-history.tsx
> +      <>
Why removing the div and the space?

2022-10-27 16:03 UTC, WesleyKapow submitted a review, later dismissed
One minor nit but otherwise LGTM

2022-10-27 16:03 UTC, WesleyKapow commented on src/components/content/conditions-history.tsx
> +          <div>
Is this div needed?

2022-10-27 17:14 UTC, WesleyKapow requested changes

2022-10-27 17:14 UTC, WesleyKapow commented on src/components/content/forms/form-field.tsx
> -  if (render && hidden) {
Why removing this? I don't fully know this code but this seems unrelated to your work.

2022-10-27 17:52 UTC, WesleyKapow submitted a review, later dismissed
LGTM

2022-10-27 18:10 UTC, WesleyKapow approved these changes

2022-10-27 18:12 UTC, merged