CTW-374 ODS and Multi-Field Form Error Display
zeus-health/ctw-component-library pull request #168
Opened 2022-10-27 16:33 UTC by melocule

2022-11-01 19:29 UTC, WesleyKapow requested changes
Didn't review everything yet but wanted to stop here. See my note in condition schema about using `refine` or `superRefine` on the schema itself.

2022-11-01 19:29 UTC, WesleyKapow commented on src/components/content/conditions-history.tsx
> +          (c: Condition) => new ConditionModel(c, includedResources)
Was this needed? `historyResponse.data.conditions` should already be `fhir4.Condition` type so this shouldn't be needed.

We don't need to explicitly add types when TS already knows them. E.g. `['foo', 'bar'].map((item: string) => {}` does not need the `: string` typing as that is already a given due to what you are mapping over.

2022-11-01 19:29 UTC, WesleyKapow commented on src/fhir/conditions.ts
> +    const conditionModel: ConditionModel = new ConditionModel(c);
This is superfluous, it'd be like doing `const foo: string = "hello world"`. Only when we want to be careful that the right side is in fact the type we expect do we need to do this, like:
```ts
const data: LoaderData = {...}
```
Since `{...}` could be any object, only by adding in the explicit `: LoaderData` do we enforce its type/shape.

2022-11-01 19:29 UTC, WesleyKapow commented on src/fhir/action-helper.ts
> +      resourceType: "foo",
This don't look right O_o

2022-11-01 19:29 UTC, WesleyKapow commented on src/components/core/main.scss
>    }
See if you can get the style right without this. My thinking is that `8%` seems awfully specific. The icon should be positioned in a more general manner (like "be centered and 4px from the right")

2022-11-01 19:29 UTC, WesleyKapow commented on src/components/content/forms/form-field.tsx
> +  // styling of the error icon before: ctw-pointer-events-none ctw-absolute ctw-inset-y-0 ctw-right-0 ctw-top-2 ctw-flex ctw-h-min ctw-items-center ctw-pr-3
remove

2022-11-01 19:29 UTC, WesleyKapow commented on src/components/core/alert.tsx
> +    <XCircleIcon className="ctw-h-5 ctw-flex-none ctw-text-error-icon" />
I think we want exclamation here too. The X circle looks like something you can close.

2022-11-01 19:29 UTC, WesleyKapow commented on src/models/operation-outcome-issue.ts
> +  | "information";
`fhir4.OperationOutcomeIssue.severity` already has this. You can use  `fhir4.OperationOutcomeIssue['severity']`. We also don't currently force all functions to have explicit return types so TS will pick this up automatically in your `get severity()` function.

2022-11-01 19:29 UTC, WesleyKapow commented on src/components/content/forms/condition-schema.tsx
> +};
I was hoping this could be on the schema itself using `refine` or `superRefine`. Did you try that?

2022-11-01 19:57 UTC, melocule commented on src/components/content/forms/condition-schema.tsx
> +};
Yeah I tried that initially, but .refine and .superRefine return a Zod.Effects instead of a Zod.Object which messes things up

2022-11-01 20:01 UTC, melocule commented on src/components/core/alert.tsx
> +    <XCircleIcon className="ctw-h-5 ctw-flex-none ctw-text-error-icon" />
Hey! I took this from something Jesse sent me, let me just confirm this edit with him

2022-11-01 21:34 UTC, melocule commented on src/components/core/main.scss
>    }
Hmm just discussed with Priyank about this, the select box is peculiar because the "v" icon is added automatically outside of our code and there doesn't seem to be a way to move it. We might need to keep this special styling and have the error icon just stay on the left of the selector. 

Any chance we can huddle on this tomorrow (if you want to take a look)?

2022-11-03 18:04 UTC, WesleyKapow approved these changes
Looks good! Left a few nitpicks.

2022-11-03 18:04 UTC, WesleyKapow commented on src/components/content/forms/types.ts
> +  status:
Can this be defined via fhir4?

2022-11-03 18:26 UTC, melocule commented on src/components/content/forms/condition-schema.tsx
> +});
This makes extend not work unfortunately

2022-11-03 18:58 UTC, WesleyKapow approved these changes

2022-11-03 19:31 UTC, merged