Add Patient History hiding features
zeus-health/ctw-component-library pull request #208
Opened 2022-11-08 16:49 UTC by pmadria3

Draft PR - blocked by issue on DA team but just tossing this in a Draft PR

2022-11-08 18:49 UTC, WesleyKapow commented on src/fhir/types.ts
> +};
These aren't fhir types right? Should probably live with patient history stuff.

2022-11-18 14:42 UTC, WesleyKapow requested changes
Add screenshot of new UI!

2022-11-18 14:42 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +          )}
I think all of this can be pushed into the `RetrievePatientHistory` component. You also don't want the onClick to trigger `handleClinicalHistory`. Instead the onClick will open the future history request drawer.

2022-11-18 14:42 UTC, WesleyKapow commented on src/components/core/patient-history/patient-history-message.tsx
> +export const RetrievePatientHistory = ({
1. Component name should match file name.
2. This is not a "core" component. I need to re-organize these but the thought is "core" components are for our building blocks and "content" components are for specific use cases, like conditions, medications, patient history. Another way of thinking about it is "core" components could be used in a non CTW application. They are generic and have nothing to do with healthcare or CTW/profile.

2022-11-18 14:42 UTC, WesleyKapow commented on src/components/core/patient-history/patient-history-message.tsx
> +  <div className="ctw-body-container">
Don't use this class. Inline whatever it is you need.

2022-11-18 14:42 UTC, WesleyKapow commented on src/components/core/patient-history/patient-history-message.tsx
> +      <div className="ctw-title-container" />
Don't use this class and this div is empty/useless.

2022-11-18 14:42 UTC, WesleyKapow commented on src/components/content/patient-history/patient-history-types.ts
> +export type RawPatientRefreshHistoryMessage = {
Move this and `patient-history.ts` into `src/services/patient-history/`. I'll later refactor `fhir` to be moved into this new `services` directory.

2022-11-18 14:42 UTC, WesleyKapow commented on src/components/content/patient-history/patient-history-types.ts
> +export type PatientRefreshHistoryMessage = {
These two are so similar, why do we need both?

2022-11-18 14:42 UTC, WesleyKapow commented on src/components/content/patient-history/patient-history.ts
> +        "practitioner-role": "Test Provider",
Oh dear, do we really need these? We won't have these!

2022-11-18 14:42 UTC, WesleyKapow commented on src/components/content/patient-history/patient-history.ts
> +    ).map((entry: RawPatientRefreshHistoryMessage) => ({
What's the purpose of this mapping?

2022-11-18 14:42 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +  handleClinicalHistory();
This should be done in a `useEffect`, otherwise this will get called many many times, like when the component re-renders.

2022-11-23 19:43 UTC, WesleyKapow submitted a review, later dismissed

2022-11-23 19:43 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +            <PatientHistoryMessage message="Retrieve patient clinical history." />
Do we ever use a different `message` for this component? If not push it into `PatientHistoryMessage`.

2022-11-23 19:43 UTC, WesleyKapow commented on src/services/patient-history/patient-history.ts
> +        "practitioner-role": "Test Provider",
TODO

2022-11-23 19:43 UTC, WesleyKapow commented on src/services/patient-history/patient-history.ts
> +    /* eslint no-underscore-dangle: 0 */
Don't think this is needed.

2022-11-23 19:43 UTC, WesleyKapow commented on src/services/patient-history/patient-history.ts
> +export async function getLatestPatientRefreshHistoryMessage(
How do you imagine this function will be used in other situations? Why this function and not something like `hasFetchedPatientHistory` that returns a `Promise<boolean>`?

2022-11-29 19:07 UTC, WesleyKapow requested changes

2022-11-29 19:07 UTC, WesleyKapow commented on src/components/content/conditions/story-helpers/mocks/patient-history-message.ts
> +    0: {
Do they really return a data object with `0` as a key instead of an array?

2022-11-29 19:07 UTC, WesleyKapow commented on src/components/content/patient-history/patient-history-message.tsx
> +    <div>{children}</div>
Do we vary what we pass in as children here or is it always the `Request Records` button? If it doesn't vary, let's not make it configurable -- YAGNI!

2022-11-29 19:07 UTC, WesleyKapow commented on src/services/patient-history/patient-history.ts
>    statuses: string[]
Why does this need to take `statuses`?

2022-11-29 19:12 UTC, pmadria3 commented on src/components/content/conditions/story-helpers/mocks/patient-history-message.ts
> +    0: {
Yep that's what the response looks like 

![Screen Shot 2022-11-29 at 1 11 18 PM](https://user-images.githubusercontent.com/98342697/204623730-50467954-120a-42f5-8004-0cf7a4be9219.png)

2022-11-29 19:26 UTC, pmadria3 commented on src/services/patient-history/patient-history.ts
>    statuses: string[]
Originally had it as an array since there can be multiple but I only need to worry about done so changed it - good catch!

2022-11-29 19:44 UTC, WesleyKapow commented on src/components/content/conditions/story-helpers/mocks/patient-history-message.ts
> +    0: {
yikes ok

2022-11-29 19:45 UTC, WesleyKapow commented on src/services/patient-history/patient-history.ts
>    statuses: string[]
Why does this need to take a status at all?

2022-11-29 19:47 UTC, WesleyKapow commented on src/services/patient-history/patient-history.ts
>    statuses: string[]
What does it mean for a caller of this function to pass in something other than `done`? In english what is this function's contract? E.g. "Hey I'll let you know if the user has had any patient history data already fetched" OR "hey I'll let you know if the user has had any patient history fetched with the given status"? Which do we want?

2022-11-29 19:53 UTC, pmadria3 commented on src/services/patient-history/patient-history.ts
>    statuses: string[]
ah good point there is no need to pass in anything

2022-11-29 19:58 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +      patientResponse.data?.id as string
hmm also just noticed this `as string`.. we shouldn't lie! Looks like this could be `undefined`. What happens then?

2022-11-29 19:59 UTC, WesleyKapow submitted a review, later dismissed

2022-11-29 19:59 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +              onClick={() => setRequestDrawerisOpen(true)}
s/DrawerisOpen/DrawerIsOpen (capitalize the `i`)

2022-11-29 20:15 UTC, WesleyKapow approved these changes

2022-11-29 20:21 UTC, merged