Ctw 538/delete condition enters in error instead of delete
zeus-health/ctw-component-library pull request #214
Opened 2022-11-09 16:38 UTC by luthfib

CTW-538

Delete functionality for validation status now edits to entered-in-error instead of deleting.

2022-11-09 17:09 UTC, WesleyKapow requested changes
The modal edit module still has `onDelete` and talks about removal.

I suggest leave it as it was w.r.t being a delete modal (and not an edit modal).

Have the modal NOT do the actual delete part and instead invoke `onDelete` and `await` that before closing.

The conditions `onDelete` should take the current condition resource, set the verification status and save that. That way you don't lose any parts of the resource.

2022-11-14 14:05 UTC, WesleyKapow requested changes

2022-11-14 14:05 UTC, WesleyKapow commented on src/components/content/conditions-helper.ts
> +) => {
Have this function take a `fhir4.Condition` and set the clinicalStatus to `entered-in-error`.

2022-11-14 14:05 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +              requestContext.fhirClient
Have `onConditionDelete` handle everything.

2022-11-14 14:05 UTC, WesleyKapow commented on src/components/content/conditions-helper.ts
> +    queryClient.invalidateQueries([QUERY_KEY_OTHER_PROVIDER_CONDITIONS]),
Shouldn't need to re-query other provider conditions.

2022-11-14 14:05 UTC, WesleyKapow commented on src/fhir/conditions.ts
> +export const getDeleteConditionFhirResource = async (
Should be able to remove this. The idea is we should take the raw `fhir4.Condition` resource, set the clinicalStatus and save that.

2022-11-14 15:34 UTC, WesleyKapow commented on src/components/content/conditions-helper.ts
> +) => {
`conditionModel.resource`. All of our fhir models wrap an actual fhir resource.

2022-11-14 16:45 UTC, WesleyKapow requested changes

2022-11-14 16:45 UTC, WesleyKapow commented on src/components/content/conditions-helper.ts
> +  const resourceToDelete = { ...resource };
??? This so you don't modify the existing one? Use `cloneDeep` if you want to do that. Otherwise what will happen is you will create an object where all of the top level key/values are cloned but any nested are not. So in this case, you are in fact still modifying the `verificationStatus.coding` that exists on the original.

2022-11-14 16:45 UTC, WesleyKapow commented on src/components/content/conditions-helper.ts
> +  ) {
This guard needed? What if there is no verificationStatus? We still want to set it to `entered-in-error` right? You can probably avoid the if and just ALWAYS setup `verificationStatus`. Something like `verificationStatus = {coding: [{code: ..., system}]}`

2022-11-14 16:45 UTC, WesleyKapow commented on src/components/content/conditions-helper.ts
> +  const resourceToDelete = { ...resource };
Also name implies you are going to delete the resource. While this is `onConditionDelete`, we aren't actually deleting it.

2022-11-14 17:16 UTC, WesleyKapow approved these changes
LGTM

I do wonder if there is a reason you wanted to clone the resource. Would it be a problem to set it directly? would that have impacted some display in the FE before it was really set/saved?

2022-11-14 17:48 UTC, melocule requested changes

2022-11-14 17:48 UTC, melocule commented on src/components/content/conditions-helper.ts
> +  const clonedResource = cloneDeep(resource);
Hey Luthfi! Can I ask why the resource needs to be cloned here instead of modifying it directly?

2022-11-14 17:50 UTC, luthfib commented on src/components/content/conditions-helper.ts
> +  const clonedResource = cloneDeep(resource);
Yes, we can’t modify params. One of our eslint, usually because it can cause problems, so we clone it to avoid doing that.

2022-11-14 17:51 UTC, luthfib commented on src/components/content/conditions-helper.ts
> +  const clonedResource = cloneDeep(resource);
https://eslint.org/docs/latest/rules/no-param-reassign

2022-11-14 17:57 UTC, WesleyKapow commented on src/components/content/conditions-helper.ts
> +  const clonedResource = cloneDeep(resource);
Ah cool, didn't realize that guarded nested re-assignments too. YAY!

2022-11-14 18:23 UTC, melocule approved these changes

2022-11-14 19:05 UTC, WesleyKapow approved these changes

2022-11-14 19:06 UTC, merged