CTW-515/improve-onset-and-abatement
zeus-health/ctw-component-library pull request #218
Opened 2022-11-09 21:39 UTC by pmadria3

[CTW-515](https://zeushealth.atlassian.net/jira/software/projects/CTW/boards/49?selectedIssue=CTW-515)

This PR reduces verification status options for adding conditions and does some form validation on hitting submit for the date fields. 

![Screen Shot 2022-11-09 at 3 38 50 PM](https://user-images.githubusercontent.com/98342697/200947402-ebc83fbb-d0a8-453b-a1ef-763083d1078a.png)

2022-11-09 21:40 UTC, pmadria3 commented
Right now - I'm throwing an error but am open for suggestions on what we want to do @WesleyKapow

2022-11-14 14:36 UTC, WesleyKapow requested changes

2022-11-14 14:36 UTC, WesleyKapow commented on src/components/content/forms/condition-schema.tsx
> +    verificationStatus: z.enum(["confirmed", "unconfirmed"]),
Interesting, `conditionSchema` already has `verificationStatus`, I guess this just overwrites it? Maybe more clarity, move it out of the shared `conditionSchema` and put it in the conditionEditSchema.

2022-11-14 14:36 UTC, WesleyKapow commented on src/components/content/forms/form-field.tsx
> +  errors?: string | string[];
Undo these changes, this should continue taking an array of errors.

Being able to pass a string for `errors` has a few issues:
1. It's called `errors` (plural) implying it is an array.
2. The bigger issue is we're treating it as an array. You're even doing `as string[]` below. And as a reminder, you RARELY should ever use `as` in typescript. It's only when we know something has to be a certain type but the TS compiler doesn't.

2022-11-14 14:36 UTC, WesleyKapow commented on src/components/content/forms/drawer-form.tsx
> +    });
We don't need the `isInvalid` state. There's already state for handling and displaying errors, `setErrors`. This is why I had you console.log other form errors to see what `setErrors` should look like. You should loop over the input elements and for each one that is invalid, add an error for that key to `inputErrors`. Then, if `inputErrors` is not empty, `setErrors(inputErrors)` and `return`.

2022-11-14 14:36 UTC, WesleyKapow commented on src/components/content/forms/drawer-form.tsx
> +    const formDataValidationToArray = Array.from(formDataValidation);
```suggestion
    const inputs = Array.from((event.target as HTMLElement).querySelectorAll(
      "input"
    ));
```

`formDataValidation` and `formDataValidationToArray` are really awkward names. `formDataValidation` does not point to any type of validation, it points to inputs. `formDataValidationToArray` doesn't point to anything that will transform it, e.g. `to array` it. It instead points to an array. Generally it is good practice to not have the type included in the name variables as we can easily see the type. You also do all of this in one pass to avoid the extra variable, and just call it `inputs` or `inputElements` to make it clear these are DOM elements.

2022-11-14 19:29 UTC, WesleyKapow requested changes

2022-11-14 19:29 UTC, WesleyKapow commented on src/components/content/forms/drawer-form.tsx
>      });
You don't need `errorMessagesArray`. Populate `inputErrors` in a single pass.

2022-11-14 19:29 UTC, WesleyKapow commented on src/components/content/forms/drawer-form.tsx
> +    if (Object.keys(inputErrors).length) {
`!isEmpty` from lodash maybe? Would make this line a bit more explicit of the intent.

2022-11-14 19:29 UTC, WesleyKapow commented on package-lock.json
>        "integrity": "sha512-5dgndWOriYSm5cnYaJNhalLNDKOqFwyDB/rr1E9ZsGciGvKPs8R2xYGCacuf3z6K1YKDz182fd+fY3cn3pMqXQ==",
You shouldn't have any package-lock.json changes when you didn't make any package.json changes (unless you are explicitly wanting to upgrade a lib version). This likely happened because you deleted the lock file and ran `npm install`. See if you can get things working right with reverting this change.

2022-11-14 19:43 UTC, WesleyKapow commented on src/components/content/forms/drawer-form.tsx
> +    Object.entries(inputs).forEach(([_, value]) => {
What type is `inputs`? Why `Object.entries` here?

2022-11-14 19:54 UTC, WesleyKapow submitted a review, later dismissed

2022-11-14 20:44 UTC, merged