Ctw 472/patient history request drawer
zeus-health/ctw-component-library pull request #257
Opened 2022-11-17 14:15 UTC by luthfib

Adds the following: 
- [x] Patient Request Drawer
- [x] Allows user to pre-populate their patient data from the zus patient api
- [x] Modify patient data on save
- [x] Hit the patient history api once the data save is confirmed 
- [x] Handle patient history api errors

<img width="461" alt="image" src="https://user-images.githubusercontent.com/16874444/203423971-d3b4f4b8-4fee-4b40-89ad-eb9d64428c99.png">

2022-11-18 15:28 UTC, WesleyKapow requested changes

2022-11-18 15:28 UTC, WesleyKapow commented on src/components/core/form/drawer-form-with-fields.tsx
> +                // TODO: figure out why typescript thinks this can be undefined
If `errors` can be `undefined` then `errors?.[field]` can be `undefined`.

2022-11-18 15:28 UTC, WesleyKapow commented on src/components/content/condition-header.tsx
> +export const ConditionHeaderSummary = ({
This is pretty trivial and used in one place. I vote inline it and remove this extra component.

2022-11-18 15:28 UTC, WesleyKapow commented on src/components/core/form/drawer-form-with-fields.tsx
> +    };
See if you can get by without using `presentational`. You can still use this union type and `nevers` to specify the two types of uses. You can also pull these subtypes out to give you something like `export type FormType = FormFieldType | FormContentType` (where those subtypes are defined just above and are also exported).

2022-11-18 15:28 UTC, WesleyKapow commented on src/components/content/patient-history-request-drawer.tsx
> +export class RequestData {
What's this? How about a simple object `{name: "", ...}`?

2022-11-18 18:45 UTC, luthfib commented on src/components/content/patient-history-request-drawer.tsx
> +export class RequestData {
This will get removed, it was simply to mock an object

2022-11-21 15:29 UTC, luthfib commented on src/components/core/form/drawer-form-with-fields.tsx
> +                // TODO: figure out why typescript thinks this can be undefined
Yup, but theoretically if check for presentational being false then errors should be defined, which indicates im typing incorrectly somewhere

2022-11-21 15:29 UTC, luthfib commented on src/components/core/form/drawer-form-with-fields.tsx
> +    };
You mean without adding a new prop of presentational?

2022-11-21 15:34 UTC, WesleyKapow commented on src/components/core/form/drawer-form-with-fields.tsx
> +    };
Yes. I don't think it is needed.

2022-11-21 15:41 UTC, luthfib commented on src/components/core/form/drawer-form-with-fields.tsx
> +    };
specifically if we do..

```
 if (presentational) {
                  return (
                    <FormField
                      key={label}
                      readonly={readonly}
                      render={render}
                    />
                  );
                }
```

2022-11-21 15:44 UTC, WesleyKapow commented on src/components/core/form/drawer-form-with-fields.tsx
> +    };
`if (field)`

2022-11-21 15:44 UTC, WesleyKapow commented on src/components/core/form/drawer-form-with-fields.tsx
> +    };
`presentational` is redundant.. you know if it is presentational based on the other props.

2022-11-23 20:04 UTC, WesleyKapow requested changes

2022-11-23 20:04 UTC, WesleyKapow commented on src/fhir/models/patient.ts
>  import { findReference } from "@/fhir/resource-helper";
Models shouldn't have any setters. This was a failed pattern from CTW. Instead, any mutations should happen directly on a `fhir4.resource`, and it is that resource that should be saved. No model should be involved in mutations!

2022-11-23 20:04 UTC, WesleyKapow commented on src/components/content/forms/patients.ts
> +      `Managing organization not found with id of ${patient.organization?.id} and is needed in order to perform patient scheduling.`
Why do I care about patient scheduling here? This is `editPatient` not some setup scheduling helper.

2022-11-23 20:04 UTC, WesleyKapow commented on src/components/content/forms/patients.ts
> +      `Managing organization not found with id of ${patient.organization?.id} and is needed in order to perform patient scheduling.`
Ah you do it lower! Refactor this! editing a patient and fetching history are two separate actions. Our drawer may do both, but they are separate actions.

2022-11-23 20:04 UTC, WesleyKapow commented on src/components/content/forms/patients.ts
> +  }
This is gross. Can you refactor this out? Maybe into `createOrEditFhirResource`?

2022-11-28 13:52 UTC, luthfib commented on src/components/content/patient-history-request-drawer.tsx
> +    patientID={patient.id}
This has been in here for a while. I'll see about refactoring this, however I am pretty sure at this point medications, and conditions all use this prop.

2022-11-28 14:52 UTC, luthfib commented on src/components/content/forms/patients.ts
> +  }
I don't think it makes sense to put it into `createOrEditFhirResource` because it edits the result object, not sure thats something we want to introduce into `createOrEditFhirResource `

2022-11-28 15:27 UTC, WesleyKapow requested changes

2022-11-28 15:27 UTC, WesleyKapow commented on src/components/content/forms/patients.ts
>    }
Why is this needed? I don't see us passing any of this to the `schedulePatientHistory` function. Can we instead rely on the request returning an error?

2022-11-28 15:27 UTC, WesleyKapow commented on src/components/content/forms/patients.ts
> +export const editPatientAndScheduleHistory = async (
Ideally this would just be `scheduleHistory`. Having smaller helpers is more flexible. You can then define `editPatientAndScheduleHistory` where you use it and have it call the two helpers.

2022-11-28 16:05 UTC, luthfib commented on src/components/content/forms/patients.ts
> +export const editPatientAndScheduleHistory = async (
It already combined two helpers, `schedulePatientHistory` and `editPatient`. Not sure why a even more generic version would look like?

2022-11-28 16:37 UTC, WesleyKapow approved these changes

2022-11-28 17:08 UTC, merged