CTW-336 User sort conditions
zeus-health/ctw-component-library pull request #260
Opened 2022-11-18 20:52 UTC by melocule

CTW-336
Conditions are sortable by name and group in ascending and descending order by the user.
- By default, conditions are sorted by group in ascending order
- Within the same group, conditions are always sorted alphabetically in ascending order
- Records with a blank in the field being sorted with always show last

https://user-images.githubusercontent.com/33408946/202798298-8874fdf1-40ad-45bc-9adb-5b9c16078807.mov

2022-11-18 20:56 UTC, luthfib requested changes
Seems you have some changes you havent pulled into your branch. Somethings funky going, fix that and request review because it is a bit hard to tell which files you changed. (Let me know if you need help fixing the conflicts)

2022-11-18 21:46 UTC, luthfib requested changes
The Chevron should only show up when the column is not actively being sorted or being hover. Having the Chevron show up, even dimmed looks a bit odd.

2022-11-18 21:46 UTC, luthfib commented on src/utils/sort.ts
> +    sortOrder: sortOrder as NewType,
Do we need `newType` here? I think it is you can just do `sortOrder as SortDir`

2022-11-18 21:46 UTC, luthfib commented on src/components/content/conditions-table-base.tsx
> +        0.1 * alphaSortBlankLast(a.display, b.display, "asc"),
Can this be abstracted to where we dont have to pass in the sort function everytime but instead we just specify that we want the column to be sortable?

2022-11-21 15:43 UTC, melocule commented
Todo: Sync the sort for the two tables

2022-11-21 20:22 UTC, melocule commented on src/components/content/conditions-table-base.tsx
> +        0.1 * alphaSortBlankLast(a.display, b.display, "asc"),
Hey! I think if I replace `sortFn` with just the `sortProperty` we'd lose some control over how each column is sorted-- e.g. right now, the lambda for sorting by category secondarily sorts by condition name in ascending order. Would there be a workaround for that?

2022-11-21 22:28 UTC, melocule commented on src/components/content/conditions-table-base.tsx
> +        0.1 * alphaSortBlankLast(a.display, b.display, "asc"),
Just pushed up the new version where, for a column to be sortable, either a comparator function or the index to sort by should be provided

2022-11-22 15:14 UTC, luthfib commented on src/components/content/conditions-table-base.tsx
> +        0.1 * alphaSortBlankLast(a.display, b.display, "asc"),
There seems to be a couple ts issues

2022-11-22 17:53 UTC, luthfib approved these changes

2022-11-22 18:19 UTC, merged