CTW-532 Merge builder-owned and lens medications
zeus-health/ctw-component-library pull request #269
Opened 2022-11-22 21:13 UTC by eric-gunther

https://www.loom.com/share/d28140dde76c4e468b69a51ebfef7b24

2022-11-22 21:13 UTC, eric-gunther commented on src/App.tsx
> -        </div>
The network traffic was a little confusing to debug with 2 copies of the meds component on the sample app page.

2022-11-22 21:16 UTC, eric-gunther commented on src/fhir/medications.ts
> +export function splitMedications(
This function's logic could probably be made more concise, but this is somewhat complicated logic so I was trying to make it more explicit.

2022-11-28 16:56 UTC, WesleyKapow requested changes

2022-11-28 16:56 UTC, WesleyKapow commented on .changeset/fair-adults-tickle.md
> +Updated logic for displaying builder owned medications.
nit: What was changed from a user perspective?

2022-11-28 16:56 UTC, WesleyKapow commented on src/App.tsx
> -        </div>
Storybook FTW!

2022-11-28 16:56 UTC, WesleyKapow commented on src/fhir/medications.test.ts
> +    expect(builderMedications).toHaveProperty(
TIL `toHaveProperty`, that's convenient!

2022-11-28 16:56 UTC, WesleyKapow commented on src/fhir/medications.ts
> +  // Get builder owned medications that line up with an active medication.
So the lens record has a bunch of data you want to display in the builder table? What does it have? Why can't the builder record have it? Is it things like request/dispenses? Should we instead fetch those and link to the actual resources?

2022-11-28 16:56 UTC, WesleyKapow commented on src/fhir/medications.ts
> +    const mergedMed = clone(
Probably better to use `cloneDeep`, otherwise you get a shallow clone where modifying any of the copied objects would modify the original.

2022-11-28 20:27 UTC, eric-gunther commented on src/fhir/medications.ts
> +    const mergedMed = clone(
Figured that cloneDeep was overkill since I'm not modifying any of the nested objects, but that probably makes this unsafe/vulnerable to future changes.

2022-11-28 20:32 UTC, eric-gunther commented on src/fhir/medications.ts
> +  // Get builder owned medications that line up with an active medication.
The lens record has last prescribed date, last prescriber, last dispensed date, (all of which we display on the table) and a few other properties that the lens process calculates and then writes to the lens med statement as an extension. There's been a bunch of conversation as to whether that's an abuse of extensions and perhaps this data is better expressed as just a reference to med requests/dispenses. Evan has some more opinions/background on this, but from my perspective it's about providing a convenient way of accessing a bunch of data about a "medication summary". The builder record doesn't have any of this stuff, it's just some medication statement belonging to the builder, without any additional context.

One reason for this change is to display the builder's display text for the med (in case it is different than the lens display text).

Perhaps more importantly, we don't want this part of the component to be too sensitive to lens latency, especially if users expect data to show up immediately after writing it. So if we're stuck waiting a few seconds for lens to process then there may be a lag in the last prescribed/last dispensed information showing up, but there won't be a lag in the row showing up.

2022-11-28 23:25 UTC, WesleyKapow commented on src/fhir/medications.ts
> +  // Get builder owned medications that line up with an active medication.
Right I think I get what you're doing but it seems brittle. You are taking a lens resource and treating it as a builder resource by replacing a few things. What if we want to replace more? What if the lens has stuff that's "wrong" w.r.t a builder resource.

I think ideally we'd either:
1. Fetch the associated resources we need to display the data we want to display.
2. Create a new FHIR resource type to contain all of the "medication" bits we want in a single resource.

I'm fine with this change as is but definitely encourage you and lens folk think through this and decide on what solution you want going forward.

2022-11-28 23:25 UTC, WesleyKapow submitted a review, later dismissed

2022-12-01 17:44 UTC, eric-gunther commented
Latest testing round:

https://user-images.githubusercontent.com/97455910/205123485-7130a50b-c9d7-450a-8ed8-4d3c5077ca56.mov

2022-12-01 20:00 UTC, mrosata approved these changes

2022-12-01 20:25 UTC, merged