CTW-336 user sort conditions redo
zeus-health/ctw-component-library pull request #288
Opened 2022-11-29 22:28 UTC by melocule

CTW-336
Redo condition sorting to allow all columns to be sortable, and sort primarily by last recorded date and condition name.

Based on some updated AC:
- Conditions Tables should remain sorted by descending recorded date, followed by condition name
- Instead of only two sortable columns, make all sortable
- Flip the sort arrow (up chevron means ascending order, down chevron means descending order)

2022-11-29 22:31 UTC, luthfib commented on src/components/core/table/table-rows.tsx
> +  console.log("TableRows", records);
Remove console.log
```suggestion
```

2022-11-29 22:31 UTC, luthfib commented on src/components/core/table/table.tsx
> +  console.log("Result of sortRecords(...)", sortedRecords.slice(0, count));
Remove 

```suggestion
```

2022-11-29 22:33 UTC, luthfib commented on .changeset/small-gifts-refuse.md
> +Redo condition sorting to allow all columns to be sortable, and sort primarily by last recorded date and condition name.
```suggestion
Condition sorting now allows all columns to be sortable. Sort primarily defaults to be by last recorded date and condition name.
```

2022-11-30 18:13 UTC, pmadria3 commented on src/components/core/table/table-helpers.tsx
> +          // eslint-disable-next-line @typescript-eslint/no-explicit-any
do we need this eslint disable?

2022-11-30 18:13 UTC, pmadria3 commented on src/components/core/table/table-helpers.tsx
> +          // eslint-disable-next-line @typescript-eslint/no-explicit-any
should we be setting this as any?

2022-11-30 19:24 UTC, melocule commented on src/components/core/table/table-helpers.tsx
> +          // eslint-disable-next-line @typescript-eslint/no-explicit-any
I also thought it shouldn't be needed, but I get this issue when I remove the cast:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/33408946/204889606-4e0dbf8d-15dc-4889-98ef-c83741b849df.png">

2022-11-30 20:28 UTC, WesleyKapow commented on src/components/core/table/table-helpers.tsx
> +          // eslint-disable-next-line @typescript-eslint/no-explicit-any
TS is right, you are saying this function takes anything (`T`) and then you try and call `toString()` on whatever `T` is. 

What are the possible types of T? Anything a model getter could return ya?

I think this won't work for numbers, `undefined`, & `null`.
```js
true.toString()
// 'true'
"foo".toString()
// 'foo'
5.toString()
// VM192:1 Uncaught SyntaxError: Invalid or unexpected token
```

Maybe use `${firstCompare[indices[i]]}` instead? Also verify this properly works for undefined and nulls.

2022-11-30 20:30 UTC, WesleyKapow commented on src/components/core/table/table-helpers.tsx
> +          // eslint-disable-next-line @typescript-eslint/no-explicit-any
May also wan't to consider if using lodash would help or not (I'm not sure).

https://stackoverflow.com/questions/41138820/lodash-orderby-with-null-and-real-values-not-ordering-correctly

2022-12-01 19:09 UTC, melocule commented on src/components/core/table/table-helpers.tsx
> +          // eslint-disable-next-line @typescript-eslint/no-explicit-any
Hey! I used your solution Wesley and it worked, thanks for sharing it.

2022-12-01 19:26 UTC, WesleyKapow requested changes

2022-12-01 19:26 UTC, WesleyKapow commented on src/components/core/table/table-helpers.tsx
> +        ) *
Have you verified behavior when these are `null` or `undefined`? This string conversion will give you the literal string `undefined` which will not be treated as a blank in your comparison function.

2022-12-01 19:52 UTC, melocule commented on src/components/core/table/table-helpers.tsx
> +        ) *
Thanks for this callout, just submitted a patch that I tested for this case

2022-12-01 20:52 UTC, WesleyKapow reviewed
hmmm this is fairly complicated code, I can't easily determine "correctness" here and as we noted there are numerous edge cases and tricky aspects to this.

Which means... dun dun dunnn... UNIT TESTS! Please write unit tests to prove correctness in a handful of different situations (null, numbers, undefined, strings, blanks, etc).

2022-12-05 15:06 UTC, WesleyKapow commented on src/components/core/table/table-helpers.tsx
> +    (dir === "asc" && !o[index]) || (dir === "desc" && o[index]);
Also `!o[index]` will rule out columns with a zero `0`. This should explicitly check if the value is empty or not.

Check out this helper I made in CTW -- https://github.com/zeus-health/ctw/blob/main/app/utils.ts#L18

I'd probably change it to `isEmptyValue` (not plural).

2022-12-05 15:06 UTC, WesleyKapow commented on src/components/core/table/table-helpers.tsx
> +  // Makes a list of iteratees, where each index iteratee is preceded by an iteratee that ensures blanks go last.
This is a great approach!

2022-12-05 15:16 UTC, WesleyKapow commented on src/components/core/table/table-helpers.tsx
>  export function sortRecords<T extends MinRecordItem>(
Change this to `T extends Record<string, unknown>` and 🤞 you can then remove your eslint stuff.

2022-12-05 15:21 UTC, melocule commented on src/components/core/table/table-helpers.tsx
> +    // ESLint disabled as the index may not exist on this object.
Oh actually using isEmptyValue(...) removes the need to disable this rule

2022-12-05 19:09 UTC, WesleyKapow submitted a review, later dismissed
LGTM, note I left one open question.

2022-12-05 19:09 UTC, WesleyKapow commented on src/components/core/table/table-helpers.tsx
> +    orders = orders.concat(["asc", dir || "asc"]);
So we always want blanks last regardless of asc/desc?

2022-12-05 19:54 UTC, melocule commented on src/components/core/table/table-helpers.tsx
> +    orders = orders.concat(["asc", dir || "asc"]);
Yupyup, asked the team about this when I was initially working on this ticket and apparently that's the behavior elsewhere

2022-12-05 20:00 UTC, merged