Ctw 520/on patient save prop
zeus-health/ctw-component-library pull request #293
Opened 2022-11-30 21:41 UTC by luthfib

- Refactors so that form validation does not happen inside of the action but instead happens in the drawer form. This eliminates boiler plate as keeping the drawer consistent. Also ensures that we have custom function such as onPropSave they can be decoupled from what goes on in the form. 
- Add onPatientSave prop and adds it to the patient schedule history

Still need to: 
- [ ] Fix a couple of type issues relating to any but want to get some eyes on this before proceeding

2022-12-01 15:23 UTC, pmadria3 commented on src/components/content/forms/conditions.ts
> +  formValidation: { success: boolean; data: any; errors: undefined },
need a type that's not any

2022-12-01 15:25 UTC, pmadria3 commented on src/components/content/forms/conditions.ts
> +  formValidation: { success: boolean; data: any; errors: undefined },
I'll wait to review the rest - didn't realize it was in draft

2022-12-01 19:36 UTC, pmadria3 commented on src/components/content/patient-history-request-drawer.tsx
> +    // TODO: How do we want to handle errors from responses that arent defined by us?
just flagging

2022-12-02 14:58 UTC, melocule submitted a review, later dismissed

2022-12-02 14:58 UTC, melocule commented on README.md
> +3. `<PatientProvider>` also has an onPatientSave prop which can be used to override the behavior when saving patient information. onPatientSave should be an async function.
Nit
```suggestion
3. `<PatientProvider>` also has an `onPatientSave` prop which can be used to override the behavior when saving patient information. `onPatientSave` should be an async function.
```

2022-12-02 16:41 UTC, WesleyKapow requested changes
If the drawer is handling validation, then let it handle it. No need for the action/onPatientSave/etc to be called with errors. What would a consumer do with that?

I think you should be able to cleanup and hopefully remove all of these `OmitMatch` types.

2022-12-02 16:41 UTC, WesleyKapow commented on README.md
> +  /* Logic to send data to data
fix comment

2022-12-02 16:41 UTC, WesleyKapow commented on README.md
> +}
Why do they care about success or errors? We should do our own validation and only call this callback when the data is valid. They should return success or failure (via async promise resolve/reject).

2022-12-02 16:41 UTC, WesleyKapow commented on src/components/core/patient-provider.tsx
> +  onPatientSave?: (data: unknown) => Promise<unknown>;
The types for these two `onPatientSave` types don't match. The function should take a well defined data type and should return a promise void, e.g. `(data: PatientData) => Promise<void>`

2022-12-02 16:41 UTC, WesleyKapow commented on src/components/core/patient-provider.tsx
> +  const handleSave = useCallback(
nit: can just `return useCallback`... no need for `handleSave` variable.

2022-12-02 16:41 UTC, WesleyKapow commented on src/components/core/patient-provider.tsx
> +      if (typeof onPatientSave === "function") {
It can only be undefined or a function right? Could just do `if (onPatientSave)`

2022-12-02 16:41 UTC, WesleyKapow commented on src/components/core/form/drawer-form.tsx
> +    data: { success: boolean; data: T; errors: undefined },
Do we need to call action on errors? Why not simplify this and only call action when it passes schema validation.

2022-12-02 16:41 UTC, WesleyKapow commented on src/components/content/patient-history-request-drawer.tsx
> +    // TODO: How do we want to handle errors from responses that arent defined by us?
We need to wrap the `await onPatientSave` line in a try/catch and have the catch render a generic error

2022-12-02 16:41 UTC, WesleyKapow commented on src/components/content/forms/patients.ts
> +type OmitMatch<T extends { data: unknown }> = Omit<T, "data"> &
??? what's this doing? Why not use `PatientFormData` directly (and also remove the `Edit` from the type)?

2022-12-02 16:47 UTC, luthfib commented on src/components/core/form/drawer-form.tsx
> +    data: { success: boolean; data: T; errors: undefined },
You mean only pass data down to the action? Instead of passing errors and success as well?

2022-12-02 17:09 UTC, WesleyKapow commented on src/components/core/form/drawer-form.tsx
> +    data: { success: boolean; data: T; errors: undefined },
Yes. Why do actions need that info?

2022-12-02 18:52 UTC, mrosata commented on src/components/content/conditions.tsx
>      }
Is the idea here that `clinicalHistoryExists` is a tribool (true, false, or indeterminate) where an undefined clinicalHistoryExists means "we don't yet know the answer"?

If so we probably could just put that `handleClinicicalHistory` bit in a separate useEffect that only triggers when the `patientResponse.data.id` changes.

```tsx
useEffect(() => {
  if (patientResponse.data?.id) {
      handleClinicalHistory(patientResponse.data.id);
  }
}, [patientResponse.data?.id])
```

2022-12-02 19:23 UTC, mrosata commented on src/components/content/conditions.tsx
> +    useState<boolean>(false);
```suggestion
  const [clinicalHistoryExists, setClinicalHistoryExists] = useState(false);
```

2022-12-02 19:24 UTC, mrosata approved these changes

2022-12-02 19:27 UTC, merged