Ctw 536/multiple elem in single row
zeus-health/ctw-component-library pull request #296
Opened 2022-12-01 18:58 UTC by luthfib

2022-12-01 18:59 UTC, WesleyKapow commented
screens or it didn't happen

2022-12-01 19:01 UTC, luthfib commented
> screens or it didn't happen

Good point.

2022-12-01 19:09 UTC, WesleyKapow requested changes
Jumped on this PR because I was curious how you solved it, love the solution, very elegant!

2022-12-01 19:09 UTC, WesleyKapow commented on src/components/core/form/drawer-form-with-fields.tsx
> +            {data.map((record) => {
nit: s/record/entry

`record` is a little confusing

2022-12-01 19:09 UTC, WesleyKapow commented on src/components/core/form/drawer-form-with-fields.tsx
> +            })}
This all looks redundant to what is in `FormFieldEntry`, how about a `FormFieldEntry` and a `FormFieldEntries` which uses it?

2022-12-01 19:09 UTC, WesleyKapow commented on src/components/core/main.scss
> +    height: 2.25rem;
hmmm specific height's are a little scary. Height should usually be determined by font-size/padding/etc.

Why was this needed?

2022-12-01 19:14 UTC, luthfib commented on src/components/core/main.scss
> +    height: 2.25rem;
Specifically targeting this use case:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/16874444/205139823-992d01b4-078a-49f9-a6e5-12100a056129.png">

I can play around with it and see I find a solution that doesn't require specific height setting.

2022-12-01 19:58 UTC, melocule commented on src/components/core/main.scss
> +    height: 2.25rem;
Not so related to this PR but I just noticed an issue with the border color for when the listbox is selected, would you mind fixing it here? I noticed that it's purple for the other fields, but blue for the listboxes which looks a bit awkward
<img width="560" alt="image" src="https://user-images.githubusercontent.com/33408946/205147626-0e9c3208-7215-48a0-9643-950b028d2f8d.png">
<img width="554" alt="image" src="https://user-images.githubusercontent.com/33408946/205147665-4cd4dc6e-5c67-46b8-9662-df155ab4bad6.png">

2022-12-01 20:37 UTC, luthfib commented on src/components/core/main.scss
> +    height: 2.25rem;
I'll address it in a followup pr

2022-12-01 21:05 UTC, WesleyKapow submitted a review, later dismissed
Approving with a few nits.

2022-12-01 21:12 UTC, luthfib commented on src/components/core/form/drawer-form-with-fields.tsx
> +        <Fragment key={record.label}>
I only did `Fragment` because I need to add the React key

2022-12-01 21:16 UTC, WesleyKapow commented on src/components/core/form/drawer-form-with-fields.tsx
> +        <Fragment key={record.label}>
Ah of course, for some reason I was thinking you could do that without but of course not.

2022-12-02 15:28 UTC, WesleyKapow approved these changes

2022-12-02 15:28 UTC, WesleyKapow commented on src/components/core/form/drawer-form-with-fields.tsx
> +            {data.map((entry, idx) => {
nit: idx not used?

2022-12-02 15:30 UTC, merged