Add consent checkbox
zeus-health/ctw-component-library pull request #307
Opened 2022-12-05 22:39 UTC by luthfib

Adds a consent checkbox to the patient request drawer

<img width="579" alt="image" src="https://user-images.githubusercontent.com/16874444/205757872-018c77c3-a8c6-49c7-96d0-dc41594801ba.png">

Still need: 
 - [ ] Text for the checkbox in the patient request drawer

2022-12-06 16:58 UTC, WesleyKapow requested changes

2022-12-06 16:58 UTC, WesleyKapow commented on README.md
> +    consent: string;
`onPatientSave` doesn't care about `consent` and shouldn't receive it, just like `npi`.

2022-12-06 16:58 UTC, WesleyKapow commented on src/components/core/checkbox.tsx
> +export function Checkbox({ name, text }: CheckboxProps) {
Hmm not sure what the right name for this is. It's really a checkbox box as it not only has a checkbox ☑️, but wraps it in a box with some text.

Maybe `ConsentField` -- `core/forms/consent-field.tsx`?

2022-12-06 17:58 UTC, WesleyKapow approved these changes
LGTM

1. `ConsentField` should probably be in `core/form` directory.
2. Still have the todo around the message in that consent box.

2022-12-09 19:29 UTC, luthfib commented
We have decided not to do this

2022-12-09 19:29 UTC, closed without merging