Ctw 626/CCDA-follow-up
zeus-health/ctw-component-library pull request #370
Opened 2022-12-29 21:04 UTC by pmadria3

Opening draft PR with the changes - will modify description on last change.

2023-01-05 20:46 UTC, mrosata commented on src/components/content/CCDA/base64toBinaryField.tsx
> +    document.body.appendChild(a);
One suggestion would be to use `useRef` here instead of creating the html element ourselves, just so React knows about the anchor tag. I will try to see if I can find an example of this online and post it here.

2023-01-05 20:52 UTC, mrosata commented on src/components/content/CCDA/base64toBinaryField.tsx
> +    document.body.appendChild(a);
Found this custom react hook to download a file _(seems to do about the same thing you're doing but using an HTMLAnchor ref)_ https://www.techprescient.com/react-custom-hook-typescript-to-download-a-file-through-api/

2023-01-05 20:53 UTC, mrosata commented on src/components/content/CCDA/base64toBinaryField.tsx
> +    document.body.appendChild(a);
Here's the TLDR
```ts
import React from "react";
import { Button as InternalButton, Spinner } from "react-bootstrap";

export enum ButtonState {
  Primary = "Primary",
  Loading = "Loading",
}

interface ButtonProps {
  readonly buttonState: ButtonState;
  readonly onClick: () => void;
  readonly label: string;
}

export const Button: React.FC<ButtonProps> = ({
  buttonState,
  onClick,
  label,
}) => {
  const isLoading = buttonState === ButtonState.Loading;
  return (
    <div className="d-flex justify-content-center mt-5">
      <InternalButton onClick={onClick} variant="primary" size="sm">
        {isLoading && (
          <Spinner
            as="span"
            animation="border"
            size="sm"
            role="status"
            aria-hidden="true"
          />
        )}
        {!isLoading && label}
      </InternalButton>
    </div>
  );
};
```

2023-01-05 20:57 UTC, WesleyKapow requested changes
Looks great, just a few minor comments.

2023-01-05 20:57 UTC, WesleyKapow commented on src/components/content/CCDA/document-button.tsx
>      <svg
Pull SVG out into it's own component.

2023-01-05 20:57 UTC, WesleyKapow commented on src/components/content/condition-history/conditions-history.tsx
> +    useState<BinaryDocument>(DEFAULT_BINARY_DATA);
I think things would get simplified if you switch to two states, `isOpen` and `binaryDocument`.

2023-01-05 20:57 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +          <svg
Same as other svg? Pull out into it's own component.

2023-01-05 20:57 UTC, WesleyKapow commented on src/components/content/CCDA/base64toBinaryField.tsx
> +    a.download = "CCDA-XML-Document";
Is this the name of the file?

How about `CCDA-{condition}.xml`, where `condition` is some kebab-case of condition title/name?

2023-01-05 21:43 UTC, WesleyKapow commented on src/components/content/CCDA/base64toBinaryField.tsx
> +    document.body.appendChild(a);
Yes switch to `useRef`, you can search library for other examples.

2023-01-06 20:32 UTC, WesleyKapow commented on src/components/core/svg-document.tsx
> +export const SVGDocument = ({ className, height }: SVGDocumentProps) => (
Hmmm this isn't an SVGDocument.. what is it? What should this be named?

2023-01-06 21:28 UTC, pmadria3 commented on src/components/core/svg-document.tsx
> +export const SVGDocument = ({ className, height }: SVGDocumentProps) => (
Changed to DocumentIcon - is that better?

2023-01-06 23:01 UTC, WesleyKapow commented on src/components/core/svg-document.tsx
> +export const SVGDocument = ({ className, height }: SVGDocumentProps) => (
Perfect!

2023-01-09 17:09 UTC, WesleyKapow requested changes

2023-01-09 17:09 UTC, WesleyKapow commented on src/components/content/CCDA/base64toBinaryField.tsx
> +  const [name, setFileName] = useState<string>();
Our convention is to have the state name and the setter names match, so `[fileUrl, setFileUrl]` and `[fileName, setFileName]`.

2023-01-09 17:09 UTC, WesleyKapow commented on src/components/content/CCDA/base64toBinaryField.tsx
> +    setFileName(`CCDA-${fileName}`);
`.xml`?

2023-01-09 19:17 UTC, WesleyKapow commented on src/components/content/condition-history/conditions-history.tsx
> +                  onClick={() => onClick(entry.binaryId as string, entry.title)}
Ahh silly TypeScript and react, ok!

2023-01-09 19:18 UTC, WesleyKapow approved these changes

2023-01-09 19:20 UTC, merged