CTW312/transition-from-UPID-to-HealthieID
zeus-health/ctw-component-library pull request #38
Opened 2022-08-30 17:24 UTC by pmadria3

This PR transitions from using UPID to HealthieID. 
![Screen Shot 2022-08-30 at 12 24 31 PM](https://user-images.githubusercontent.com/98342697/187503408-5d0c2111-fe32-45dd-8a00-cd065c019fe8.png)

2022-08-30 17:59 UTC, luthfib commented on src/components/content/conditions.tsx
> +              system={system}
Do we use system here?  I dont see where it is used, but correct me if im wrong

2022-08-30 18:15 UTC, luthfib requested changes

2022-08-30 18:15 UTC, luthfib commented on src/fhir/search-helpers.ts
> +  const identifier = `${SYSTEM_HEALTHIE_ID}|${patientID}`;
Make this be able to pass in dont hardcode this in here

2022-09-01 19:40 UTC, luthfib submitted a review, later dismissed

2022-09-01 19:40 UTC, luthfib commented on src/components/core/patient-provider.tsx
> +export function IDProvider({ children, ...ctwState }: IDProviderProps) {
Please rename this to match the rest of the file

2022-09-01 21:07 UTC, luthfib requested changes

2022-09-01 21:07 UTC, luthfib commented on src/fhir/conditions.ts
> +        systemURL: systemZus,
same here? Not sure why we have to rename it if we are just passing it down, maybe rename the arg?

2022-09-01 21:07 UTC, luthfib commented on src/components/content/conditions.tsx
> +      );
It would be nice to do this in the provider, instead of having to do it in every component that we need it in. Im thinking something along the lines of.... 

` const { patientID, systemURL, patientUPID, system, patientDataIsLoading } =
    usePatientContext();`

Then we can trigger of a patientDataIsLoading
`
 if (!patientDataIsLoading) {
      load();
    }
`
and re trigger the useEffect with by adding `patientDataIsLoading` to the dep array. 

Inside of your provider code you could do something like....

`
useEffect(() => {
    async function load() {
      const fhirClient = await getCTWFhirClient();
      const response = await getUPIDfromPatientID(
        fhirClient,
        ctwState.patientID,
        ctwState.systemURL
      );
      setUPIDData(response);
      setIsLoading(false);
    }
    load();
  }, []);
`

This is just a potential nice to have, doesnt necessarily have to stop the pr and this isn't fully tested code or anything, but I think it would be nice because then we dont have calls everywhere translating patientID's to UPID

2022-09-01 21:10 UTC, pmadria3 commented on src/components/content/conditions.tsx
> +      );
Confer with @WesleyKapow on this

2022-09-01 21:13 UTC, luthfib submitted a review, later dismissed
Also dont forget to add a changeset.... `npx changeset`. Add a meaningful message

2022-09-02 18:43 UTC, WesleyKapow requested changes

2022-09-02 18:43 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +      );
Agreed. This should be handled by the `PatientProvider`.

Really the only thing `PatientProvider` needs to return to us is a way to get a UPID.

`const { getPatientUPID } = usePatientContext()`

This conditions component would then do `const patientUPID = await getPatientUPID()`. And the provider would either 1. quickly return the UPID it already fetched, or 2. fetch the UPID.

Loading state can be handled by the conditions component. Also no need for `systemURL` as this is a UPID and we can use the hardcoded system URL constant for that.

2022-09-02 18:43 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +      );
This will also open up the door for us in the future to make `PatientProvider` take either:
A. patientID & systemURL
B. patientUPID

So in the CTW app case, we'd already have a UPID from the URL, so we would do <PatientProvider patientUPID={valueFromURLParams}>` and then `getPatientUPID()` would return that one instead of ever needing to fetch one.

2022-09-06 20:14 UTC, WesleyKapow requested changes

2022-09-06 20:14 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +  const { getPatientUPID, patientID, systemURL } = usePatient();
Why do we need `patientID` and `systemURL`? Can we not:
1. Do everything off of UPID.
2. Pass UPID around and use `SYSTEM_ZUS_UNIVERSAL_ID` when constructing the query.

2022-09-06 20:14 UTC, WesleyKapow commented on src/fhir/search-helpers.ts
> +  patientFilters?: SearchParams
Do we need `patientFilters` here?

2022-09-06 20:14 UTC, WesleyKapow commented on src/fhir/search-helpers.ts
>    })) as fhir4.Bundle;
I think you can change this back to be based on `patientUPID` and not `patientID/systemURL`. My hope is we can keep things simple by ALWAYS fetching data by `patientUPID` EXCEPT when calling `getUPIDfromPatientID` which should NOT use the other search helpers. Instead it should search directly using the fhir client and find the first patient that has the matching system/patientID.

2022-09-08 14:18 UTC, WesleyKapow submitted a review, later dismissed

2022-09-08 14:18 UTC, WesleyKapow commented on src/components/core/patient-provider.tsx
> +});
Construct initial state with `undefined` like I did in CTWProvider.

```ts
React.createContect<ThirdPartyID | undefined>(undefined)
```

2022-09-08 14:18 UTC, WesleyKapow commented on src/components/core/patient-provider.tsx
> +} & ThirdPartyID;
So... we're gonna want this to work for EITHER:
A. Consuming app specifies `patientID` and `systemURL` OR
B. Consuming app specifies `patientUPID`

Look at CTWProvider for how this is setup. You'll want a state that has things as optional and a props that has `& (ThirdPartyID | {patientUPID})`

& (ThirdPartySpecified | PatientUPIDSpecified)

2022-09-08 14:18 UTC, WesleyKapow commented on src/components/core/patient-provider.tsx
> +  async function getPatientUPID() {
Make this function work for the case where `patientUPID` is passed in as a prop.. i.e check if we have `patientUPID` and if so, return it.

Also,  look at CTWProvider's `handleAuth`. What we want is for only the first call to this to have to fetch the UPID. And actually, we know we have to fetch it.. maybe go ahead and fetch it write away in `PatientProvider`, store in some `useState` stae. You'll want to store the promise of the fetch so that consumers of `getPatientUPID()` can still `await` until it is done. But this should simplify things so that you immediately try to get the UPID and cache it in the state.

2022-09-08 14:39 UTC, pmadria3 commented on src/fhir/search-helpers.ts
> +function patientSearchParams(
I agree - Eslint was complaining so moved it to stop but then just reverted it back to original

2022-09-08 20:07 UTC, WesleyKapow requested changes

2022-09-08 20:07 UTC, WesleyKapow commented on src/fhir/search-helpers.ts
>  export async function searchAllRecords<T extends ResourceTypeString>(
Please look at the diff you made to this function and the comments. Probably want to revert them?

2022-09-08 20:07 UTC, WesleyKapow commented on src/components/core/patient-provider.tsx
> +import React, { useContext, useEffect, useState } from "react";
Remove uses of `React.*` with the values directly.. so `ReactNode`, `createContext`, `useMemo`.

That way it is clear what things from `React` this file depends on.

2022-09-08 20:07 UTC, WesleyKapow commented on src/components/core/patient-provider.tsx
> +type CtwUPID = { patientUPID: string; patientID?: never; systemURL?: never };
CtwUPID? How about `PatientUPIDSpecified` (aligns with naming used in CTWProvider).

2022-09-08 20:07 UTC, WesleyKapow commented on src/components/core/patient-provider.tsx
> +  return { patientUPIDPromise };
Hmmm can be simplified to just `return useContext(CTWPatientContext)`.

2022-09-09 13:33 UTC, WesleyKapow requested changes

2022-09-09 13:33 UTC, WesleyKapow commented on src/fhir/search-helpers.ts
> -
Why remove this? It may be un-used a.t.m but I expect we'll want it.

2022-09-09 14:08 UTC, pmadria3 commented on .changeset/ninety-dolphins-shout.md
> +There's a new PatientProvider that allows the user to provide either a PatientUPID or a combination of PatientID/SystemUrl to be utilized for fetching conditions about the patient.
I left the conditions in there but added a note that we will utilize it for future resources

2022-09-09 14:28 UTC, WesleyKapow approved these changes

2022-09-09 14:28 UTC, WesleyKapow commented on .changeset/ninety-dolphins-shout.md
> +There's a new PatientProvider that allows the user to provide either a PatientUPID or a combination of PatientID/SystemUrl to be utilized for fetching conditions about the patient. Will be used to fe
The confusion here is that it has nothing to do with fetching conditions or other resources. All it does is provide a UPID, possibly by looking it up. What other components do with that UPID is their business.

2022-09-09 14:34 UTC, pmadria3 commented on .changeset/ninety-dolphins-shout.md
> +There's a new PatientProvider that allows the user to provide either a PatientUPID or a combination of PatientID/SystemUrl to be utilized for fetching conditions about the patient. Will be used to fe
I see - went ahead and fixed that to be specific to patientProvider.

2022-09-09 14:41 UTC, WesleyKapow approved these changes

2022-09-09 14:42 UTC, merged