CTW-619/list-navigation
zeus-health/ctw-component-library pull request #412
Opened 2023-01-18 22:04 UTC by pmadria3

This is a draft PR with the changes to the layout of the table. 
![Screenshot 2023-01-18 at 4 03 41 PM](https://user-images.githubusercontent.com/98342697/213305281-14db8795-24c8-462d-9320-b1c07291bcbb.png)

2023-01-19 17:48 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions-tabs.tsx
> +export type PatientConditionsActionsProps = {
File is `PatientConditionsTabs` .. not actions! Also if it is tabs, then I'd expect it to handle the tabs part of the component and not the next row which has the "actions".

2023-01-19 20:28 UTC, WesleyKapow submitted a review, later dismissed

2023-01-19 20:28 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions-actions.tsx
> +      <Toggle name="historic" text="Historic" onChange={onToggleShowHistoric} />
This should be visible regardless of `hideAdd`

2023-01-19 20:28 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions-actions.tsx
> +        onClick={() => showAddConditionForm()}
Can you just pass `showAddConditionForm` or do you have to wrap it in the function?

2023-01-19 20:28 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions-tabs.tsx
> +                      : "ctw-tab-underline ctw-tab-underline-hover:focus-visible ctw-tab ctw-relative ctw-space-x-2"
`:foo` are not actual classes and are instead "pseudo" selectors. You don't add them to the classes and instead only use them in CSS. Like you would NOT do `className="foo:hover bar:after"`. So you should be able to remove these `:focus-visible` classes.

2023-01-19 20:28 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions.scss
> +  .ctw-tab-underline-hover {
It's weird to call this hover, what does it have to do with hovering? Is this the class that gets applied when a tab is selected? So should there be a `ctw-tab-selected`?

2023-01-19 20:28 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions-tabs.tsx
> +                      : "ctw-tab-underline-hover:focus-visible ctw-tab-underline ctw-tab ctw-relative"
With `cx` you can conditionally added classes a few ways, here, I'd split out the classes that are always the same, and then only add the optional ones based on the bool, something like `"ctw-tab-underline ctw-tab ctw-relative", {"ctw-tab-selected": selected}`

2023-01-19 20:29 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions.tsx
> +        />
newline after this, just to help visually break up these large component uses

2023-01-19 20:42 UTC, pmadria3 commented on src/components/content/conditions/patient-conditions-actions.tsx
> +        onClick={() => showAddConditionForm()}
It has to be in a function

2023-01-19 20:42 UTC, pmadria3 commented on src/components/content/conditions/patient-conditions-actions.tsx
> +      <Toggle name="historic" text="Historic" onChange={onToggleShowHistoric} />
Do we want to show the historic/Add condition button in other provider records? If I remove the hideAdd it will show in that tab as well...right now it hides it

2023-01-19 21:08 UTC, luthfib commented on src/components/content/conditions/patient-conditions.scss
> +  .ctw-tab-underline-hover {
This could be changed to `.ctw-tab-underline`

2023-01-19 21:15 UTC, luthfib commented on src/components/content/conditions/patient-conditions-tabs.tsx
> +                    : "ctw-tab-underline-hover ctw-tab ctw-relative ctw-space-x-2"
This is a bit confusing. I think this could be improved by always applying the common classes. `ctw-tab-underline-hover ctw-tab ctw-relative`. Im curious as to why `ctw-space-x-2` is needed when selected by not when selected?

2023-01-19 21:15 UTC, luthfib submitted a review, later dismissed
Looking good, however still some changes around cx

2023-01-20 17:01 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions-tabs.tsx
> +  function blurClicked() {
Add a link to the issue that explains why this is needed.

2023-01-20 17:51 UTC, WesleyKapow requested changes

2023-01-20 17:51 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions-tabs.tsx
> +  function blurClicked() {
Add a link to the issue that explains why this is needed.

2023-01-20 17:51 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions-tabs.tsx
> +    if (document.activeElement) {
```suggestion
    // Guard against server side where document isn't defined.
    if (document) {
```

2023-01-20 17:51 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions-tabs.tsx
> +  function blurClicked() {
ugh sorry, can you also add a comment summarizing the issue and why this is needed, that way fellow devs will know from just the code and can follow the link if they want to learn or explore the issue more.

2023-01-20 17:51 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions-tabs.tsx
> +              onClick={() => blurClicked()}
No need to wrap this in a function.

2023-01-20 18:43 UTC, pmadria3 commented on src/components/content/conditions/patient-conditions-tabs.tsx
> +    if (document.activeElement) {
Had to add an eslint-disable because it was always truthy in this case

2023-01-20 19:46 UTC, mrosata commented on src/components/content/conditions/patient-conditions-tabs.tsx
> +    if (document) {
```suggestion
    if (typeof document !== "undefined") {
```

2023-01-20 19:51 UTC, mrosata commented on src/components/content/conditions/patient-conditions-tabs.tsx
> +              onClick={blurClicked}
Is this going to work with keyboard nav or would it be better just to call `blurClick` above in onChange as well?

2023-01-20 19:58 UTC, pmadria3 commented on src/components/content/conditions/patient-conditions-tabs.tsx
> +              onClick={blurClicked}
Yep so this works with the keyboard nav using `onClick` but `onChange` it doesn't seem to toggle back

2023-01-20 20:39 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions-tabs.tsx
> +              onClick={blurClicked}
We specifically only want to call the blur function on click. That way we don't get the outline when you click but you will get it when tabbing (keyboard use).

2023-01-20 20:41 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions.scss
> +      @apply ctw-absolute ctw-left-0 -ctw-bottom-0 ctw-block ctw-h-0.5 ctw-w-full;
Negative bottom-0 is weird ya?

2023-01-20 20:41 UTC, WesleyKapow approved these changes

2023-01-20 20:47 UTC, pmadria3 commented on src/components/content/conditions/patient-conditions.scss
> +      @apply ctw-absolute ctw-left-0 -ctw-bottom-0 ctw-block ctw-h-0.5 ctw-w-full;
yeah but the bar seems to slid all the way up into the button if I remove it :( 
![Screenshot 2023-01-20 at 2 47 19 PM](https://user-images.githubusercontent.com/98342697/213802284-2694fede-71e2-44a0-84c1-aac4cdf65ebf.png)

With -0: 
![Screenshot 2023-01-20 at 2 47 44 PM](https://user-images.githubusercontent.com/98342697/213802357-389ddbe8-6336-42d8-984f-addb857341c6.png)

2023-01-20 21:10 UTC, merged