Ctw 319 embeddable add ability to pass list of styles to themes
zeus-health/ctw-component-library pull request #44
Opened 2022-09-02 16:43 UTC by melocule

[**Jira Ticket**](https://zeushealth.atlassian.net/jira/software/projects/CTW/boards/49?assignee=62c5970b1bb561c33795d8d6&selectedIssue=CTW-319)
> Healthie is going to need to be able to pass a styles down to our CTW Provider component with the overridable styles (These will override our tailwind config values).

**AC**
- Types around our overridable styles (see ctw-main-light as option in IDE)
- If possible keep the overridable styles in sync with what we pass to tailwind
_Note: Current best attempt is having a script that can be ran to sync the styles definitions with tailwind. Tried to have it always synced up by importing the config directly, but this would only check for correct CSS variable names at runtime-- live type checking only works for types that are literals ([see attempt to sync](https://github.com/zeus-health/ctw-component-library/commit/22982ba18616f2701b90d0c14ed62cb0a51a8418))_

**Result**
What the client would see:
<img width="1005" alt="Pasted Graphic 5" src="https://user-images.githubusercontent.com/33408946/188198148-522605e0-e27f-433e-8362-c62b7fe41591.png">
Impact of the above style setting :
<img width="1069" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/33408946/188198195-41e87800-e871-4058-9105-6ad26c01703a.png">
Removal of the style setting (what it looked like before):
<img width="1067" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/33408946/188198250-189d87e4-d4e6-4c6b-a675-b8d42d8c0b42.png">

2022-09-02 20:25 UTC, WesleyKapow requested changes
I've got a few concerns with this current approach:
1. Generated files should clearly be generated. In this case the file exists within src/styles and should have a big fat comment at the top saying DO NOT EDIT, THIS IS GENERATED, and a pointer for how to re-generate it.
2. `--ctw--primary-light` and the like are kinda ugly theme names. We don't need the prefix for these when passing it into the provider. Instead, we should have `primaryLight`.
3. I think we can tweak how `CSSColorPalette` is setup to avoid the need for the `sync-style` script. How about this, change the object in `tailwind.config.cjs` to be a flat map of colors.

```ts
export const CSSColorPalette = {
  colors: {
    transparent: "transparent",
    white: "#fff",
    black: "#000",
    primaryLighter: "#FAF5FF",
    primaryLight: "#F3E8FF",
    primaryMain: "#4990E2",
    primaryDark: "#577FE6",
    iconDefault: "#374151",
  },
};
```

Then our type can be:
```ts
export type Theme = Partial<Record<keyof typeof CSSColorPalette['colors'], string>>
```

That should yield a type called `Theme` that looks like:

```ts
type Theme = {
    transparent?: string | undefined;
    white?: string | undefined;
    black?: string | undefined;
    primaryLighter?: string | undefined;
    ...
}
```

You'll then need to at runtime process the passed in object to construct the correct `--ctw--` CSS variables. You can use `kebabCase` from lodash to help here -- https://lodash.com/docs/4.17.15#kebabCase

2022-09-02 20:25 UTC, WesleyKapow commented on src/components/core/ctw-provider.tsx
> +    <div style={style as React.CSSProperties}>
Exported style should already be cast to what is needed. That way any consumer importing it already has the right type (and so multiple consumers won't have to cast it each time).

2022-09-06 14:08 UTC, melocule commented
Fresh attempt to import the Theme object from tailwind.config.cjs:
Still no live type checking, the .cjs file requires the .d.ts to declare it as a module. With or without specifying the type of the Theme object in the .d.ts file, live type checking doesn't work in App.tsx. It would work if the type were set literally in the .d.ts file, but that leads to the syncing issue again.

2022-09-07 13:14 UTC, WesleyKapow requested changes
Lookin' REALLY good!!

2022-09-07 13:14 UTC, WesleyKapow commented on src/components/core/ctw-provider.tsx
> +  theme?: any;
Why `theme` and `style`? Let's go with just `theme` and change the type to be called `Theme` as well.

2022-09-07 13:14 UTC, WesleyKapow commented on tailwind.config.cjs
> +  require("./tailwind-gen.theme.cjs").addCSSVarReference;
Require the file once and use destructuring to get the three things you want from it.

2022-09-07 13:14 UTC, WesleyKapow commented on src/styles/tailwind.theme.ts
> +export function mapToCSSVar(colorConfig: Style): any {
Anyway to DRY this function up with the `addCSSVarReference` function?

2022-09-07 13:14 UTC, WesleyKapow commented on src/styles/tailwind.theme.ts
> +export type Style = Subset<typeof TailwindTheme["colors"]>;
This is awesome! Really really awesome!

2022-09-07 13:14 UTC, WesleyKapow commented on .gitignore
> +.DS_Store
The `mv` command shouldn't fail but just in case, add the `tailwind.theme.js` file as well.

2022-09-07 13:21 UTC, WesleyKapow commented on tailwind.config.cjs
> +const ThemeUtil = require("./tailwind-gen.theme.cjs");
Better to use destructuring to make it clear what things you are using from the imported file.

2022-09-07 13:25 UTC, melocule commented on src/styles/tailwind.theme.ts
> +export function mapToCSSVar(colorConfig: Style): any {
Revised this function when I removed calls to createCSSVar, this should be fixed at this commit too
<img width="585" alt="image" src="https://user-images.githubusercontent.com/33408946/188889459-1d2b170a-d9e2-4951-bbb2-62defa329845.png">

2022-09-07 13:34 UTC, WesleyKapow approved these changes
LGTM

2022-09-07 13:37 UTC, melocule commented
Tysm for your help Wesley!

2022-09-07 13:40 UTC, merged