Ctw 282/add meatball menu to conditions
zeus-health/ctw-component-library pull request #45
Opened 2022-09-06 13:36 UTC by luthfib

Adds dropdown menu and ellipses action button and provisionally opens the same drawer for now. Next stories that create those drawers should handle open the appropriate drawers. 

**Potential fixes**: Centering the menu and arrow to go in the middle of the ellipses button

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/16874444/188648863-b61e5595-ed4b-43c7-be15-c065d339df84.png">

2022-09-06 16:23 UTC, WesleyKapow requested changes

2022-09-06 16:23 UTC, WesleyKapow commented on src/components/core/table/table-rows.tsx
> +        <Fragment key={record.id}>
Fragment not needed. Can continue using `key` on the `tr` as before.

2022-09-06 16:23 UTC, WesleyKapow commented on src/components/core/table/table-rows.tsx
> +                  <DotsHorizontalIcon className="ctw-2-5 ctw-w-5 ctw-cursor-pointer" />
What's `ctw-2-5`?

2022-09-06 16:23 UTC, WesleyKapow commented on src/components/core/dropdown-menu.tsx
> +                        "group ctw-flex ctw-w-full ctw-items-center ctw-border-none ctw-bg-transparent ctw-py-2 ctw-px-2 ctw-text-content-black",
Should be `ctw-group`? Maybe not even needed.

2022-09-06 16:28 UTC, luthfib commented on src/components/core/table/table.tsx
> +              ellipsesMenuAction && showRightTableBorderShadow,
Ahh good catch. It should actually be !ellipsesMenuAction && showRightTableBorderShadow. The idea being that overall table shadow on the right should only show if ellipsesMenuAction is not defined.

2022-09-07 13:47 UTC, WesleyKapow requested changes

2022-09-07 13:47 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> -              ]}
This table will definitely have rowActions.. also important to keep the columns the same between the two tables for alignment purposes.

2022-09-07 13:47 UTC, WesleyKapow commented on src/components/core/dropdown-menu.tsx
> +        <Menu.Button className="ctw-cursor-pointer ctw-border-none ctw-bg-transparent">
Use `ctw-btn-clear` instead.

2022-09-07 13:47 UTC, WesleyKapow commented on .changeset/perfect-points-own.md
> +Remove unused conditions table export
This doesn't capture the changes here.

2022-09-07 15:02 UTC, WesleyKapow requested changes

2022-09-07 15:28 UTC, WesleyKapow commented on src/components/core/dropdown-menu.tsx
> +        <Menu.Button className="ctw-btn-clear ctw-cursor-pointer ctw-border-none ctw-text-primary-dark hover:ctw-text-primary-main">
`"ctw-btn-clear ctw-link"` is all you need.

2022-09-07 15:33 UTC, luthfib commented on src/components/core/dropdown-menu.tsx
> +        <Menu.Button className="ctw-btn-clear ctw-cursor-pointer ctw-border-none ctw-text-primary-dark hover:ctw-text-primary-main">
Not sure why its showing the diff wrong but I have `ctw-btn-clear ctw-link` now only here. Shows up correctly in the code changes tab

2022-09-07 15:44 UTC, WesleyKapow approved these changes
LGTM

2022-09-07 15:45 UTC, merged