Add date parsing
zeus-health/ctw-component-library pull request #450
Opened 2023-02-02 17:02 UTC by pmadria3

This fixes the date parsing for last retrieved date.

2023-02-02 18:18 UTC, WesleyKapow approved these changes

2023-02-02 18:18 UTC, WesleyKapow commented
Add changeset for patch?

2023-02-03 21:50 UTC, luthfib commented on .changeset/little-cars-brush.md
> +Update usePatientHistory to use patientHistoryDetails and fix date.
More context around this would be good

2023-02-03 22:14 UTC, WesleyKapow requested changes

2023-02-03 22:14 UTC, WesleyKapow commented on src/components/content/patient-history/use-patient-history.tsx
> +    dateCreated: patientHistoryDetails?.dateCreated,
The keys here are what is exposed to customers. How about: `lastRetrievedAt`, `latestStatus`, `lastRequestedAt` ?

2023-02-06 15:23 UTC, luthfib approved these changes

2023-02-06 15:23 UTC, merged