Ctw 840/condition 2.0 patient history fixes
zeus-health/ctw-component-library pull request #583
Opened 2023-03-14 19:25 UTC by luthfib

Request records now appears in empty table state when patient has never made request to patient history api. Adds ability to pass loading state to PatientConditionsBase. Export last retrieved date so we can use it outside of conditions 2.0. 

<img width="991" alt="Screenshot 2023-03-14 at 2 08 42 PM" src="https://user-images.githubusercontent.com/16874444/225115176-802378c2-bba6-491f-852d-207966125d17.png">

2023-03-15 16:24 UTC, WesleyKapow requested changes
Looks like `usePatientHistory` should already provide the `lastRetrievedAt`. Could you simplify this by just using that existing hook and maybe add an `isLoading` to it?

I don't think we need `PatientHistoryLastRetrieved` as that just wraps the header-message with a check.. we can do that ourselves.

`useShowPatientHistoryRequestButton` is probably not needed either as we want to construct our empty message with the request records button IF there is no `lastRetrievedAt` which we can get from `usePatientHistory`.

2023-03-15 16:24 UTC, WesleyKapow commented on src/components/content/patient-history/patient-history-action.tsx
> +      {!hideRequestRecords && !showRequestRecordsRequestButtonQuery.data && (
I think we always want to show the request records button unless `hideRequestRecords`. As in, we shouldn't hide it when there's data. We want to provide a way for them to request it again.

2023-03-15 16:24 UTC, WesleyKapow commented on src/components/content/patient-history/use-patient-history.tsx
> +    data:
This looks more like a bool than a set of data. What should this be named?

2023-03-15 16:24 UTC, WesleyKapow commented on src/components/content/patient-history/use-patient-history.tsx
> +export function useShowPatientHistoryRequestButton() {
The name is tied to its use but what is this really? What information is this providing / what do we want it to provide?

2023-03-20 20:26 UTC, WesleyKapow requested changes

2023-03-20 20:26 UTC, WesleyKapow commented on src/components/content/patient-history/use-patient-history.tsx
> +  const query = usePatientConditionsOutside();
This makes it conditions specific and thus should not be in the general `patient-history` area.

2023-03-20 20:26 UTC, WesleyKapow commented on src/components/content/patient-history/patient-history-action.tsx
> +        !showRequestRecordsRequestButtonQuery.hasNoOutsideData && (
What if instead, you rely on consumers to specify `hideRequestRecords` depending if there's data or not?

2023-03-20 20:26 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions-outside.tsx
> +  const emptyMessage = showRequestRecordsRequestButtonQuery.hasNoOutsideData ? (
Can this instead be based on `usePatientHistory` somehow? We know we won't have any outside records because this is for `emptyMessage`, so we only want to customize the empty message if we have never requested patient history before (do I have that right?).

2023-03-20 20:26 UTC, WesleyKapow commented on src/components/content/patient-history/patient-history-last-retrieved.tsx
> +export const PatientHistoryLastRetrieved = () => {
This is only used in one place, is it really needed?

2023-03-20 21:06 UTC, luthfib commented on src/components/content/patient-history/patient-history-last-retrieved.tsx
> +export const PatientHistoryLastRetrieved = () => {
We need to export this because this will be used by consumers?

2023-03-20 21:08 UTC, luthfib commented on src/components/content/patient-history/patient-history-action.tsx
> +        !showRequestRecordsRequestButtonQuery.hasNoOutsideData && (
Not sure I follow here... There are two scenarios. One if consumers just want to flat out hide request records and the other is if we want to hide it conditionally based on the logic above. Not sure how that fits both use cases, but maybe I am missing something.

2023-03-20 21:19 UTC, WesleyKapow commented on src/components/content/patient-history/patient-history-last-retrieved.tsx
> +export const PatientHistoryLastRetrieved = () => {
Why not have consumer use `usePatientHistory` and then `{patientHistory.lastRetrievedAt && <div>Last Retrieved {patientHistory.lastRetrievedAt}</div>`.. guess there's `formatISODateStringToDate` being used by `PatientHistoryTableHeaderMessage`, but that's simple enough too. We probably don't need this component nor `PatientHistoryTableHeaderMessage` (which looks outdated.. it has a switch on status and renders the same thing regardless of the status).

2023-03-20 21:24 UTC, WesleyKapow commented on src/components/content/patient-history/patient-history-last-retrieved.tsx
> +export const PatientHistoryLastRetrieved = () => {
(I'm trying to keep things simple.. `usePatientHistory` is a hook that already provides patient history details that consumers should need. We don't then need simple components that show parts of these details.)

2023-03-20 21:26 UTC, luthfib commented on src/components/content/patient-history/patient-history-last-retrieved.tsx
> +export const PatientHistoryLastRetrieved = () => {
Sounds more complicated to me, and more code for the consumer. But if we want to avoid exporting something else I can go that route.

2023-03-20 21:37 UTC, WesleyKapow commented on src/components/content/patient-history/patient-history-last-retrieved.tsx
> +export const PatientHistoryLastRetrieved = () => {
I think you can roll `formatISODateStringToDate` into `usePatientHistory` so that `lastRetrievedAt` uses that formatted date. I don't think we use the date as a date elsewhere.

I think it keeps things simpler.. sure it's a little more code for the consumer.. but it's one conditional.

That said, we do have the `RequestRecordsButton`.. it's doing a little bit more but also fairly simple. I'm ok with keeping this lastRetrieved component but maybe kill off the `PatientHistoryTableHeaderMessage` component?

2023-03-20 21:38 UTC, luthfib commented on src/components/content/patient-history/patient-history-last-retrieved.tsx
> +export const PatientHistoryLastRetrieved = () => {
Sounds good.

2023-03-21 16:31 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions-outside.tsx
> +        (hideRequestRecords &&
Should probably be an `||`. Hide it under any of these circumstances.

2023-03-21 16:44 UTC, WesleyKapow approved these changes

2023-03-21 18:14 UTC, merged