Ctw 848/zap scrolling on overflow
zeus-health/ctw-component-library pull request #592
Opened 2023-03-17 17:06 UTC by mrosata

### ScrollableContainer and ScrollableContent

https://www.loom.com/share/8187df91f0b34ddb967849fe538cf32c

Problem: While adding scrollbars to an element is fairly simple, adding scrollbars to a nest container can be very nuanced. This is because scrollbars are only added when an element grows past a dimension of its parent. If we have nested elements `A -> B -> C` and want `C` to scroll when a dimension of `B + C > A`, then we need 
- To have a fixed height of `A`
- To have `B + C` able to grow to fill the space of `A`
- To add `overflow: scrollbar` to `C`

Now with more nesting `A -> B1 -> B2 -> BN -> C`, we need to similarly for CSS to be able to know when the nested content has outgrown `A` so it can put scrollbars on `C`. Here's an image with all the nested containers from `A -> ... -> C` in the zus-aggregated-profile. Notice, the outlines are only on elements that both descendants of `A` and ancestors of `C`, we don't care about children of `B` that aren't also descendants of `C`.

<img width="1233" alt="Screen Shot 2023-03-17 at 10 41 24 AM" src="https://user-images.githubusercontent.com/6380075/225936800-7e153e22-1697-409f-8b69-a918edcb65fd.png">

Now in this image we are saying to ZAP, that collectively all its content shouldn't outgrow 500px, and the inner table grows to the max size it can within that bound before growing scrollbars.
```tsx
  <ZusAggregatedProfile
    height="500px"
    resources={["observations-outside", "observations"]}
    title="Observations"
  />
```

It would be very messy to track this by classname in each component using it. So this PR introduces a couple helper containers (`ScrollableContainer` and `ScrollableContent`). These containers are just `div` tags, they are robust and accept any props a `div` normally takes (even refs). Here's how they work in practice:

```tsx
<ScrollableContainer height={height}>
  <div>
    <h1>I am a title</h2>
  </div>
  <ScrollableContainer>
    <div>Random content</div>
    
    <ScrollableContent>
       <table>
         {/* A large table */}
       </table>
    </ScrollableContent>
    
    <div>Random content</div>
  </ScrollableContainer>
</ScrollableContainer> 
```

If we need a `ScrollableContainer` or `ScrollableContent` to be able to not scroll (ie: one EHR wants scrollbars and another doesn't), we would just pass scrollingEnabled as false and height as undefined. In this example I didn't use variables for easy viewing:

```tsx
<ScrollableContainer height={undefined} scrollingEnabled={false}>
  <div>
    <h1>I am a title</h2>
  </div>
  <ScrollableContainer  scrollingEnabled={false}>
    <div>Random content</div>
    
    <ScrollableContent scrollingEnabled={false}>
       <table>
         {/* A large table */}
       </table>
    </ScrollableContent>
    
    <div>Random content</div>
  </ScrollableContainer>
</ScrollableContainer> 
```

2023-03-17 20:10 UTC, luthfib approved these changes

2023-03-17 21:21 UTC, WesleyKapow commented
Please hold off on merging until we can discuss options on Monday!

2023-03-21 14:45 UTC, WesleyKapow requested changes

2023-03-21 14:45 UTC, WesleyKapow commented on src/components/content/zus-aggregated-profile/zus-aggregated-profile.stories.tsx
This scrolling functionality is very fragile as it depends on all divs having the right class. Therefore, we really need a test to ensure we don't break it!

2023-03-21 14:45 UTC, WesleyKapow commented on src/components/content/observations/patient-observations-outside.tsx
> +    <div
I don't think this wrapper is needed and it deviates from how conditions is setup.

2023-03-21 14:45 UTC, WesleyKapow commented on src/components/core/main.scss
> +  }
nit: Make these not nested. Typically nesting is used for nested selectors and not as a way to DRY up class names. The main issue is it makes these class names harder to grep/find.

2023-03-21 15:20 UTC, mrosata commented on src/components/content/zus-aggregated-profile/zus-aggregated-profile.stories.tsx
> +        <style>{".ctw-zus-aggregated-profile { height: 450px }"}</style>
This is for customers/consumers using our Storybook. To illustrate they need to set a height on that component I wanted to use a language everyone understands (CSS) rather than tailwind.

2023-03-21 15:46 UTC, merged