Ctw 826/patient history index
zeus-health/ctw-component-library pull request #603
Opened 2023-03-22 13:12 UTC by luthfib

Create POC table of patients who have made patient history requests.

2023-03-22 13:57 UTC, WesleyKapow commented on src/components/content/patient-history/use-patient-history.tsx
> +export function useBuilderPatientHistoryList(
Maybe pull this and helper function out into new file `use-builder-patient-history-list.ts`.

Also in general I try to keep helper functions below the exports. That way it's easier to jump in to a file and see what the main responsibilities are.

2023-04-03 14:43 UTC, mrosata commented on src/components/content/patient-history/patient-history-table.tsx
> +  "PatientsTable"
```suggestion
  "PatientsHistoryTable"
```

2023-04-05 14:03 UTC, eric-gunther requested changes
Very excited about this feature! Concerned about pagination and performance of the patient history API, I don't think we need to get it perfect on the first try but at least would be good to have some safety checks in place to avoid requesting too much data.

2023-04-05 14:03 UTC, eric-gunther commented on src/fhir/models/patient-history.ts
> +}
It feels strange to me that this model would extend the FHIR model. Patient history requests are a Zus specific thing that really have nothing to do with FHIR. I get that you're extending `FHIRModel<PatientModel>` in order to acquire the name getters, but I wonder if it makes more sense to have a simpler model here since you're constructing these models in `use-builder-patient-history-list.ts` anyway. I don't feel strongly about this, curious if you have thoughts to justify either way.

I just imagine as we build more admin functionality it's unlikely that everything is going to keep extending these fairly large FHIR models.

2023-04-05 14:26 UTC, luthfib commented on src/fhir/models/patient-history.ts
> +}
Good point. I think it would make more sense to have this perhaps take a patient model and the history info

2023-04-10 16:51 UTC, bryanjknight reviewed
LGTM but probably need a original dev to approve. Also a good exercise for me to see what I missed in a given PR

2023-04-10 16:57 UTC, eric-gunther submitted a review, later dismissed

2023-04-10 16:57 UTC, eric-gunther commented on src/fhir/models/patient-history.ts
> +  kind = "PatientHistorytModel" as const;
I'm assuming this is a typo, right?

2023-04-10 16:58 UTC, pmadria3 commented on src/services/patient-history/patient-history-types.ts
> +  | "error";
also there is a "done-with-error" state as well right?

2023-04-10 16:59 UTC, luthfib commented on src/fhir/models/patient-history.ts
> +    // eslint-disable-next-line no-underscore-dangle
We do, the table uses it

2023-04-10 17:00 UTC, pmadria3 commented on src/components/content/conditions/story-helpers/mocks/patient-history-message.ts
> -      _updatedAt: "2022-11-28T14:29:27.436Z",
was this meant to be deleted?

2023-04-10 17:00 UTC, pmadria3 requested changes
Looking good - just left a few comments 

Also do we need tests or followup?

2023-04-10 17:01 UTC, luthfib commented on src/fhir/formatters.ts
> +
Yeah, lets leave this one. The other one didnt quite work for the format I was using and this new one is a bit more flexible. If anything we could remove the old one by use by use case.

2023-04-10 17:02 UTC, luthfib commented on src/components/content/conditions/story-helpers/mocks/patient-history-message.ts
> -      _updatedAt: "2022-11-28T14:29:27.436Z",
Yes, it is not a field anymore

2023-04-10 17:04 UTC, luthfib commented on src/fhir/models/patient-history.ts
> +    // eslint-disable-next-line no-underscore-dangle
We do need it. Or else eslint complains

2023-04-10 17:55 UTC, pmadria3 approved these changes

2023-04-10 17:57 UTC, merged