Multi-resource timeline
zeus-health/ctw-component-library pull request #609
Opened 2023-03-23 20:27 UTC by eric-gunther

2023-03-24 14:38 UTC, WesleyKapow requested changes

2023-03-24 14:38 UTC, WesleyKapow commented on src/fhir/medications.ts
> +export async function getMedicationDispnseCommon(
typo, s/dispnse/dispense

2023-03-24 14:38 UTC, WesleyKapow commented on src/components/content/timeline-2.0/helpers/filters.ts
> +};
Sort goes in `sorts.ts`

2023-03-24 14:38 UTC, WesleyKapow commented on src/components/content/timeline-2.0/patient-timeline-columns.tsx
> +          ))}
Use of `row` is confusing here as we're dealing with tables. Maybe `detail` instead? (this aligns with a suggestion I had to rename `actor` to `actorDetails`).

2023-03-24 14:38 UTC, WesleyKapow commented on src/components/content/timeline-2.0/patient-timeline-columns.tsx
> +        <div>
extra div not needed

2023-03-24 14:38 UTC, WesleyKapow commented on src/components/content/timeline-2.0/patient-timeline.tsx
> +      <Table
Use `ResourceTable` instead. See conditions and observations for examples of what this should look like.

2023-03-24 14:38 UTC, WesleyKapow commented on src/components/content/timeline-2.0/patient-timeline.tsx
> +        "ctw-scrollable-pass-through-height ctw-overflow-hidden"
`ctw-overflow-hidden` is redundant with what `ctw-scrollable-pass-through-height` provides.

2023-03-24 14:38 UTC, WesleyKapow commented on src/components/content/timeline-2.0/patient-timeline.tsx
> +          defaultState: defaultConditionFilters,
Should be default timeline filters.

2023-03-24 14:38 UTC, WesleyKapow commented on src/components/content/timeline-2.0/patient-timeline.tsx
> +        columns={patientTimelineColumns(true)}
you won't want to hardcode view fhir button to true

2023-03-24 14:38 UTC, WesleyKapow commented on src/components/content/timeline-2.0/patient-timeline.tsx
> +          if (record.model.constructor === EncounterModel) {
Use a switch statement on `record.model.resourceType`

2023-03-24 14:38 UTC, WesleyKapow commented on src/components/content/timeline-2.0/patient-timeline.tsx
> +  return <></>;
Pull out into a helper file.

2023-03-24 14:38 UTC, WesleyKapow commented on src/components/content/timeline/patient-timeline.tsx
> +export function usePatientEncounterDetailsDrawer() {
Move to new `timeline-2.0/helpers/modal-hooks.ts` (to align with conditions)

2023-03-24 14:38 UTC, WesleyKapow commented on src/hooks/use-medications.ts
Remove or cleanup copypasta comments :P

2023-03-24 14:38 UTC, WesleyKapow commented on src/fhir/medications.ts
Functions that fetch a list of resources should be plural, so `getMedicationRequestsCommon` or maybe `getCommonMedicationRequests`, etc.

2023-03-24 14:38 UTC, WesleyKapow commented on src/fhir/medications.ts
> +    throw errorResponse("Failed fetching medications for patient", e);
Be more specific, "fetching medication requests" -- same goes for other copypasta

2023-03-24 17:16 UTC, WesleyKapow requested changes

2023-03-24 17:16 UTC, WesleyKapow commented on src/components/content/conditions/helpers/sorts.ts
> +];
This file is for conditions, move these to `timeline-2.0/helpers/sorts.ts`

2023-03-24 17:16 UTC, WesleyKapow commented on src/fhir/medications.ts
>  export async function getMedicationStatement(
`getMedicationStatements`

2023-03-24 17:16 UTC, WesleyKapow commented on src/fhir/timeline-event.ts
>      patientEncountersQuery.data,
How about `queries.map(q => q.data)`?

2023-03-28 19:13 UTC, luthfib commented on src/App.tsx
> +  // { render: () => <PatientSearch />, title: "Patient Search" },
Can you uncomment?

2023-03-28 19:14 UTC, luthfib commented on src/components/content/timeline-2.0/helpers/medication-detail.tsx
> +};
Could probaly move this to src/components/content/timeline-2.0/helpers/modal-hooks.tsx

2023-03-28 19:22 UTC, luthfib submitted a review, later dismissed
LGTM

2023-03-28 19:27 UTC, luthfib approved these changes

2023-03-28 19:55 UTC, WesleyKapow approved these changes

2023-03-28 19:55 UTC, WesleyKapow commented on src/components/content/timeline-2.0/helpers/modal-hooks.tsx
> +  return <></>;
You can `return null` in these cases.

2023-03-28 19:57 UTC, luthfib approved these changes

2023-03-28 20:03 UTC, mrosata approved these changes

2023-03-28 20:04 UTC, merged