Ctw 748/allergies update
zeus-health/ctw-component-library pull request #620
Opened 2023-03-31 03:14 UTC by pmadria3

Still need to iron out some details 

![Screenshot 2023-03-30 at 10 14 29 PM](https://user-images.githubusercontent.com/98342697/229013763-10cf0c05-c03e-49d1-9700-1057cb8ae262.png)

2023-04-04 00:56 UTC, eric-gunther requested changes

2023-04-04 00:56 UTC, eric-gunther commented on src/components/content/allergies/allergies-filter.tsx
> +  allergy.knownCodings,
The ticket AC says to de-dupe by code, preferring RxNorm over NDC over SNOMED, using the display value. So I think simply de-duping on `allergy.display` was correct, but we'll want to adjust that getter (will provide that feedback in a comment on that area of the code).

2023-04-04 00:56 UTC, eric-gunther commented on src/App.tsx
> +  },
Non-blocking feedback, but this whole App.tsx is starting to get a bit messy again. Perhaps we could just use a single instance of `ZusAggregatedProfile` where folks can play around with the `resources` prop.

2023-04-04 00:56 UTC, eric-gunther commented on src/components/content/allergies/helpers/history.tsx
> +  // will only show themselves in the history.
Copy/paste comment still referencing conditions.

2023-04-04 00:56 UTC, eric-gunther commented on src/components/content/allergies/helpers/history.tsx
> +  }
You should investigate the performance of these queries by code in production, I suspect they are going to be slow (which I think I noticed for conditions already in prod).

2023-04-04 00:56 UTC, eric-gunther commented on src/components/content/allergies/helpers/history.tsx
> +];
These are the values to de-dupe on in the history, right? So I would expect this to include the date field and perhaps others.

2023-04-06 03:19 UTC, pmadria3 commented on src/components/content/allergies/patient-allergies.tsx
> +/* eslint-disable import/order */
eslint messed up in editor so had to add this - please can someone remove this

2023-04-06 03:20 UTC, pmadria3 commented on src/fhir/models/allergies.ts
> +/* eslint-disable import/order */
same as prev comment

2023-04-06 14:45 UTC, pmadria3 commented on src/App.tsx
> -  { render: () => <PatientTimelineV2 />, title: "Patient Timeline" },
Eric had a comment on it above - we can just do one instance and then pass the resource and use that

2023-04-06 14:47 UTC, luthfib approved these changes

2023-04-06 14:48 UTC, merged