[BUG] Loading State for Dismiss/Restore Buttons
zeus-health/ctw-component-library pull request #695
Opened 2023-05-02 21:01 UTC by Stephen-Tsen

When the dismiss/restore button is clicked for patient outside conditions and medications, the button shows a loading state and the add button is disabled until the action is complete.

- Create `useAction` hook to help with chaining callbacks
- Create `useToggleArchive` hook to help with providing input feedback to the user when the action is invoked
- Add styling for disabled primary and secondary buttons
- Update the patient outside conditions and medications components to provide feedback to the user when the dismiss/restore buttons are clicked. When it is clicked, both the dismiss/restore and add buttons are disabled until the action is completed. If it is successful, then the query is invalidated a nd rerun

2023-05-02 21:07 UTC, Stephen-Tsen commented on src/i18n/index.ts
> +      "resource.unnamed": "unnamed {{resource}}",
Please let me know if it was intentionally spelled `unamed`

2023-05-02 21:38 UTC, Stephen-Tsen commented on src/fhir/basic.ts
> +    Telemetry.reportActionSuccess(profileAction);
This looked wrong to me...

2023-05-03 14:14 UTC, bryanjknight requested changes

2023-05-03 15:57 UTC, mrosata commented on src/components/content/hooks/use-toggle-archive.ts
> +  };
The `useAction` pattern seems nice. Does it offer a benefit over (in this case) just using the built in `.then` and `.finally`?
```suggestion
  const { getRequestContext } = useCTW();
  const [isLoading, setIsLoading] = useState<boolean>(false);

  const handleUpdateArchive = useCallback(async () => {
    setIsLoading(true);

    await toggleArchive(model, await getRequestContext())
      .then(() => queryClient.invalidateQueries([queryToInvalidate]))
      .finally(() => setIsLoading(false));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [model]);

  return {
    toggleArchive: handleUpdateArchive,
    isLoading,
  };
```

2023-05-03 17:37 UTC, Stephen-Tsen commented on src/components/content/conditions/patient-conditions-outside.tsx
> +  const archiveLabel = record.isArchived ? t("resourceTable.restore") : t("resourceTable.dismiss");
I have not. I'll update to using the `useBaseTranslations` hook

2023-05-03 17:45 UTC, eric-gunther commented on src/i18n/index.ts
> +      "resource.unnamed": "unnamed {{resource}}",
Elation isn't specifically setting an override for the string we display when a resource doesn't have a display value. They just use the glossary object to set overrides for `condition_one` and `condition_other` (the plural). I don't think this merits a formal deprecation or any real communication, I'd just fix the typo and call it a day.

2023-05-03 17:46 UTC, bryanjknight commented on src/i18n/index.ts
> +      "resource.unnamed": "unnamed {{resource}}",
@eric-gunther is there any way for us to gauge what is being used across the EHR integrations when we need to rename other things?

2023-05-03 18:29 UTC, pmadria3 commented on src/components/content/conditions/helpers/modal-hooks.tsx
>    return (condition: ConditionModel, onDelete?: (condition: ConditionModel) => void) => {
This is just an other comment - need changeset. You can add one by doing `npx changeset` and then probably a minor in this case.

2023-05-03 20:15 UTC, Stephen-Tsen commented on src/fhir/basic.ts
> -    await queryClient.invalidateQueries(queriesToInvalidate);
This was moved to `useToggleArchive` because invalidating the query can cause the component (row in the table) to be unmounted before the update to remove the spinner causing a react error.

2023-05-15 14:10 UTC, WesleyKapow approved these changes
Really great work here! Using this minor review as a PING, what's going on with this PR? 2 weeks old!? Let's get this in!

2023-05-15 14:10 UTC, WesleyKapow commented on src/components/content/hooks/use-toggle-archive.ts
> +    toggleArchive(model, await getRequestContext()).then(
nit: favor using async/await and not `.then`.

2023-05-15 14:10 UTC, WesleyKapow commented on src/components/content/medications/patient-medications-outside.tsx
>        </button>
Could refactor this into a re-usable component to DRY things up.

2023-05-16 20:07 UTC, Stephen-Tsen commented on src/components/content/hooks/use-toggle-archive.ts
> +    toggleArchive(model, await getRequestContext()).then(
I didn't want to invalidate the query if the toggle failed, hence why there's the success and failure functions that are ever so slighly different.

2023-05-16 20:08 UTC, Stephen-Tsen commented on src/components/content/medications/patient-medications-outside.tsx
>        </button>
I started down that path but do not remember why I reverted to this...

2023-05-16 20:22 UTC, merged