CTW-691: Rewire Conditions query for table to FQS
zeus-health/ctw-component-library pull request #749
Opened 2023-05-18 15:30 UTC by patrickvalle

https://zeushealth.atlassian.net/browse/CTW-691

2023-05-18 15:34 UTC, Stephen-Tsen commented on src/App.tsx
> +      "zap.tabs.conditionsOutside": "Outside Conditions",
`conditions`?

2023-05-18 15:57 UTC, Stephen-Tsen commented on src/fhir/conditions.ts
> +        const graphClient = createGraphClient(requestContext);
Can we add this to `getRequestContext` like we have for `fhirClient`?

2023-05-22 20:52 UTC, patrickvalle commented on src/services/fqs/conditions.ts
> +  const basicQuery = useBasic();
@WesleyKapow I know we talked about having the `Basic` logic get married to the `Condition` logic at the component level vs in this `fqs` namespace, but this just felt like the easiest/better place to put the logic given the current structure of things. Curious on your thoughts here, if this is totally revolting or not.

2023-05-24 13:56 UTC, patrickvalle commented on src/fhir/models/condition.ts
> +  get patientOrganizationName(): string | undefined {
Reduced the scope of this getter to return only the field needed by the app- this makes tracking what graphql properties we're actually using in the view way easier

2023-05-24 14:18 UTC, luthfib commented on src/services/fqs/conditions.ts
> +}
Couple of things here...

1. I think this is a big large codewise to use ternary and it makes it hard to read
2. We are repeating a lot of logic between FQS and ODS. I think what would make more sense it to wrap the fetching for each in a function and handle the error part and histogram part right after the fetch. Soo might look kinda like...

```
withTimerMetric(async (requestContext, patient) => {
  try {
      const results = enableFQS ? fetchFQSConditions : fetchODSConditions
      Telemetry.histogramMetric("req.count.builder_conditions", results.length);
      return results;
  } catch (e) {
            throw Telemetry.logError(
              e as Error,
              `Failed fetching conditions for patient: ${patient.UPID}`
            );
          }
        }, "req.timing.builder_conditions")
}
```

2023-05-24 14:20 UTC, luthfib requested changes
Left some comments on potential changes

2023-05-24 14:20 UTC, mrosata commented on src/services/conditions.ts
> +  );
I wouldn't do this like
```ts
enableFQS ?
  withTimerMetric(/**/, "req.timing.summary_conditions.fqs") :
  withTimerMetric(/**/, "req.timing.summary_conditions") :
```
I'd do it all in one `withTimerMetric`. You could still use different metric names.. though I probably wouldn't use different metric names either. Could tag the metric with `fqs` tho to be able to filter it out

2023-05-24 14:22 UTC, mrosata commented on src/services/conditions.ts
> +  );
Could write it like
```ts
withTimerMetric(async (requestContext, patient) => {
  if (enableFQS) {
    /* work work */
  } else {
    /* work work */
  }
}, "req.timing.summary_conditions", enableFQS ? ["fqs"] : [])
```

2023-05-24 14:38 UTC, WesleyKapow commented on src/fhir/basic.ts
> +      ? // FQS implementation
nit: Comments like this = a sign you should pull things out to helper functions (I like to put non-exported helper functions below all of the exported functions to make it easier to see in the file the API it exposes [the exports]).

2023-05-24 14:38 UTC, WesleyKapow commented on src/fhir/basic.ts
> +      : // ODS implementation (noop)
What's not obvious here is why do we do a no-op here in this case.

2023-05-24 14:38 UTC, WesleyKapow commented on src/fhir/models/condition.ts
> +} from "@/services/conditions";
Things like `ClinicalStatus` and `VerificationStatus` seem very much like FHIR things and not some service thing.

2023-05-24 14:38 UTC, WesleyKapow commented on src/services/conditions.ts
> +export const CONDITION_CODE_PREFERENCE_ORDER: CodePreference[] = [
Check usage of this, maybe this belongs in the model?

2023-05-24 14:38 UTC, WesleyKapow commented on src/services/fqs/conditions.ts
> +}
nit: Maybe belongs in `services/fqs/queries/condition.ts` or some other file under `services/fqs`.

The thinking here is, this is specific to FQS.

2023-05-24 14:38 UTC, WesleyKapow commented on src/services/fqs/conditions.ts
> +}
nit: Looks like a FHIR thing, so probably `fhir/conditionsts`

2023-05-24 14:39 UTC, patrickvalle commented on src/fhir/basic.ts
> +}
When we're hitting ODS, the `Basic` resources get `_revincluded` in that request and filtered out already in `usePatientSummaryConditions`. We only need to independently fetch `Basic` like this when we're hitting FQS.

2023-05-24 14:46 UTC, patrickvalle commented on src/services/conditions.ts
IMO a "service" has business logic pertaining to a specific part of the domain and is responsible for orchestrating API calls- so the concept of a "conditions service" exists regardless of the backend(s) it's using. That way when your backend needs evolve, you're not constantly refactoring where your code lives. 

To me something like a "helper" feels super generalized and is, at best, a place to park functions that get called from multiple parts of the app (components, services, etc)... and at worst, anemic code you can't figure out a better home for.

2023-05-24 14:59 UTC, patrickvalle commented on src/fhir/basic.ts
> +export function useBasic(enableFQS: boolean) {
@mrosata @luthfib @WesleyKapow I moved the fetching into a helper function and added a comment attempting to explain the noop. LMK what you think

2023-05-24 17:17 UTC, patrickvalle commented on src/services/conditions.ts
> +export function usePatientBuilderConditions(enableFQS: boolean) {
Moved the fetch functionality into separate functions for `usePatientBuilderConditions` and `usePatientSummaryConditions`

2023-05-24 17:51 UTC, WesleyKapow requested changes

2023-05-24 17:51 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions-outside.tsx
> +    QUERY_KEY_BASIC
FYI when we are just using FQS, we won't need to invalidate `QUERY_KEY_OTHER_PROVIDER_CONDITIONS` anymore.

2023-05-24 17:51 UTC, WesleyKapow commented on src/components/content/hooks/use-toggle-archive.ts
> +    );
🚫 **BLOCKER**

`forEach` doesn't return a promise. Took some digging but I found an eslint rule we should have, please add this to `eslintrc.cjs` and verify this now shows you an error `"@typescript-eslint/await-thenable": "error",`

You should instead `await Promise.all()` and you can use `queriesToInvalidate.map` to get an array of promises from `invalidateQueries`.

2023-05-24 17:51 UTC, WesleyKapow commented on src/components/content/zus-aggregated-profile/zus-aggregated-profile-tabs.tsx
> +        <PatientConditionsOutsideBadge {...{ enableFQS: props.enableFQS }} />
```suggestion
        <PatientConditionsOutsideBadge enableFQS={props.enableFQS} />
```

2023-05-24 17:53 UTC, WesleyKapow commented on src/components/content/hooks/use-toggle-archive.ts
> +    );
Oh or maybe simply `await queryClient.invalidateQueries(queriesToInvalidate)`

2023-05-24 19:33 UTC, patrickvalle commented on src/components/content/hooks/use-toggle-archive.ts
> +    );
@WesleyKapow the eslint rule and `Promise.all` are pushed

2023-05-24 19:36 UTC, patrickvalle commented on src/components/content/conditions/patient-conditions-outside.tsx
> +    QUERY_KEY_BASIC
This is a good catch, but is there a non-heinous way to wire through `enableFQS` to the `RowActions`? If not, can I advocate for us to keep the code as-is since supporting both FQS and ODS should be a short-lived state?

2023-05-24 20:01 UTC, WesleyKapow commented on src/components/content/conditions/patient-conditions-outside.tsx
> +    QUERY_KEY_BASIC
I wasn't proposing a change, just noting that when we do switch to just FQS, this can get changed then.

2023-05-24 20:04 UTC, WesleyKapow approved these changes
LGTM, great work on this btw :D

2023-05-24 21:15 UTC, merged