Ctw 358/refetch condition when adding or editing
zeus-health/ctw-component-library pull request #77
Opened 2022-09-23 18:47 UTC by luthfib

- Adds React Query to enable refetching when adding or when refocusing on page.
- Fixes bug where date would crash if parser couldnt parse date
- Used ref to pass FHIR Client on advice of creator of react Query. A different approach was also given, in which we would write a custom hashing function for the keys that and then we would potentially hash the fhir client based on the auth header, that way we would know if the auth header had been updated and we would know that we have re calculate the key

2022-09-26 13:40 UTC, WesleyKapow requested changes

2022-09-26 13:40 UTC, WesleyKapow commented on .changeset/warm-dolls-shake.md
> +Refetches condition when adding new condition or adding condition from not reviewed. Additionally fixes bug when date editing condition and date is of bad format
Maybe typo here: "when date editing condition and date" .. probably remove first "date".

2022-09-26 13:40 UTC, WesleyKapow commented on src/fhir/formatters.ts
> +  }
Do you know what dates we are passing in that fail this? Should we be calling a different helper instead of `formatDateLocalToISO`?

2022-09-26 13:40 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +  // you passed as meta when the query was created which means it can be come stale
"can become stale."

Also, this will likely need to be done everywhere we do data fetching. A comment at each use isn't great. Instead see if you can refactor any of this to a helper. Something like `usefhirClientRef()` would be great. And then a description of why we use refs would go there.

2022-09-26 13:40 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +      meta: fhirClientRef as unknown as Record<string, unknown>,
These type casts seem wrong to me.

Meta is a map from string to unknown but you are trying to pass fhirClientRef directly to it, don't do this!

Instead try `meta: {fhirClientRef}` and then use it via `meta.fhirClientRef`.

2022-09-26 13:40 UTC, WesleyKapow commented on src/components/content/conditions.tsx
> +      }
Probably want to split and detect if confirmed OR reviewed have an error.

2022-09-26 13:40 UTC, WesleyKapow commented on src/fhir/conditions.ts
> +  }
Refactor / DRY

2022-09-26 13:42 UTC, WesleyKapow commented on src/components/content/forms/conditions.ts
> +  queryClient.invalidateQueries(["conditions"]);
Do edits work correctly? As in they don't need to invalidate anything and instead we correctly show the edited condition in the table?

2022-09-26 13:52 UTC, luthfib commented on src/fhir/formatters.ts
> +  }
the date comes in as `201911011338`. We could create another helper to call if we see a date in that format maybe?

2022-09-26 13:59 UTC, WesleyKapow commented on src/fhir/formatters.ts
> +  }
Well that looks like a valid dateTime to me. Can you:
1. Verify with team that we only want to show DATEs here and not also hh:mm?
2. Update this function to return dates when given dateTime strings.

2022-09-26 15:44 UTC, luthfib commented on src/components/content/conditions.tsx
> +      }
Do we want to display notReviewed if confirmed doesnt load? Because if confirmed doesnt load then we wouldnt want to incorrectly show lens conditions that were supposed to be filtered through the snomed, idc10 and other codes

2022-09-26 17:22 UTC, luthfib commented on src/components/content/forms/conditions.ts
> +  queryClient.invalidateQueries(["conditions"]);
Invalidating should be fine, because that will retrigger a refetch and it will update the table with the new edited info. We could also theoretically edit the table and not retrigger a refetch but not sure if that should be a v2

2022-09-26 19:00 UTC, WesleyKapow requested changes

2022-09-26 19:02 UTC, WesleyKapow commented on src/components/content/forms/conditions.ts
> +  queryClient.invalidateQueries(["conditions"]);
`invalidateQueries` is being called in just `createCondition` right? So how does it work for edit?

2022-09-27 12:36 UTC, luthfib commented on src/fhir/formatters.ts
> +    if (!(parsedDate instanceof Date && !Number.isNaN(parsedDate))) {
No, it just returns an invalid Date Object

2022-09-27 12:37 UTC, luthfib commented on src/fhir/utils.ts
> +  return { fhirClientRef };
Good point. Uneeded

2022-09-27 12:44 UTC, luthfib commented on src/fhir/formatters.ts
> +  if (typeof date !== "string") {
So we could check for `date instanceof Date` but technically that could be an invalid Date object, but theoretically our matchDatePattern function should guard against returning invalid dates

2022-09-27 13:04 UTC, luthfib commented on src/components/content/forms/conditions.ts
> +  queryClient.invalidateQueries(["conditions"]);
Renamed the function for clarity, that is my bad. Renamed to... createOrEditCondition, which is what it is actually doing.

2022-09-27 13:22 UTC, WesleyKapow approved these changes
nit about comment, otherwise LGTM

2022-09-27 13:22 UTC, WesleyKapow commented on src/fhir/utils.ts
> +// you passed as meta when the query was created which means it can be come stale
This is now a bit out of place, like what is meta here? How about something like:

> A reference to fhirClient is useful for things like useQuery where we pass it in as part of the meta data. This allows useQuery to always use a fresh copy of fhirClient (whatever the reference points to).

2022-09-27 13:39 UTC, WesleyKapow approved these changes

2022-09-27 13:46 UTC, luthfib commented
Looking into the error, might have been merge conflict errors

2022-09-27 13:56 UTC, WesleyKapow approved these changes

2022-09-27 13:57 UTC, merged