Ctw 1062/labs-fqs
zeus-health/ctw-component-library pull request #774
Opened 2023-05-30 14:26 UTC by pmadria3

This PR is in draft but almost wired up.

2023-06-02 11:03 UTC, patrickvalle commented on src/fhir/timeline-event.ts
> +  const diagnosticReportQuery = usePatientAllDiagnosticReports(true);
This shouldn't always be FQS, right?

2023-06-02 11:46 UTC, bryanjknight commented on src/fhir/timeline-event.ts
> +  const diagnosticReportQuery = usePatientAllDiagnosticReports(true);
It actually should be always be FQS because ODS has a bug that's not returning all observations

2023-06-02 14:57 UTC, pmadria3 commented on src/fhir/timeline-event.ts
> +  const diagnosticReportQuery = usePatientAllDiagnosticReports(true);
I added the toggle-able nature but set it to true

2023-06-05 15:18 UTC, bryanjknight requested changes
A few small blockers but hopefully nothing too crazy

2023-06-05 15:18 UTC, bryanjknight commented on src/App.tsx
Let's use the VITE_DEMO_COMPONENTS variable and stop changing the `App.tsx` file

2023-06-05 15:18 UTC, bryanjknight commented on src/components/content/timeline/patient-timeline.tsx
> +export function PatientTimeline({ className, enableFQS = false }: PatientTimelineProps) {
is this going to be a problem that we're defaulting to ODS as opposed to making this required?

2023-06-05 15:18 UTC, bryanjknight commented on src/fhir/fqs.ts
> +export const createGraphClient = (requestContext: CTWRequestContext) => {
Shouldn't this be `services/fqs/client.ts`?

2023-06-05 15:31 UTC, pmadria3 commented on src/components/content/timeline/patient-timeline.tsx
> +export function PatientTimeline({ className, enableFQS = false }: PatientTimelineProps) {
It is going to be for a little bit because the problem is FQS is running into errors on their side and thus we are not getting the correct results back atm (tested with a couple people in prod but sandbox works fine) so we need to default to false for the time being.

2023-06-05 15:37 UTC, bryanjknight commented on src/components/content/timeline/patient-timeline.tsx
> +export function PatientTimeline({ className, enableFQS = false }: PatientTimelineProps) {
Right, my concern is that we are creating a default value as opposed to failing if it's not configured (which I think guarantees that we tie all the components together)

2023-06-05 18:11 UTC, bryanjknight submitted a review, later dismissed

2023-06-05 20:41 UTC, bryanjknight submitted a review, later dismissed

2023-06-05 20:46 UTC, bryanjknight approved these changes

2023-06-05 20:47 UTC, merged