CTW-1186/onResourceSave optional callback
zeus-health/ctw-component-library pull request #793
Opened 2023-06-06 20:17 UTC by mrosata

This feature allows an optional callback function `onResourceSave` that providers can pass in from on the provider context. Whenever a resource gets created or edited in the function `createOrEditFHIRResource` the callback is fired. The backstory is that some providers wish to be notified in the frontend after a save or edit is performed so they can perform work as well.

The callback lives on the requestContext, this is mainly because the request context is being passed into the `createOrEditFHIRResource` function already and it is already a bit unwieldy expecting all those callers to get this context and pass it in, so having to update all those callers to additionally get this callback would be a bit cringe.

One thought, we could rename this `onCreateOrEditFHIRResource` as that function of a similar name is the only caller of this callback at the moment, however, `onResourceSave` feels better, matches the `onPatientSave` callback we already make available on the patient provider.

https://www.loom.com/share/447e1b60daaf446dbb080daba7003485

2023-06-07 15:31 UTC, mrosata commented on src/components/core/providers/ctw-provider.tsx
> +  onResourceSave?: OnResourceSaveCallback;
@WesleyKapow This PR addresses a need for an EHR embedding this library to perform work whenever a resource has been created or edited in ODS. This callback allows them to optionally hit their backend or refresh data in their own UI after the resource is saved.

The use-case we 100% want to support here is for a partner that is currently using the write-back data-loop to create resources via their API and would like to refresh relevant parts of their UI after a user has added a resource to the builder record in case their own data has been changed.

2023-06-07 15:32 UTC, WesleyKapow commented on src/components/core/providers/ctw-provider.tsx
> +  onResourceSave?: OnResourceSaveCallback;
And that's different from the ehr-hook because it's a front-end callback so they can update the UI as appose to JUST the data in their backend?

2023-06-08 16:53 UTC, WesleyKapow requested changes
LGTM, not approving yet as I think the `action: failure` is problematic and we should figure out what API we want here.

Also, I think `onResourceSave` is the right name, so good as is there!

2023-06-08 16:53 UTC, WesleyKapow commented on .changeset/few-lemons-peel.md
> +Add onResourceSave callback to CTWProvider context
```suggestion
Add onResourceSave callback to CTWProvider context which will get called anytime a resource is modified (edited or created).
```

2023-06-08 16:53 UTC, WesleyKapow commented on src/fhir/action-helper.ts
> +    action = "failure";
This prevents consumers of `onResourceSave` from knowing what the actual action was (create or update).

Trying to think through what a good API here would be. They should get the resource, action, and error? status? response?

2023-06-08 16:53 UTC, WesleyKapow commented on src/components/core/providers/patient-context.tsx
> +  onResourceSave?: (data: fhir4.Resource, action: "create" | "update") => void;
Thoughts on if we'll want this to be async so that we can `await onResourceSave(...)`? That way EHRs could update their state before we consider the operation complete. E.g. we'll wait for them to update their state BEFORE we close our form drawer.

2023-06-08 16:53 UTC, WesleyKapow commented on src/components/core/providers/use-ctw.ts
> +      },
nit: This is a little gross, alternatively you could make `onResourceSave` optional, and this would simply be:
```suggestion
      onResourceSave: context.onResourceSave,
```

Then callers would do `context.onResourceSave?.(resource, action)` to call it.

FYI, I don't have a strong opinion here.

2023-06-08 18:12 UTC, mrosata commented on src/fhir/action-helper.ts
> +    action = "failure";
good point I'll update

2023-06-08 18:18 UTC, mrosata commented on src/components/core/providers/patient-context.tsx
> +  onResourceSave?: (data: fhir4.Resource, action: "create" | "update") => void;
It should be fine for us to `await` a callback with type `() => void` regardless if it is async or not. If the type is void then the person writing the callback may write a sync or async function and return whatever they want from it iirc. Specifying `Promise<void>` forces them to write an async callback regardless if they need one or not.

2023-06-08 18:21 UTC, mrosata commented on src/components/core/providers/use-ctw.ts
> +      },
Yeah I want it to be optional for the consumers of the library but internally callers don't need to know whether the consumer actually implemented it or not, it's something the context provides always.

2023-06-08 18:32 UTC, mrosata commented on src/fhir/action-helper.ts
> +    action = "failure";
Updated it to just be `"create"|"update"` and a third argument of error is passed instead where it's undefined if the operation was successful
```tsx
  onResourceSave={(resource, operation, error) => {
    if (!error) {
      celebrateGoodTimesComeOn();
    }
  }}
```

2023-06-08 19:04 UTC, WesleyKapow commented on src/components/core/providers/patient-context.tsx
> +  onResourceSave?: (data: fhir4.Resource, action: "create" | "update") => void;
I just checked and you cannot `await` something that is not "thenable". How about this, go with what you have, and down the road if we want to `await`, we can change this type to be `void | Promise<void>` and then we can detect if we have a promise and await it otherwise do nothing.

2023-06-08 19:04 UTC, WesleyKapow approved these changes

2023-06-08 19:14 UTC, merged