WIP: CTW339-Stacked Card UI
zeus-health/ctw-component-library pull request #80
Opened 2022-09-27 02:19 UTC by pmadria3

This WIP PR is to setup the condition history with a preview card that has a details component card attached to it. Currently the card is showing up but the details and a bit of the styling need to be fixed.

2022-09-27 13:49 UTC, WesleyKapow requested changes
Few quick thoughts here:
1. It is unlikely we will want to use the preview separate from the detail. It may be simpler to have a single component for this.
2. We will want to use this component for more than just condition history. It'll be the same component for medication history, just showing different data. Can you generalize this? The generic components should be in `core` while any condition specific component should be in `content`.
3. `dl` should only be used if you are also going to use `dt` and `dd` (html semantic way for displaying data).

2022-09-27 13:49 UTC, WesleyKapow commented on src/App.tsx
> +    <CTWProvider env="sandbox" authToken={VITE_AUTH_TOKEN} theme={{}}>
Use dev :)

2022-09-27 13:49 UTC, WesleyKapow commented on package-lock.json
>        "dependencies": {
package-lock.json should not really get updated unless you update package.json

2022-09-29 14:16 UTC, pmadria3 commented
Still working on styling the preview card but the rest should be up for review

2022-09-29 17:09 UTC, WesleyKapow reviewed
Adding WIP comments as I g2g :D

2022-09-29 17:09 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +export const CollapsibleDataList = ({ entry }) => {
Instead of `entry` I'd expect something like: `{date, title, subTitle, data}`

2022-09-29 17:09 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +    <dl
Don't use dl/dd in this section. Those are semantics for key/value data lists.

2022-09-29 17:09 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +const Details = ({ entry }) => (
The type for `data` here should be something like `Record<string, ReactNode>` (check on `ReactNode`.. not sure what type is correct but something that can either be a string or a JSX element).

That way, callers of `CollapsibleDataList` can pass in the `CodeListElement` themselves. And this component here does not need to worry about it.

2022-09-29 17:10 UTC, WesleyKapow commented on src/components/core/code-list.tsx
> +    <dt className="ctw-w-1/3 ctw-flex-shrink-0 ctw-font-medium">{label}</dt>
Don't use `dt` and `dd` here.

2022-09-29 17:10 UTC, WesleyKapow commented on src/components/core/code-list.tsx
> +  >
This component should not display the label.

2022-09-29 17:13 UTC, WesleyKapow commented on src/components/content/conditions-history.tsx
> +          value: getAllCodes(condition),
This is where you'd use `CodeList` something like `value: <CodeList codes={getAllCodes(condition)}/>`

2022-09-30 14:09 UTC, luthfib commented on src/components/core/code-list.tsx
> +    key={label + Math.random}
Dont use math.Random for keys as that will confuse React, and it might not diff correctly

2022-10-03 17:56 UTC, WesleyKapow requested changes

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/content/conditions-history-drawer.tsx
> +        })}
ConditionHistory is a component and should be used like any other component `<ConditonHistory>`

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/content/conditions-history.tsx
> +        data: [...detailData],
You are spreading the detailData array to make another array, why?

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/core/condition-history-list.tsx
> +export const ConditionHistoryList = ({
Change name and file name.

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/core/condition-history-list.tsx
> +          </div>
Pull this out into `ConditionHistory` component.

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/core/condition-history-list.tsx
> +};
This looks specific to conditions while trying to make a generic `DataListStackEntry`. As mentioned in another comment, if you pull out the condition specific stuff into `ConditionHistory`, then this can be a generic component.

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/core/condition-history-list.tsx
> +  const displayedEntries =
This isn't used.

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/core/condition-history-list.tsx
> +      {!showAll && limit && entries.length > limit && (
Would change to just `!showAll`

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/core/condition-history-list.tsx
> +  const [showAll, setShowAll] = useState(false);
Lot of your logic can be simplified if you initialize this based on `!limit || entries.length <= limit`.

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +}: DataListStackEntry) => {
This should take a `CollapsibleDataListProps` that should be defined above the component and exported.

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +      <div className="ctw-">
`ctw-`?

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +        className={cx("ctw-h-5 ctw-w-5", !isDetailShown ? "" : "ctw-rotate-90")}
slightly nicer use of cx -- `cx("ctw-h-5 ctw-w-5", {"ctw-rotate-90": !isDetailShown})`

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +      {data.map(({ label, value }) => {
Filter out those without value here, using `filter`.. be careful not to filter out ZEROs!

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +              // eslint-disable-next-line react/no-array-index-key
???

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +    <dl className="ctw-space-y-2 ctw-p-4" key={id}>
`key` only needed when looping over things.

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +      <div> Details </div>
Why spaces around `Details`?

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/core/code-list.tsx
> +export const CodeList = ({ codes }: any) => (
Define, export and use a `CodeListProps`.

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/core/code-list.tsx
> +        }
1. Are there possibly empty codes? Filter out before the loop.
2. `key` is needed when doing loops.
3. This is only rendering the code? Mock shows display/text, code, system right?

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/content/conditions-history.tsx
> +  // move from here to drawer
???

2022-10-03 17:56 UTC, WesleyKapow commented on src/components/content/conditions-history.tsx
> +          value: <CodeList codes={getAllCodes(condition)} />,
Refactor in favor of Luthfi's new `condition.knownCodes`

2022-10-03 18:53 UTC, WesleyKapow commented on src/components/core/drawer.tsx
> +}) {
Do not make generic components non-generic! This should not know anything about conditions!

2022-10-04 14:09 UTC, WesleyKapow commented
Please add screenshots to PR description!

2022-10-04 14:38 UTC, WesleyKapow requested changes
Handful of visual differences from mock.

1. Ensure font colors match (purple instead of blue).
2. There should be whitespace between each collapsible-data-list.
3. If there's no date provided, check with Jessie on what to display, but we definitely don't want things to fall out of alignment.
4. Check with Jessie on what should be clickable to make the details expand. Whatever area is clickable should have a pointer cursor.

![Screen Shot 2022-10-04 at 10 30 31 AM](https://user-images.githubusercontent.com/1568246/193847705-dd2e0f1d-4e15-4dd8-9736-33551e2d4333.png)
![Screen Shot 2022-10-04 at 10 18 41 AM](https://user-images.githubusercontent.com/1568246/193847719-455cd91b-db50-4592-a651-b8634a504950.png)

2022-10-04 14:38 UTC, WesleyKapow commented on .changeset/orange-parents-clap.md
> +Condition History Panel now has a stacked UI list detailing previous occurrences of different encounters. There is a preview summary card followed by a detailed card for each of the different encount
Encounters?

2022-10-04 14:38 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
>          <div className="ctw-flex ctw-space-x-4 ctw-text-primary-dark">
Spacer classes are only needed when adding white space between child elements. This div only has one child and so `ctw-space-x-4` is not doing anything and can be removed.

Can also probably remove `ctw-flex`.

2022-10-04 14:38 UTC, WesleyKapow commented on src/components/core/coding-list.tsx
> +  <div className="ctw-text-gray-900 ctw-flex ctw-items-baseline -ctw-space-x-6">
`ctw-flex ctw-items-baseline -ctw-space-x-6` any of this actually needed?

2022-10-04 14:38 UTC, WesleyKapow commented on src/components/core/coding-list.tsx
> +    <div className="ctw-flex ctw-flex-col ctw-space-y-1">
Bump the `space-y` here. Look at the figma, there should be a noticeable whitespace between each block of codings. You can use figma to see the rough gap size, I see 15px in figma (make sure you see the same!). So round that up to 16px to align with tailwind.

2022-10-04 14:38 UTC, WesleyKapow commented on src/components/core/coding-list.tsx
> +        <div className="ctw-flex-grow">
`flex-grow` needed here?

2022-10-04 14:38 UTC, WesleyKapow commented on src/components/content/conditions-history.tsx
> +        <div className="ctw-pad-0 ctw-flex ctw-space-x-10 ctw-space-y-10 ctw-text-2xl ctw-text-black">
Which of these classes is actually needed? You can use chrome dev tools to toggle classes, select the element and then `styles` and `.cls`:
 
![Screen Shot 2022-10-04 at 10 24 20 AM](https://user-images.githubusercontent.com/1568246/193845314-56442c72-ddfc-499f-b41e-67c871bf3b42.png)

2022-10-04 14:38 UTC, WesleyKapow commented on src/components/content/conditions-history.tsx
> +        <div className="ctw-flex ctw-p-2 ctw-text-sm ctw-text-black">
Which of these classes is actually needed?

`ctw-p-2` is causing this to get indented which is different than the design. If you want to create whitespace BETWEEN elements, please use a `space-` class on a parent element/div.

2022-10-04 14:38 UTC, WesleyKapow commented on src/components/core/collapsible-data-list-stack.tsx
> +        <>
Fragment not needed when only wrapping a single thing.

2022-10-04 14:38 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +      <div className="ctw-text-sm"> Details </div>
Why spaces around ` Details ` word?

2022-10-04 14:38 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +      <div className="ctw-text-sm"> Details </div>
Check with figma design, I believe this has a different font color.

2022-10-04 14:38 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +            // eslint-disable-next-line react/no-array-index-key
Remove.

2022-10-04 14:38 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +        .filter((d) => !!d.value)
What if `d.value == 0`?

2022-10-04 14:38 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +            <dd className="ctw-flex-grow">{value}</dd>
So I think `ctw-flex-shrink-0` and `ctw-flex-grow` are not needed. BUT it looks like `dd` by default have a margin, so remove that by adding `ctw-m-0` to `dd`.

2022-10-04 14:38 UTC, WesleyKapow commented on src/components/core/collapsible-data-list.tsx
> +      <div className="ctw-text-gray-900 ctw-flex ctw-items-baseline ctw-space-x-4">
For all of these classes, please verify what is actually needed.

2022-10-04 14:59 UTC, luthfib commented
@WesleyKapow Asked design what the blue would be in our app and they said it would be the dark purple. So in this case any customer would override that purple with the desired blue or whatever color they want.

2022-10-04 17:09 UTC, WesleyKapow requested changes

2022-10-04 17:09 UTC, WesleyKapow commented on src/components/core/collapsible-data-list-stack.tsx
> +        <div className="ctw-pad-2">
What's `pad-2` do?

2022-10-04 17:09 UTC, WesleyKapow commented on src/components/content/conditions-history.tsx
>          </div>
Unlikely we will ever want a CollapsibleDataListStack that doesn't have whitespace between the lists. Therefore, the component should handle the whitespace.

2022-10-04 18:33 UTC, luthfib commented on src/components/core/collapsible-data-list.tsx
> +          <div>{subTitle}</div>
This should be have a ctw-text-content-light

2022-10-04 18:44 UTC, luthfib commented on src/components/core/collapsible-data-list.tsx
> +  <div className="ctw-divide-y ctw-rounded-lg ctw-border ctw-bg-bg-lighter">
I dont think this need ctw-border

2022-10-04 18:45 UTC, luthfib commented on src/components/core/collapsible-data-list.tsx
> +  <div className="ctw-divide-y ctw-rounded-lg ctw-border ctw-bg-bg-lighter">
Also add ctw-rounded-lg to the box that expands the details card

2022-10-04 18:47 UTC, luthfib commented on src/components/core/collapsible-data-list.tsx
> +  <div className="ctw-divide-y ctw-rounded-lg ctw-border ctw-bg-bg-lighter">
I dont think you need `ctw-divide-y` either

2022-10-04 18:50 UTC, luthfib commented on src/components/core/collapsible-data-list.tsx
> +            className="ctw-text-gray-900 ctw-flex ctw-items-baseline ctw-space-x-4"
This is a weird way to push the content out, I don't even think you need it.

2022-10-04 18:51 UTC, luthfib commented on src/components/core/collapsible-data-list.tsx
> +            <dd className="ctw-m-0">{value}</dd>
I dont think `ctw-m-0` is used anywhere

2022-10-04 19:24 UTC, luthfib approved these changes
LGTM

2022-10-04 19:41 UTC, merged