Ctw 1200/rewire use history
zeus-health/ctw-component-library pull request #831
Opened 2023-06-15 01:17 UTC by pmadria3

This PR is in draft to rewire history and version query

2023-06-20 17:06 UTC, bryanjknight requested changes

2023-06-20 17:06 UTC, bryanjknight commented on src/components/content/resource/history.ts
> +      ? withTimerMetric(
Let's break these up into two functions; it's a bit hard to read with the inline if-else statement

2023-06-21 17:49 UTC, WesleyKapow requested changes
Looks great, few nitpicks and then it'll be good to go!

2023-06-21 17:49 UTC, WesleyKapow commented on src/components/content/resource/history.ts
> +      return "";
Let's make sure we don't silently error if we accidentally use this when it isn't setup.
```suggestion
      throw new Error(`Resource type to FQS query not implemented yet for ${resourceType}`);
```

2023-06-21 17:49 UTC, WesleyKapow commented on src/services/fqs/queries/versions.ts
> +      return "";
Another `throw` here.

2023-06-21 17:49 UTC, WesleyKapow commented on src/services/fqs/queries/fragments/condition.ts
> +export const fragmentConditionHistory = gql`
What's the difference between this and the one above? Is there a way to DRY this up?

2023-06-21 17:49 UTC, WesleyKapow commented on src/components/content/resource/history.ts
> +export async function getVersionHistoryFQS<T extends ResourceTypeString>(
```suggestion
async function getVersionHistoryFQS<T extends ResourceTypeString>(
```

2023-06-21 18:54 UTC, WesleyKapow commented on src/components/content/resource/history.ts
> +export function filterLensandSummary<T extends ResourceTypeString>(
nit: `filterLens**A**ndSummary` (capital A)

2023-06-21 18:54 UTC, WesleyKapow commented on src/components/content/resource/history.ts
> +  enableFQS = false,
nit: Do we need a default here? Do all consumers of this now explicitly pass this?

2023-06-22 14:14 UTC, merged