CTW-1240 Distinguish builder and outside data in allergy component
zeus-health/ctw-component-library pull request #852
Opened 2023-06-21 19:41 UTC by eric-gunther

2023-06-21 21:27 UTC, eric-gunther commented on src/components/content/allergies/helpers/history.tsx
>    const tokens = allergy.knownCodings.map((coding) => `${coding.system}|${coding.code}`);
We currently get the history for a given allergy by searching for other allergies with a matching code/system. However many allergies are just going to have a codeable concept containing only a text value (like "bee pollen") and this will not find other allergies in the FHIR store with just that text value.

Since we're already getting all of the patients allergies in the first request to build the table I suggest we just use that same set of data to determine the history for a single allergy.

2023-06-21 21:27 UTC, eric-gunther commented on src/components/content/allergies/patient-allergies.tsx
> +
This seems like a very awkward way to get the user's builder ID so that I can pass it along to the columns function, but I couldn't find a better precedent elsewhere in the codebase. Am I doing something wrong?

2023-06-22 14:15 UTC, mrosata commented on src/components/content/allergies/helpers/allergies-filter.tsx
> +  });
To make the `Map<string, AllergyModel>` _(instead of needing `string|undefined` as the map key)_ We could use lodash `lowerCase(this.display)` which would ensure that key is always a string, as lodash will return empty string when passed undefined.

---

Mini rant: The reason TypeScript would have prodded us in the `Map<string | undefined, AllergyModel>` direction instead of plain `Map<string, AllergyModel>` is because our getter `allergyModel.lowercaseDisplay ` _(and in turn `allergyModel.display`)_ returns `string|undefined`. Those accessor helpers on our FHIR models that do their best to return some meaningful value _(if possible)_ by cascading through possibly undefined FHIR resource attributes, should probably also return a static type like `string`.

There are a few places this might not play well, but with properties like `display` or `lowercaseDisplay` it feels always getting a string would simplify some typing inside components.

It would even simplify some code. It looks like @bryanjknight had to implement `lowercaseDisplay` like this
```ts
  get lowercaseDisplay(): string | undefined {
    return this.display ? this.display.toLowerCase() : this.display;
  }
```
because I'm assuming he didn't want to have to write
```ts
this.display ? this.display.toLowerCase() : this.display;
```
in multiple places. However, if `allergyModel.display` always returned a string, not only could `lowercaseDisplay` have been written like this
```ts
  get lowercaseDisplay(): string | undefined {
    return this.display.toLowerCase();
  }
```

but it likely wouldn't have needed to have been created in the first place as in the view layer one could simply and safely do things like
```tsx
  <div>{allergy.display.toLowerCase}</div>
```

2023-06-22 15:26 UTC, mrosata commented on src/components/content/allergies/patient-allergies.tsx
> +
I think you could do
```tsx
const { builderId } = useContext(CTWStateContext)
```
But since it's on that context already, maybe it's better to add the builderId to the return value of [`useCTW()`](https://github.com/zeus-health/ctw-component-library/blob/773d86c48047dbb073a2917623b640e523e623e0/src/components/core/providers/use-ctw.ts#L40-L43) so it would instead be
```tsx
const { builderId } = useCTW();
```
or we could make an `useBuilderId`
```tsx
function useBuilderId() {
  const ctx = useContext(CTWStateContext);
  return ctx.builderId;
}
```

2023-06-22 15:56 UTC, mrosata approved these changes

2023-06-22 19:59 UTC, bryanjknight commented on src/fhir/models/fhir-model.ts
> +      throw new Error("Expected builder owner tag missing or malformed.");
Throwing an error recently burned me where it resulted in the entire page not rendering any data (hence a zero moment". I would suggest having some additional safe guards, particularly around the owner tag splitting given some of our older data may not have it in the same format

2023-06-27 20:16 UTC, eric-gunther commented on src/components/core/providers/use-ctw.ts
> +    builderId: context.builderId || "",
Unsure how I feel about this coalesce but it makes using this `builderId` downstream much easier...

2023-06-27 21:32 UTC, mrosata commented on src/components/content/allergies/helpers/allergies-filter.tsx
> +    }
Regardless of which condition matches, they both do the same `allergyDataMap.set(lowercaseDisplay, allergy)`. Perhaps it's broken out into multiple if statements for readability, if so we could use variables for the conditions to summarize
```suggestion
    const allergyOwnedByBuilder = allergy.ownedByBuilder(builderId);
    const existingAllergyNotOwned = !existingAllergy.ownedByBuilder(builderId);
    if (!existingAllergy || (allergyOwnedByBuilder && existingAllergyNotOwned)) {
      allergyDataMap.set(lowercaseDisplay, allergy);
    }
```

2023-06-28 20:11 UTC, WesleyKapow commented on src/components/core/table/table.scss
> +    height: calc(100% - 3px) !important;
3px? Was 1 not enough? This will cause the vertical centering to be slightly off.

2023-06-28 20:14 UTC, eric-gunther commented on src/components/core/table/table.scss
> +    height: calc(100% - 3px) !important;
I had changed to 3px in the course of some troubleshooting because the bottom border was then disappearing, but now it seems to be working with just 1px.

2023-06-29 15:22 UTC, WesleyKapow requested changes

2023-06-29 15:22 UTC, WesleyKapow commented on src/components/content/allergies/helpers/allergies-filter.tsx
> +  return uniqueAllergies;
Simplification:

```ts
// Bump builder owned allergies to the front, so uniqBy favors them!
const builderOwnedFirst = orderBy(sortedByDate, (a) => a.ownedByBuilder(builderId), 'desc')
return uniqBy(builderOwnedFirst, 'lowercaseDisplay')
```

`orderBy(sortedByDate...)` should preserve the date ordering too.. so it will end up being, all builder owned allergies first, sorted by date, followed by all non-builder owned allergies sorted by date.

2023-06-29 15:22 UTC, WesleyKapow commented on src/components/content/allergies/helpers/column.tsx
> +              {allergy.ownedByBuilder(builderId) ? <CheckIcon /> : <></>}
As mentioned elsewhere, this would instead be `<FontAwesomeIcon icon={faCheck}/>`

2023-06-29 15:22 UTC, WesleyKapow commented on src/components/content/allergies/helpers/column.tsx
> +          <div>{allergy.recordedDate} </div>
Trailing space inside div needed here?

2023-06-29 15:22 UTC, WesleyKapow commented on src/components/content/allergies/patient-allergies.tsx
> +  };
Ah neat! I can also see us rolling this into `openDetails` in the future, if this becomes the standard across our resources. Could be an option passed to `useResourceDetailsDrawer`.

2023-06-29 15:22 UTC, WesleyKapow commented on src/components/content/allergies/patient-allergies.tsx
> +            }
This is interesting to me. So dismiss is treated like read? Would we ever want to distinguish these? I could see the UI treating dismissed as read (not bold), but unclear if we want to act like it was read in this case.

2023-06-29 15:22 UTC, WesleyKapow commented on src/components/content/hooks/use-toggle-read.ts
> +   * Function to call to toggle the archive status of the FHIR model
```suggestion
   * Function to call to toggle the read status of the FHIR model
```

2023-06-29 15:22 UTC, WesleyKapow commented on src/components/content/hooks/use-toggle-read.ts
> +   * True when `toggleArchive` is called
```suggestion
   * True when `toggleRead` is called
```

2023-06-29 15:22 UTC, WesleyKapow commented on src/components/content/hooks/use-toggle-read.ts
> + * This hook is toggles the read status for the specified FHIR model.
```suggestion
 * This hook toggles the read status for the specified FHIR model.
```

2023-06-29 15:22 UTC, WesleyKapow commented on src/components/content/hooks/use-toggle-read.ts
> +    // the old read/restore text.
```suggestion
    // the old mark as read/new text.
```

2023-06-29 16:34 UTC, eric-gunther commented on src/fhir/models/fhir-model.ts
> +  ownedByBuilder(builderId: string): boolean {
`ownedByBuilder` is intended to indicate if the data is "first party" data that your organization wrote to Zus. `isSummaryResource` indicates if the resource was generated by our lens process - it's not really 3rd party or 1st party data, it's just special Zus data that merges the two. I think these are meaningful distinctions that drive different behavior in the app.

2023-06-29 16:43 UTC, eric-gunther commented on src/components/content/allergies/patient-allergies.tsx
> +            }
I think this is subject to change, but I believe "read" means "I interacted with this record" - ie. you clicked it to view the details, you dismissed it, or you explicitly clicked "Mark as Viewed" (note that "read" and "viewed" have been used interchangeably and I think we're still debating what the final word may be).

2023-06-29 16:50 UTC, eric-gunther commented on src/components/content/hooks/use-toggle-archive.ts
> +  const handleToggleDismiss = useCallback(async (model: FHIRModel<fhir4.Resource>) => {
Did that so I could use it in the row click handler:

```const { toggleRead } = useToggleRead(QUERY_KEY_PATIENT_ALLERGIES, QUERY_KEY_BASIC);

  const handleRowClick = (record: AllergyModel) => {
    if (!record.isRead) {
      toggleRead(record);
    }
    openDetails(record);
  };```

2023-06-29 16:54 UTC, eric-gunther commented on src/components/content/allergies/patient-allergies.tsx
> +  };
Yeah agreed that there's room for refactoring once it's universally rolled out across components.

2023-06-29 17:26 UTC, eric-gunther commented on src/fhir/allergies.ts
> +  }, [basicsQuery.data, patientAllergiesQuery.data]);
Yeah it's kinda ugly. Given where I'm at with this PR (and the fact that you didn't mark this as blocker) I'd like to punt on this refactor and address it as I need to add similar functionality for other resources.

2023-06-29 17:28 UTC, eric-gunther commented
Fair amount of changes made via PR feedback but functionality still looking good, here's the latest in a video - 

https://github.com/zeus-health/ctw-component-library/assets/97455910/8d5de355-de1a-4498-9f41-7b32ca99e2c6

2023-06-29 17:37 UTC, WesleyKapow submitted a review, later dismissed
Looks good, you should also remove the `CheckIcon` you added.

2023-06-29 18:51 UTC, WesleyKapow approved these changes

2023-06-29 18:55 UTC, merged