Ctw 353/update logic in condition display
zeus-health/ctw-component-library pull request #87
Opened 2022-09-28 13:49 UTC by luthfib

This pr adds more codes to filter for duplicate conditions

TODO: 
- [ ] Fix type issue in fhir/conditions.ts
- [ ] Find more conditions to test 
- [ ] Changeset

2022-09-28 15:23 UTC, pmadria3 commented on src/App.tsx
> +    <CTWProvider env="sandbox" authToken={VITE_AUTH_TOKEN} theme={{}}>
probably should use dev here

2022-09-28 17:24 UTC, pmadria3 commented on src/fhir/conditions.ts
> +        confirmedCodeDict[code].push(modelCode as string);
nit: can just use conditionModel[code] directly instead of setting to modelCode

2022-09-28 17:24 UTC, pmadria3 commented on src/fhir/conditions.ts
> +        return codesLookup[code].includes(modelCode as string);
same nit as above

2022-09-28 17:25 UTC, pmadria3 submitted a review, later dismissed
Small nits but otherwise LGTM

2022-09-28 17:33 UTC, pmadria3 approved these changes
LGTM

2022-09-29 13:40 UTC, WesleyKapow requested changes
Quick feedback -- It'd be useful if we could have an array of SYSTEM URLs of systems to use. Where all we need to do is edit this array to edit how things work. I think this means moving away from having explicit `icd9Code` and `icd10CMCode` getters on the model.

We're going to use this array in a few places. For matching and removing. And also for history lookup.

2022-09-29 14:14 UTC, luthfib commented
That makes sense. That's where my thought was with the codes array but an array of system urls would simplify it even more as we wouldnt have to add methods to the condition model

2022-10-03 03:10 UTC, pmadria3 commented on src/models/conditions.ts
> +  get availableCodes(): fhir4.Coding[] {
change availableCodes into `allCodeSystems` or `allSystemCodes`?

2022-10-03 17:03 UTC, WesleyKapow approved these changes
Handful of naming nitpicks to make this a bit more clear, otherwise LGTM

2022-10-03 17:03 UTC, WesleyKapow commented on src/models/conditions.ts
> +  get allSystemCodings(): fhir4.Coding[] {
How about `knownCodings`?

2022-10-03 17:22 UTC, WesleyKapow approved these changes

2022-10-03 17:23 UTC, merged