CTW-333: Filter out non-builder records using the builder ID in the JWT
zeus-health/ctw-component-library pull request #89
Opened 2022-09-29 19:14 UTC by melocule

Components that were meant to display only records owned by the builder now address the case of shared records between builders. Rather than filtering out by non-builder tags, the query filters for the builder ownership tag.

2022-09-30 00:02 UTC, luthfib requested changes
Looking good but a couple of show stoppers

2022-09-30 00:02 UTC, luthfib commented on src/fhir/search-helpers.ts
> +    _tag: builderTag,
This doesnt look right to me. Might have to look around and ensure but I think you would create duplicates with this. You might be able to do something like: 

```
  _tag:not": nonBuilderTags.join(","),
  _tag: builderTag,
```

2022-10-03 14:14 UTC, luthfib commented
I also wonder if we want to get the auth from the FHIR client or if we want to allow the ctw provider to pass the auth token, as I think that will be a more generic approach that will decouple the FHIR client and the auth token.. thoughts @WesleyKapow

2022-10-03 16:13 UTC, melocule commented on src/fhir/client.ts
> +};
There's a property in the JWT that's actually an array of strings, just realized I can type it as `string | string[]` though so I'm going with that!

2022-10-03 17:05 UTC, melocule commented on src/fhir/search-helpers.ts
> +    _tag: builderTag,
Thanks for the catch! Didn't see any resources with both, but apparently whether those tags overlaps can change with time.

2022-10-03 17:09 UTC, WesleyKapow commented
@luthfib agreed that getting it from FHIRClient is hacky. I'm just not thrilled with having to pass the accessToken around everywhere which is why I was opting for the hacky approach for now (no refactoring or plumbing of an argument needed).

Eventually we may need the `CTWProvider` to hand us something that we can pass around everywhere and hang stuff off of that. Things like `env`, `accessToken`, user details, etc.

2022-10-03 17:15 UTC, WesleyKapow requested changes

2022-10-03 17:15 UTC, WesleyKapow commented on src/fhir/client.ts
> +  SYSTEM_ZUS_BUILDER_ID: string;
Here you are saying this has a key of the literal string: `SYSTEM_ZUS_BUILDER_ID`.

2022-10-03 17:15 UTC, WesleyKapow commented on src/fhir/client.ts
> +export function getJWT(fhirClient: Client): ZusJWT {
s/getJWT/getClaims

The accessToken is the JWT, I believe you are decoding it and getting the claims data.

2022-10-03 17:17 UTC, WesleyKapow commented on src/fhir/client.ts
> +export type ClientAuth = {
Need to be exported?

2022-10-03 18:37 UTC, WesleyKapow approved these changes
Side note -- avoid super-long-branch-names-that-describe-everything :P (it could have been something like `CTW-333/filter-by-owner-tag`)

2022-10-03 18:52 UTC, WesleyKapow commented
@melocule may need to resolve merge conflicts with main to get CI going.. not sure.. CI has been a little weird lately.

2022-10-03 19:35 UTC, luthfib approved these changes

2022-10-03 19:36 UTC, merged