CTW-1283 Moving view FHIR to quick actions for allergies & immz
zeus-health/ctw-component-library pull request #921
Opened 2023-07-06 17:36 UTC by eric-gunther

2023-07-06 18:44 UTC, WesleyKapow requested changes
ViewFHIR is also used for care-teams, documents, and timeline.

I strongly suggest trying to get this working within `ResourceTable` so that it is setup in a single place for all resources.

As mentioned in slack, you should be able to do something like `rowActions={<div className="ctw-flex ctw-space-x-2"><ViewFHIRThingy/>{rowActions}</div>}`

The `ctw-flex ctw-space-x-2` part is in there to align with how other row action buttons are setup and spaced.

2023-07-07 16:24 UTC, WesleyKapow approved these changes
Looks great! Only a couple of notes/nitpicks.

2023-07-07 16:24 UTC, WesleyKapow commented on src/components/core/view-fhir.tsx
>          event.stopPropagation();
This is not needed anymore as the parent of where row actions get inserted (in `table-rows.tsx` does this at the parent `td` level).

2023-07-07 16:24 UTC, WesleyKapow commented on src/components/content/resource/resource-table.tsx
> +  RowActions?: TableProps<T>["RowActions"];
Props should be camelCase (lower case first). When I setup `ResourceTable`, I made it `rowActions` but was refactoring a lot and didn't want to do more and switch the other cases of `RowActions` to `rowActions`.

2023-07-07 16:24 UTC, WesleyKapow commented on src/components/content/resource/resource-table.tsx
> +      : undefined;
Beautiful!

2023-07-07 17:01 UTC, eric-gunther commented on src/components/content/resource/resource-table.tsx
> +  RowActions?: TableProps<T>["RowActions"];
Yeah I normally use lowercase for props but when I made this lowercase I was getting an error trying to reference rowActions as a component in JSX. I had noticed that the `Table` component has `RowActions` with a capital R and I figured it was because of this reason.
![image](https://github.com/zeus-health/ctw-component-library/assets/97455910/6be6bb07-a6ab-44c7-b407-642635a434af)

2023-07-07 17:12 UTC, WesleyKapow commented on src/components/content/resource/resource-table.tsx
> +  RowActions?: TableProps<T>["RowActions"];
Oh right! That's why it was originally capitalized.. doh! OK carry on!

2023-07-07 17:48 UTC, WesleyKapow approved these changes

2023-07-07 18:21 UTC, bryanjknight approved these changes

2023-07-07 18:21 UTC, merged