CTW-1286 Generic read/dismiss
zeus-health/ctw-component-library pull request #926
Opened 2023-07-07 14:23 UTC by eric-gunther

2023-07-07 14:31 UTC, eric-gunther commented on src/components/content/resource/resource-table.tsx
> +  queryKeyToInvalidateOnReadDismiss,
This feels a little awkward - if you enableDismissAndRead actions then you most likely need to have a specific query invalidated when dismiss/read happen. So you don't _need_ to also pass in a `queryKeyToInvalidateOnReadDismiss` but you probably should. Is there a more intelligent way to combine these into a single prop? Like an object called `dismissAndReadConfig` that contains an enable property and a query key to invalidate property? Or is this approach reasonable?

2023-07-07 14:31 UTC, eric-gunther commented on src/fhir/document.ts
> +  };
It definitely smells to keep re-writing basically this same thing to retrieve the Basic resources along with the actual clinical resources. However I think a lot of this is going to be up for refactoring soon when we officially pull the plug on querying ODS, so I'm of the mind that we can punt a cleaner refactoring of this data access layer until that time. FWIW documents is the last resource that I'm implementing this for (later we'll need it for labs...) so it's not like this pattern will grow out of hand too quickly.

2023-07-07 17:39 UTC, WesleyKapow requested changes
Handle of nits and questions, don't think there was anything major.

Love the new place within `ResourceTable` for us to put generic actions!

2023-07-07 17:39 UTC, WesleyKapow commented on src/components/content/document/unread-documents-notification.tsx
> +  }, [getRequestContext]);
Suggestion: pull this out into a `useBuilderId` hook. I'd setup a new `use-builder-id.ts` file in `core/providers`.

2023-07-07 17:39 UTC, WesleyKapow commented on src/components/content/zus-aggregated-profile/zus-aggregated-profile-tabs.tsx
> +      <div className="ctw-flex ctw-items-center ctw-space-x-2">
Just calling it out that you're increasing the space between the "documents" and the beta label. It use to be `space-x-1` and now it'll be `space-x-2`.

2023-07-07 17:39 UTC, WesleyKapow commented on src/fhir/document.ts
> +  };
Absolutely agreed. This is pretty gross. And agreed on punting for now. Probably good call to just wait until we kill ODS. That should reduce the noise in these areas and make it a little easier to clean this up.

2023-07-07 17:39 UTC, WesleyKapow commented on src/components/content/document/unread-documents-notification.tsx
> +export const UnreadDocumentsNotification = () => {
I could see us benefiting from changing `UnreadNotification` to take an array of models as a prop and it do the "unreadOutside" logic. That way all of our resource notifications would simply be:

```ts
export const UnreadDocumentsNotification = () => {
  const query = usePatientDocuments();
  return <UnreadNotification data={query.data}/>
}
```

^ just a thought, not a suggestion for this PR.

2023-07-07 17:39 UTC, WesleyKapow commented on src/components/content/resource/resource-table.tsx
> +  }
nit: Lodash's `compact` can simplify this a bit.

```ts
const queryKeysToInvalidate = compact([QUERY_KEY_BASIC, queryKeyToInvalidateOnReadDismiss])
```

2023-07-07 17:39 UTC, WesleyKapow commented on src/components/content/resource/resource-table.tsx
> +    onRowClick || enableDismissAndReadActions
If there's no `onRowClick`, we probably don't want to mark it as read right? There wouldn't be any details getting opened in this case.

So this would be `onRowClick ?` without the `|| ...`

2023-07-07 17:39 UTC, WesleyKapow commented on src/components/content/resource/resource-table.tsx
> +    enableDismissAndReadActions && data.length > 0
Why does `data.length > 0` matter?

2023-07-07 17:39 UTC, WesleyKapow commented on src/components/content/resource/resource-table.tsx
> +          "ctw-tr-dismissed": enableDismissAndReadActions && record.isDismissed,
Why add the `enableDismissAndReadActions` guard here? Shouldn't we display it as dismissed if it is, no matter the `enableDismissAndReadActions` bool?

2023-07-07 17:39 UTC, WesleyKapow commented on src/components/content/resource/resource-table.tsx
> +            enableDismissAndReadActions && !record.ownedByBuilder(userBuilderId) && !record.isRead,
This one makes more sense. Only render as unread of you can mark it as read.

2023-07-07 17:39 UTC, WesleyKapow commented on src/components/content/resource/resource-table.tsx
> +    }
This ends up being the same as `queryKeysToInvalidate` from above.. should you pass that in instead of `queryKeyToInvalidate`?

2023-07-07 17:39 UTC, WesleyKapow commented on src/components/content/resource/resource-table.tsx
> +  queryKeyToInvalidateOnReadDismiss,
You're not currently using this right? When would we? I think we only need to invalidate the basics query. Any hooks that depend on basics would automatically get updated when `useBasics` gets updated. So I think this can be removed unless I'm missing something.

2023-07-10 14:27 UTC, eric-gunther commented on src/components/content/resource/resource-table.tsx
> +    onRowClick || enableDismissAndReadActions
Ha that's a great point, derp

2023-07-10 15:23 UTC, WesleyKapow submitted a review, later dismissed
LGTM

2023-07-10 17:35 UTC, luthfib approved these changes

2023-07-10 17:45 UTC, merged