CDEV-204 patient history empty states
zeus-health/ctw-component-library pull request #962
Opened 2023-07-13 19:15 UTC by sarahmangels

expand table empty states to include request records button and show spinner while request is in progress

https://zeushealth.atlassian.net/browse/CDEV-204

![image](https://github.com/zeus-health/ctw-component-library/assets/95938276/d47e3343-2d3d-457d-a761-9cc329afbc47)

![image](https://github.com/zeus-health/ctw-component-library/assets/95938276/1a71290d-b97d-4cfe-9ce7-72d5541322c1)

2023-07-13 19:31 UTC, eric-gunther commented on src/components/content/patient-history/use-patient-history.tsx
> +  return isFetching;
Should there be more uses of `setIsPolling` and `setIsFetching` here?

2023-07-13 19:46 UTC, eric-gunther requested changes

2023-07-13 19:46 UTC, eric-gunther commented on src/components/content/patient-history/use-patient-history.tsx
> +          provider.status === "done_with_errors"
We reference these statuses in a number of places now (eg. `patient-history-message-status.tsx`, `patient-history-table.tsx`), think we should have em as constants.

2023-07-13 19:46 UTC, eric-gunther commented on src/components/core/icons/refresh.tsx
> +export const RefreshIcon = ({ className }: { className?: string }) => (
Is there not an applicable font awesome icon for this?

2023-07-14 13:12 UTC, sarahmangels commented on src/components/core/icons/refresh.tsx
> +export const RefreshIcon = ({ className }: { className?: string }) => (
no :( Tai said the closest one in font awesome looked too much like an undo icon so she modified it

2023-07-14 13:17 UTC, sarahmangels commented on src/components/content/patient-history/use-patient-history.tsx
> +  return isFetching;
setIsPolling is being used to block this hook from being executed multiple times at once - so there can only be 1 poll going on at a time, so it makes sense to only call it once. 

setIsFetching is used to mark when the polling is complete so we only set it at the end once the API says the job is complete!

2023-07-14 13:43 UTC, sarahmangels commented on src/components/content/patient-history/use-patient-history.tsx
> +          provider.status === "done_with_errors"
hm wait i think it sort of is already?? its comparing provider.status which is type PatientRefreshHistoryMessageStatus (https://github.com/zeus-health/ctw-component-library/blob/5d8b23156ed5e9daf5bcf88867f4ef903e5dcd63/src/services/patient-history/patient-history-types.ts#L1) so it wont let me change the strings here to anything outside of that type

2023-07-14 14:24 UTC, eric-gunther commented on src/components/content/patient-history/use-patient-history.tsx
> +          provider.status === "done_with_errors"
Ah, well that seems fair enough. Won't block on it.

2023-07-14 14:25 UTC, eric-gunther submitted a review, later dismissed

2023-07-14 14:37 UTC, eric-gunther approved these changes

2023-07-14 14:39 UTC, merged